### ISSUE TITLE
How toget 2/3 + 1/3 columns with grids ?

### ISSUE THREAD

**Issue by brunob** [Semantic-Org/Semantic-UI#1057]
Hi, i'm searching a way to get a grid with columns like that :  2/3 total width + 1/3 total width

This example show what i can do for now, but it's not exactly 2/3 vs 1/3 : http://jsfiddle.net/s1e48tn0/

Does anyone knows if it's possible ?

Thanks :)

**Comment by MrFusion42** [comment]
Even when changing the `@columnCount`, one cannot have mixed grids (it would be hard to combine thirds with halves).

This codepen exemplifies some of the limitations: http://codepen.io/MrFusion42/pen/emajvo

Since this was a very important issue for my company, we worked on integrating grid mixins that act as generators, so that all of the needed CSS rules can be easily generated.

This is the same markup, but loading our [forked version](https://github.com/MrFusion42/Semantic-UI/tree/column-generators) of Semantic UI:  http://codepen.io/MrFusion42/pen/wBLKQj

I've submitted a pull request with the changes: [#2090](https://github.com/Semantic-Org/Semantic-UI/pull/2090).

**Comment by MrFusion42** [comment]
Added pull request #2095 for the branch _"next"_.  (Sorry, didn't notice that pull requests were not supposed to be on master)
