### ISSUE TITLE
disabling all animations/transitions

### ISSUE THREAD

**Issue by coreyfarrell** [Semantic-Org/Semantic-UI#1158]
I'm sorry if I've missed something, but I can't seem to find a documented way to disable animations.  Semantic-UI provides a clean good looking base for my UI's, but for me animations are not part of clean/responsive UI's.  I understand that others will disagree with this, but a way to turn them off would be excellent.

If I've missed something in the documentation I'm sorry.  As an example it would be great to have a transition: 'none' (for example to use with popup's).  As for css based animation it would be great if they were protected by lack of a class on body.  For example:

```
*:not(.ui.noanimate) .ui.reveal > .visible.content {
  /* transition properties */
}
```

.noanimate is just an example, I don't really care what the class name would be, just a way to say "no css transitions in any child of elements with this class".  Maybe instead we could have:

```
.ui.noamimate, .ui.noamimate * {
  -webkit-transition: none!important;
  -moz-transition: none!important;
  -ms-transition: none!important;
  transition: none!important;
}
```

**Comment by Pithikos** [comment]
Is this still valid? Current [site.variables](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L176) doesn't seem to have that.

In any case I have tried both and transition is still there.

```css
@transitionDuration: 0s;
@defaultDuration : 0s;
```

**Comment by bw2** [comment]
I just created a copy of semantic.css and deleted (almost) all *transition* and *animation* properties.

**Comment by darrenterhune** [comment]
Adding behaviour to the api to allow disabling transitions would be nice. CSS animations/transitions can really mess with a developer's head when dealing with testing suites. For example we have a rails app, and test using capybara system tests and have a few tests that behave really inconsistently because of transitions around modals and dropdowns. We've disabled css animations and jquery effects in our test environment by injecting some code into the test html document using custom middleware, but I cannot figure out how to do the same for semantic-ui `transition.js`.

**Comment by ethernidee** [comment]
There is still really no way to prevent animation/transition for particular dropdown or menu. No instant "hide" method at all. The lack of animation control prevents creating of responsive interface.
