### ISSUE TITLE
Support to "transparent" color.

### ISSUE THREAD

**Issue by rentalhost** [Semantic-Org/Semantic-UI#1206]
Like input, allow all others ui components to be transparent (without border, outline and backgrounds).

Applicable to:
- Button*
- Divider*
- Header**
- Label
- Segment

And others.

See this examples: http://jsfiddle.net/xmdbph6g/1/
- No make too sense, but it could can done.
  *\* Basically to remove background-color of inverse.

**Comment by geemang2000** [comment]
Agreed on not supporting too many colors.  Would it make sense to add a White color? http://semantic-ui.com/globals/site.html#colors   I believe it'd help handle usecase such as, icon buttons being used which should not have border (e.g. basic).

**Comment by loopmode** [comment]
I know this is rather old and closed, but I'd like to drop my two cents here.
In my own UI libs for various projects, my buttons supported a `pure` prop, which would render then as described here - no background, no borders etc.
The reason and use case for this was mainly using icons as buttons without losing semantics, and also without losing additional states like hover, disabled, active etc.
There are plenty situations where you just need the _behaviour_ and _functionality_ of a button, but not it's looks. Depending on the visuality of the project, it might be for example list item actions, or, pretty much the case even with SUI, the close-button of the Modal.

So, of course one can use an icon directly instead of a button. Then assign pointer/hand-cursor, hover-state/colors etc via CSS. But that's a) overhead and b) semantically incorrect - you end up with an icon that has `onClick` on it.
And of course you can do it yourself and prepare a "pure" CSS class and assign it to some buttons, but that too is overhead.

It would be much better to just do `<Button pure icon onClick={}><Icon name="remove" /><Button>`.

**Comment by zaunaf** [comment]
Also supporting this issue. Icon only button is always in demand. Spawning a brand new theme only for this feature seems overwhelming.
