### ISSUE TITLE
[Popup] Preserve Should Be Set to False by Default

### ISSUE THREAD

**Issue by Arkni** [Semantic-Org/Semantic-UI#1369]
##### ISSUE 1
when trying to remove the Popup definitely, that's not working for me and the popup still here.
Here is a [fiddle](http://jsfiddle.net/Arkni/v6h5pf6g/) that shows the isssue.
I found an old issue about that, this [comment](https://github.com/Semantic-Org/Semantic-UI/issues/760#issuecomment-39490577) of one of the owners said that :
Calling
```js
$('.ui.button').popup('remove');
```
will remove the popup from the DOM when you use 
```js
$('.ui.button').popup({preserve: true});
```
But sadly, doesn't work for me :(
What is the right way to definitely remove the popup from the DOM ?

##### ISSUE 2
Please check this [fiddle](http://jsfiddle.net/Arkni/qbenn4jh/)
For the first time, there is only one popup added to the DOM.
The *destroy* button is for destroying the popup
According to the same [comment](https://github.com/Semantic-Org/Semantic-UI/issues/760#issuecomment-39490577) , this
```js
$('.ui.button').popup('destroy')
```
removes all events and disables the popup that's ok, but when you click again on the *destroy* button this will add a new popup to the DOM.

**Comment by startswithaj** [comment]
This has to be documented

**Comment by jlukic** [comment]
@startswithaj 
It looks like the setting   `preserve` was accidentally set to `true` by default. I'll fix this in the next release. For now you can just add `$.fn.popup.settings.preserve = false;` or set it to false in your init.

**Comment by startswithaj** [comment]
@jlukic hey I appreciate the quick response. While this is in your mind could you clarify something for me. 

``` $('.ui.button').popup('remove popup').popup('destroy'); ``` is this the correct way of 'destroying' a popup or will calling ('destroy') remove it from the dom if the settings a default (after the fix above)?

If this is the case, could we put in in the documentation? In my mind calling destroy should remove any extra dom elements created. I didnt really follow the 'This was added because destroy is called when an existing component is re-initialized. ' logic?

**Comment by jlukic** [comment]
$('.ui.button').popup('destroy'); as long as `preserve: false`, otherwise as you stated.
