### ISSUE TITLE
HOW CAN I MAKE MENU WORK???

### ISSUE THREAD

**Issue by oroalej** [Semantic-Org/Semantic-UI#1419]
I've been searching for a solution for hours, the website lacks documentation on how this thing work.
i copy paste the menu in the semantic website..

```
        <div class="ui menu">
          <a class="active item">
            <i class="home icon"></i> Home
          </a>
          <a class="item">
            <i class="mail icon"></i> Messages
          </a>
          <div class="right menu">
            <div class="item">
              <div class="ui transparent icon input">
                <input type="text" placeholder="Search...">
                <i class="search link icon"></i>
              </div>
            </div>
          </div>
        </div>
```

i already added the address.js 

```
    <script src="/js/jquery-latest.js"></script>
<script src="/semantic-ui/dist/semantic.min.js"></script>
<script src="/js/address.js"></script>
```

UPDATE:

```
  $('.ui .item').on('click', function() {
      $('.ui .item').removeClass('active');
      $(this).addClass('active');
   }); 
```

**Comment by shangab** [comment]
Hi Semantic Team,

It is really undeniable that you put huge amount of work in this project. But the problem is (Or may as it appears to me). I go to semantic-ui website, I see a nice module (say a table with nice sliding check boxes for each row). I "innocently" copy the source that they labeled "literally" as "source" I go to my website and paste it.

Now bear in mind that I already have all semantic-ui JavaScript and CSS links in my page. I run the example and the table is "DEAD" not live as it appears in the website demo of semantic-ui. Please say the same thing about menus, dropdowns, sliding menus ...ect. The list goes on and on.

Am I missing something guys? please feedback.

Thanks,

**Comment by jholl** [comment]
do you have a live example of this not working?
here it is in [codepen](http://codepen.io/jholl/pen/KdZqZO).  Cut and Paste from docs, no css or js needed.

Check your debugger -- are you including jQuery?  Does jQuery init in time and before Semantic js?

**Comment by shangab** [comment]
Yes @jholl jQuery is there and before semantic. One more note please, look at this nice grids page:
http://semantic-ui.com/examples/grid.html

None of the examples in it shows the source, at least the HTML.

Regards,

**Comment by jholl** [comment]
is there a question?

for one, you can use your browser's inspect tool to see the source.

also there's an explanation of grids with source [within the docs](http://semantic-ui.com/collections/grid.html); you can get the idea of how they work there.
