### ISSUE TITLE
Sticky element is larger than its container, cannot create sticky

### ISSUE THREAD

**Issue by TITAN-UZ** [Semantic-Org/Semantic-UI#1490]
Hi!
How to fix this problem!

Sticky element is larger than its container, cannot create sticky

clear: both;
does not help

**Comment by muppetjones** [comment]
I am getting the same error, but due to sticky being applied to a previously empty element.
In short, I have a Django app that uses formsets to add a number of elements. I use js to add and remove these elements as needed. 
Without any elements, the sticky content is larger than the context is is applied to, but once a formset has been created, the sticky is smaller than the context. Unfortunately, even when I call 'sticky' after creating a single formset element, SemanticUI still claims the sticky is larger.
As mentioned in the documentation, I have tried a sticky refresh (before the call, after the call, within the formset function, etc), but this only causes the error to be thrown twice.
Any suggestions?


http://jsfiddle.net/urh9x2a9/20/

**Comment by jlukic** [comment]
That test case is difficult because you are using JS templating. Keep in mind calling `$('.ui.sticky').sticky('refresh');` before initializing, is the equivalent of initializing with no settings (aka no context) and then immediately calling ``refresh``.

Do you have a simpler test case that can produce the issues? Perhaps with static HTML?

**Comment by muppetjones** [comment]
Unfortunately, no. I can add extra br to fatten the context, which removes
the error.

I will try to reproduce the error without using the js template, but no
guarantees on when I'll be able to do it. For now, it works without sticky
(but not as cool =).

**Comment by muppetjones** [comment]
Another thought: refresh does not appear to work after initialization,
presumably because initialization fails.

**Comment by jlukic** [comment]
If i can get a simple test case I will re-open this issue. For now I'm going to go ahead and close things.

**Comment by startswithaj** [comment]
What can happen is you have two columns.

In the left hand column you have an accordion which is collapsed on init. 
In the right hand column you have a sticky which get initialised on load. 

The accordion collapsed is smaller than the content of sticky. Sticky rage quits.

One of the accordion blocks is then expanded by user. Sticky doesnt work.

**Comment by jlukic** [comment]
An example speaks a thousand words.

**Comment by startswithaj** [comment]
Sorry Jack, I will circle back around and provide working examples and better descriptions for all my tickets. We're converting an app from su 1 to 2 at the moment and everything is exploding. I pressed for time at the moment.

**Comment by srissel** [comment]
Hi guys,

I am currently experiencing the same situation:
My page's main content is appended via AJAX calls, which leads to having Semantic UI initialize sticky early than the rest of my page, leading to the exception described herein.

I tried to wrap my sticky initialization and catch the exception, in order to call a refresh via `jQuery.once();`
```
    try {
        $('#pagemenu.sticky')
        .sticky({
            offset: 60,
            context: '#maincontent'
        });
    } catch (e) {
        window.console.log("Error during sticky initialization.");
        // using jQuery.once to re-initialize sticky
    }
```

But unfortunately the browser doesn't step into the catch section.
Could you please help me to catch this exception?

**Comment by srissel** [comment]
EDIT: I think I was able to tackle this issue by using option `observeChanges: true` for the sticky module

**Comment by startswithaj** [comment]
I haven't looked at the code for this in a while, but I had a similar
problem. I'm pretty sure the reason your try catch doesn't work is because
the actual sticky initialisation is run with a setTimeout.

I.E If you run the following code you will see it does not catch the error.

try{
    (function(){
        setTimeout(function(){
            throw 'foo'
        }, 100);
    })()}catch(e){
    console.debug(e)}
