### ISSUE TITLE
Select Styling

### ISSUE THREAD

**Issue by brigand** [Semantic-Org/Semantic-UI#152]
Yes, select elements are difficult to style, but you can at least make them look somewhat like the text inputs.

this looks terrible: [fiddle](http://jsfiddle.net/GQCaG/) 

Bootstrap does a decent job, so we can get some pointers there.

**Comment by KarandikarMihir** [comment]
@jlukic Separate styling for `<select />` is much needed! It forces me to import entire semantic.min.css in my React project instead of importing only required style. I tried using dropdown.min.css, but it's not the same as pure `<select />`. 

I'd highly appreciate it if you make one. If it is not possible, can you at least post the relevant style for `<select />` here? Thanks in advance.

**Comment by philrykoff** [comment]
The select styles are included in the form module, so you only need that.

https://github.com/Semantic-Org/UI-Form/blob/master/form.css#L156

**Comment by KarandikarMihir** [comment]
@philrykoff Thanks! I made it work somehow. I don't want to complain, but it still does not feel like the one from semantic.min.css. Anyways, thanks again!
