### ISSUE TITLE
Tabular menu: content has longer width than the menu

### ISSUE THREAD

**Issue by mxth** [Semantic-Org/Semantic-UI#1554]
See: http://jsfiddle.net/6murnr7n/20/

**Comment by UiCandy** [comment]
Hi mxth,

This is caused by the `.ui.segment.attached { width: calc(100% + 2px) }` css property, the additional 2px causes it to bleed
.
I think it's too small a fix to fork the repo, so would just request the moderators to edit the line `semantic.css:12292` to `.ui.segment.attached { width: 100% }` 


.ui.segment.attached{

}

**Comment by jlukic** [comment]
Continued in #1557
