### ISSUE TITLE
What's SUI recommended architecture for custom style in myself folder?

### ISSUE THREAD

**Issue by hpyhacking** [Semantic-Org/Semantic-UI#1555]
I'm use Rails build some sites, but I'm use browserify and gulp build less and coffee for my site.

I have a doubt when read [running-installer](http://learnsemantic.com/guide/expert.html#running-installer), "SUI is recommended to build the site in its own directory it?" 

Now I'm link `./node_modules/semantic-ui/src/site/*` to my site folder `MY_SITE/app/assets/stylesheets/*` to custom style for my site, but it's so strange.

What's SUI recommended architecture for custom style in myself folder?

@jlukic

**Comment by anestv** [comment]
At `./node_modules/semantic-ui/src/site/*` there are your site's variables and overrides (part of the source code). 

The css and js files which you should link to `MY_SITE/app/assets/*` are in `./node_modules/semantic-ui/dist/`

**Comment by hpyhacking** [comment]
This's strange.

We usually add `node_modules` to `.gitignore` and this folder just store library. Why my site's variables and overrides in a library folder?

I hope import SUI less version just like `@import 'semantic-ui/semantic-ui` and insert my site's variables and overrides before this import line, or other one good idea? @anestv

**Comment by faller** [comment]
@hpyhacking 

I have faced the same problem with you. You may need some Asian typography optimization, forking SUI and install it by bower is a good way.

By the way, I enjoy using SUI with webpack, which is better than browserfiy

**Comment by anestv** [comment]
If you want to customise Semantic then you will need to modify some variables from your site (`src/site`) or theme (`src/themes/themeName`) (mostly `globals/site` variables) and then build (using gulp). If you have modified some variables, I think you would want to not gitignore the folder.

To include the compiled Semantic UI files (css and js) in an html page, you will have you use the files from `dist/`. 

If you try to include files from `src/site` in html nothing should happen because browsers shouldn't understand .less files.

If you want to include Semantic's source (.less) in some other less files you have, I don't know how you could do it

**Comment by jlukic** [comment]
See Build Tools Issued thread. I discuss the current issues there. I recommend using a dropped zip for now instead of managing inside package folder for bower or npm. **They will wipe on upgrade** because they've decided as an edict to treat their component folder similarly to a temp folder.

I'll have a better POV by imho until the installer detects and copies site files out of node_modules etc, it's too much trouble to use for anything but dist/ only release

**Comment by jlukic** [comment]
Apologies phone response, typos. Back in office Monday.

**Comment by jlukic** [comment]
Continued discussion in #1385, closing
