### ISSUE TITLE
Sidebar with fixed menu

### ISSUE THREAD

**Issue by idleberg** [Semantic-Org/Semantic-UI#1567]
When using a vertical sidebar on a page with fixed top menu, I have these two options:

1. Put the top menu inside the pusher (which I'd assume is the right way). Once the sidebar slides in, the content inside the pusher is scrollable including the fixed menu ([example](http://jsfiddle.net/idleberg/mg9akspo/))

2. Put the top menu outside the pusher and the it will remain fixed when scrolling. However, the menu will not get dimmed ([example](http://jsfiddle.net/idleberg/0s1Lguvu/))

I'd expect it to act as in the first case, without scrolling.

**Comment by jlukic** [comment]
Here's an example of expected syntax:
http://jsfiddle.net/sgn42ypt/

Any content inside of ``pusher`` cannot be fixed, This is caused by ``transform`` causing a new stacking context. I've mentioned this in previous threads. Basically chrome/firefox will attach ``position:fixed`` to any element with a 3d transformation. This is supposedly part of the spec for transforms, but IE11 decided not to implement it (kind of actually siding with IE on this one). So what you have is broken ``position: fixed`` inside of any transformed element.

The only real solution is to include fixed content outside. Sidebar will automatically animate any ``fixed`` content that is adjacent to a visible sidebar.
