### ISSUE TITLE
Missing v1.6.1 on npm

### ISSUE THREAD

**Issue by PeterDaveHello** [Semantic-Org/Semantic-UI#1573]
Just let you know maybe you forgot to push v1.6.1 on it :)

**Comment by jlukic** [comment]
Yeah. If i push code while im at home I haven't configured npm publish access there.

**Comment by jlukic** [comment]
Pushed

**Comment by anestv** [comment]
Hey Jack, I think version 1.6.1 at npm is different from GitHub. In particular, I did `npm install semantic-ui` and the file `node_modules/semantic-ui/src/themes/default/globals/site.variables` at lines 86-102 has:

    /*-------------------
            Sizes
    --------------------*/
    
    /*
      To have sizing resolve to a specified pixel values adjust
      the numerator to the desired font size and the
      denominator to the base em size
    */
    @miniSize        : (10 / 14);
    @tinySize        : (12 / 14);
    @smallSize       : (13 / 14);
    @mediumSize      : @emSize;
    @largeSize       : (16 / 14);
    @bigSize         : (18 / 14);
    @hugeSize        : (20 / 14);
    @massiveSize     : (24 / 14);
instead of [this](https://github.com/Semantic-Org/Semantic-UI/blob/1.6.1/src/themes/default/globals/site.variables#L86-L102)

This difference caused many problems when I tried to build, for example buttons whose size was not medium had `font-size: 0rem`

**Comment by jlukic** [comment]
Sorry NPM can be frustrating with its versioning. Instead of publishing the current matching tagged version it wants to publish ``head``. Its my mistake. 

I'll republish as new patch.

**Comment by jlukic** [comment]
Republished ``1.6.2``

**Comment by PeterDaveHello** [comment]
Thanks.
