### ISSUE TITLE
Elements Sizing

### ISSUE THREAD

**Issue by mikocot** [Semantic-Org/Semantic-UI#1575]
I was wondering for a while why my small buttons become larger than default ones, now I know (site.variables):

```
@smallSize       : 13px;
@mediumSize      : @emSize;
.....
@small           : unit((@smallSize / @mediumSize), rem);
```
with em set to 12px, we end up with small = 13/12rem, and therefore bigger than medium, which is not very intuitive
One could change all the sizes relatively, but maybe it would be nicer to just set proportions here, and calculate absolute sizes based on them and current @emSize.

Cheers!

**Comment by faller** [comment]
+1

**Comment by jlukic** [comment]
I understand why you would want to enjoy the simplicity of setting a single `emValue` that resizes all elements, but adding derived sizing values will still have restrictions.

Sizes need to resolve to exact pixel values to prevent subpixel alignment issues. Using decimal pixel values will sometimes cause box shadow strokes to disappear, for inline block content to not align correctly and other hard to debug issues.

That means If `@small` `@large` etc are calculated as a ratio of base EM value and then rounded to the nearest whole number they may sometimes have duplicate values caused by rounding. Meaning you may see `mini` and ``tiny`` are the same size.  

I would still recommend that most people set each size manually for their project. However I will add rounded derived values instead to make this process simplified for those who don't want to adjust each value.

```less

@emSize: 14px;

/* Ratios */
@miniSize = (10/14);
@tinySize = (12/14);
@smallSize = (13/14);

/* Derived Value */
@mini   : unit(( round(@miniSize * @emSize) / @mediumSize), rem);
@tiny    : unit(( round(@tinySize* @emSize) / @mediumSize), rem);
@small : unit(( round(@smallSize * @emSize) / @mediumSize), rem);
```

**Comment by jlukic** [comment]
Will resolve to exact pixel values in ``next`` release.

I encourage you to take a peek at the logic in the above commit.

**Comment by mikocot** [comment]
Yeap, the solution is more or less what I meant. Thanks.
