### ISSUE TITLE
Problems with !important styling

### ISSUE THREAD

**Issue by subhog** [Semantic-Org/Semantic-UI#1591]
I want to create a subtle variant of label, like the left one here:

![screen shot 2015-01-08 at 11 44 49](https://cloud.githubusercontent.com/assets/1041199/5661423/ce643134-972b-11e4-81aa-6c5dc93a54c3.png)

(the background here is `ui secondary segment`).

Since I wanted to use standard colors for text, my intention was to just use additional keyword to reverse color scheme, similar to how `inverted` works. The problem is in [these lines](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/label.less#L537-L539):

    .ui.green.labels .label,
    .ui.green.label {
      background-color: @green !important;
      border-color: @green !important;
      color: @invertedTextColor !important;
    }

What is the reason to use `!important` flag here? Why would you use it in a framework at all? It hinders all attempts of further customization.

**Comment by jlukic** [comment]
If you look at the issues history i've talked about ``!important`` several times elsewhere, and I probably said it better there, so I'll just leave the reasoning mostly as a precept. 

The answer is controlling specificity is...fairly complex. Since there are no manual means in CSS for specifying a 'calculated specificity' you have to rely on the barbarism of automatic calculation from the weighted values of your rules. This is not something you can always necessarily control by adjusting rules, especially when element  'coupled' definitions tend to have additional specificity just by the nature of the selectors being defined in the context of other elements. 

Variables and overrides are the project's solution. In most cases, you can just adjust the underlying variables if you need to adjust the text color. In this case, the variable should probably be `@greenTextColor`` which should be set in ``buton.variables`` as `@invertedTextColor` it appears to currently not be the case. I'll add the additional variables for you, since I'm already familiar with this use case with buttons and agree that more granular control is necessary.

If in the future you discover other variables that are barriers like this, there is still quite an easy solution. Use site or theme override files.

For example:
``site/elements/button.overrides``
 ```less
.ui.green.labels .label,
.ui.green.label {
  color: @textColor !important;
}
```

**Comment by lubber-de** [comment]
We managed to remove all of the `!important` settings for color of all elements since https://github.com/fomantic/Fomantic-UI 2.7.0 
https://fomantic-ui.com/introduction/new.html#colors
