### ISSUE TITLE
[Menu] Items should size themselves equally

### ISSUE THREAD

**Issue by pkorotkov** [Semantic-Org/Semantic-UI#1598]
Hi,
using the latest Semantic-UI release I noticed that when placing pretty large content in the left menu, the right menu items don't get vertically centered like their left counterparts. Put a snippet [here](http://jsfiddle.net/2ahw6t0L/6/).
It looks like a bug, doesn't it?

**Comment by gabormeszoly** [comment]
@pkorotkov hi, the fiddle link is wrong
-g

**Comment by pkorotkov** [comment]
@gabormeszoly, sorry for wrong link - updated.

**Comment by jlukic** [comment]
This is expected behavior. Menu items don't currently match heights. To accomplish this means swapping `item` over to `table-row` instead of `inline-block`, or using a not fully supported `flex-box` layout.

I'll look into this as an enhancement.

**Comment by pkorotkov** [comment]
@jlukic, thanks for explanations, I got the point. Yet, I believe it'd be great to explicitly tune such behavior by the native means of SUI.
-br

**Comment by serkandurusoy** [comment]
Hi there,

I've been banging my head all over untill I finally found this report.

![image](https://cloud.githubusercontent.com/assets/4649948/5823966/ad982c72-a0e9-11e4-88d8-e521786cd990.png)

I think vertical aligning should be consistent within a menu, unless otherwise required by the design. I see such patterns all over the web, a menu with a main left and a secondary right part, often for login information and they match in terms of vertical alignment.

I think this is more than mere enhancement.

In the meantime, how can we achieve this?

**Comment by jlukic** [comment]
Flexbox is coming in the next release with a solve for this issue

**Comment by jlukic** [comment]
Added in `next`
