### ISSUE TITLE
[Grid] Add SASS/LESS Mix-ins For Grid

### ISSUE THREAD

**Issue by badri** [Semantic-Org/Semantic-UI#1609]
Hi
Loving the framework so far!
I have just 1 gripe. Given we emphasize semantics so much, why does the grid system have presentational logic in HTML instead of CSS? It will give a more cleaner markup, among other advantages.
Ex: http://www.sitepoint.com/sass-bourbon-neat-lightweight-semantic-grids/
A semantic grid like Susy or Bourbon Neat would be awesome.
Is there any design consideration behind this? Do you accept patches for this feature?

**Comment by jlukic** [comment]
Thanks for your contribution but I don't plan on supporting mix-ins with SASS/LESS for grids. They are neat ways to create grids, but don't fit into the standards set by the rest of the library. 

UI elements like grid are designed to be descriptive, so that the page's markup makes the underlying design self-evident. So just looking at one template or html file will allow you to understand the layout without having to investigate its rendered design, or the underlying css implementation. This is somewhat verbose, but I believe necessary.
