### ISSUE TITLE
[Dropdown] Initializing dropdown removes exisiting callbacks on anchors.

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI#1618]
I am using semantic ui with the Meteor.js framework, which is using iron-router as single page routing mechanism. When adding menus into dropdown and calling `$('.ui.dropdown').dropdown();` the routing ceases to work, since the click event added by the iron-router is replaced by semantic ui. I have also created the minimally reproducible app and placed it to [Dropbox](https://dl.dropboxusercontent.com/u/3418607/Third.zip).

You need meteor installed to reproduce this.
The app works correctly, but when you uncomment following in the file header.js, switching back to home route will trigger the full page refresh instead of regular behaviour.

```javascript
Template.header.rendered = function() {
  //$('.ui.dropdown').dropdown({on: 'hover'});
};
```

**Comment by jlukic** [comment]
Would it be possible to create an example of this on [Meteorpad](http://meteorpad.com/)?

**Comment by jlukic** [comment]
Reinit calls `destroy`, but this [only removes namespaced events](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L100) which should not affect other event handlers.

**Comment by tomitrescak** [comment]
Here is the meteor pad with reproducible behaviour:

http://meteorpad.com/pad/iDRH7xfmhQdQD6ff6/Leaderboard

Also, I narrowed down the issue and it seems that iron router breaks if by coincidence the `$('.ui.dropdown').dropdown({on: 'hover'});` is called twice on the same element, as a result the routing stops working. It can be omitted by making sure that the code is called only once per dropdown.

Just comment out following code and routing will work again:

``` javascript
Template['practicals'].rendered = function() {
  $('.ui.dropdown').dropdown({on: 'hover'});
};
```

**Comment by jlukic** [comment]
Thanks I'll do my best to investigate

**Comment by splendido** [comment]
Hello @tomitrescak,

Lets have a look at [this meteorpad](http://meteorpad.com/pad/8jFKgZbiY4p6pvACt/Semantic-UI-issue-1618).

Your problem is solved by using:

```javascritp
Template.header.rendered = function() {
  this.$('.ui.dropdown').dropdown({on: 'hover'});
};
```

and getting rid of the other `Template.practicals.rendered` declaration.
I've also added a console log to check that the header is correctly rendered only once.


Please note that `this.$` should be used in place of `$` to limt the search of dom elements within the current template: this is essential to guarantee you're not going to re-initialize other elements matching the selector you might have in other already rendered templates.
...it also results in a faster search ;-)

Differently you could use `class` or `id` to make sure your selector matches only your current target SUI module.

Another important thing is to remember not to put SUI modules which need some initialization under conditional expressions or each statements:

```html
<template name="example">
  {{#if myCond}}
    <div class="ui dropdown"> ... </div>
  {{/if}}

  {{#each myItems}}
    <div class="ui dropdown"> ... </div>
  {{/each}}
</template>
```
```javascript
Template.example.rendered = function() {
  this.$('.ui.dropdown').dropdown({on: 'hover'});
  // other SUI modules initialization
};
```

**this is not likely to work** since the `rendered` callback will be called only once, while the condition and the list of items might change while the template is already rendered because of reactivity: this will results in dom elements being added to (or removed from) the rendered template after its `rendered` callback is executed and all SUI modules added later on will remain un-initialized.

The right structure is something like this:

```html
<template name="example">
  {{#if myCond}}
    {{> myDropdow}}
  {{/if}}

  {{#each myItems}}
    {{> myItem}}
  {{/each}}
</template>
```

with some:

```javascript
// No rendered callback needed for template 'example'

Template.myDropdown.rendered = function() {
  this.$('.ui.dropdown').dropdown({on: 'hover'});
  // other SUI modules initialization
};

Template.myItem.rendered = function() {
  this.$('.ui.dropdown').dropdown({on: 'hover'});
  // other SUI modules initialization
};
```

This is something we should put clear into the meteor/README.md file: **it's really the only thing needed to get SUI working with Meteor flawlessly!** :-)

As a general organization one could also think of keeping an initializer for each SUI element and use them like this:

```javascript
initAccordions(t) {
  t.$('.ui.accordion').accordion();
}
initDropdowns(t) {
  t.$('.ui.dropdown').dropdown({on: 'hover'});
}

Template.myDropdown.rendered = function() {
  initDropdowns(this);
}
```

but this might be more about a personal choice than a general rule.

**Comment by tomitrescak** [comment]
Splendido, thanks for the answer. Really helpful.

**Comment by jlukic** [comment]
This might have been related to #1750 closed in `next`

**Comment by steve-ross** [comment]
@splendido's comment should be in the README.md pain to go digging for this stuff, or why not add some helpers to the package itself?

**Comment by splendido** [comment]
Hi @steve-ross!
what about creating a PR for the README in [Semantic-UI-Meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor)?
Perhaps a *best practeces* section?

**Comment by zayaisshawn** [comment]
@splendido Your answer solved my problems. Thank you +1:

**Comment by steve-ross** [comment]
@splendido Sorry, had notifications off, there ya go :smile:

**Comment by frankapimenta** [comment]
If you want to create a new object where you set a field via a dropdown in the template that is a solution!

In case you want then to edit that object field and on rendering the edit template for that object the dropdown should select the correct option for the object field then I would use a Meteor.setTimeout which is not the best or pass the option as an attribute to the {{> dropdown}} which is I think the better option.

Does anyone have a better idea? it could actually help me out..

My timeout works fine but you know how is it with timeouts...
Passing the attribute to the dropdown is something I'll still have to try!
