### ISSUE TITLE
Extending transitions

### ISSUE THREAD

**Issue by ph7vc** [Semantic-Org/Semantic-UI#1621]
I like having transitions shipped with the framework, however it feels somewhat limited.

Is there a reason that there isn't support for something like "slide in left"? There only appears to be up and down at the moment.

I was trying to look at how I could extend it; and it looks like the CSS for the transitions are in the `src/themes/default/modules/transition.overrides` file.

I guess my question is; how does `transition.js` know what transitions are valid? Is it as simple as adding the appropriate CSS classes?
 
Thanks!

**Comment by jlukic** [comment]
Its really simple to extend. 

Transition creates a fake element tests if an animation exists (after adding the appropriate class names), then caches the results for future animations. It also uses this fake element to determine whether the animation is static, or has both an `in` and `out` animation. 

You can extend transition relatively easily. I would be willing to include pull requests that add new animations.  Any animation that transitions in and out just needs one rule for each. 

So `slide left` would need `slide left in` and `slide left out`.

For static animations like bounce etc. You can just have ``bounce`` as class name.

Since the definitions are arbitrary they all get put into the default themes override file.
