### ISSUE TITLE
Error rendering a button "fluid AND circular"

### ISSUE THREAD

**Issue by antonellopasella** [Semantic-Org/Semantic-UI#1686]
<div class="circular ui teal fluid icon button">
            <i class="icon settings"></i>
</div>

See the "teal" button 

![image](https://cloud.githubusercontent.com/assets/96335/5855053/4131f2e2-a234-11e4-82c1-341db239eff5.png)

**Comment by jlukic** [comment]
Are you saying the unexpected behavior is the oblong shape?

**Comment by antonellopasella** [comment]
Yes

Il giovedì 22 gennaio 2015, Jack Lukic <notifications@github.com> ha
scritto:

> Are you saying the unexpected behavior is the oblong shape?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Semantic-Org/Semantic-UI/issues/1686#issuecomment-71045159>
> .
>


-- 
Antonello Pasella http://www.pasella.it

**Comment by jlukic** [comment]
I can see why that is misleading. I don't know of any way in pure css to make sure the aspect ratio of width to height remains `1:1` when the width is fluid, or arbitrary relative to the container's dimensions.

**Comment by beetaa** [comment]
noop, @jlukic , how about using the smallest(height, width) to make element circle, instead simply using its width when the element is fluid?

**Comment by jlukic** [comment]
There isn't anything in pure css that can do a smallest() calculation

**Comment by beetaa** [comment]
thanks @jlukic , so there's two suggestions:

1. how about using the width instead of the height to make element circle when it is in the fluid container?  the most case is, when something (normally containers) turn into fluid, it's width changed, but the height of the **grid row**, **segment**, **paragraph** will keep their size (commonly **line-height**).

2. using **js** in nessesary, just like other modules.
