### ISSUE TITLE
New Feature : Sortable List

### ISSUE THREAD

**Issue by cazzoo** [Semantic-Org/Semantic-UI#1694]
Hi there,

I fount yet no built-in sortable list in Semantic-UI.
I looked a bit into this feature and achieve it well with Jquery-UI. I did not achieve it with jquery-sortable plugin or others HTML5 native fonctionnalities.

Here is a mockup I made using SUI and Jquery (+UI) : http://jsfiddle.net/cazsan/2158tg4b/

Do you think this feature could be added to our lovely Framework?

Best regards

**Comment by jlukic** [comment]
I think that jQuery UI and [Sortable](https://github.com/RubaXa/Sortable/blob/master/Sortable.js) have a good handle on this for now. 

I dont believe its worth throwing our hat into the ring unless there was something specifically it was missing, because as you've shown its all quite compatible with Semantic UI components.
