### ISSUE TITLE
Doubling Grid on Mobile

### ISSUE THREAD

**Issue by LauraSempere** [Semantic-Org/Semantic-UI#1716]
In the Documentation of the Doubling grid says: "A Doubling grid automatically doubles its column width on each device jump. For example, four column computer grid, will jump to a two column grid on tablet, and one column on mobile."
This works on tablet with any number of columns doubling grid, but on mobile it never jumps to a one column. We've been working with Semantic for almost one year, and in the previous version (before releasing the beta version) the doubling grid turned into one column on mobile size. 

I found that Verbat also commented this issue on Oct 2014 #1173. He was using Semantic Beta Version.
We are currently using Semantic 1.7.3 and it is still not working. 

Thanks,

**Comment by jlukic** [comment]
`doubling grid` at mobile moves to `two columns` for 2-6 columns. This was intentional. There are many cases where you want to reduce column but still not vertically stack. Docs are a bit fuzzy on this front so i'll update with a table.

In general, if you want one column on mobile, you can always override with `stackable` variation. 

So a `ui four column doubling stackable grid` will product 4 --> 2 --> 1.

There was a related bug, not mentioned, with `doubling grid` appearing incorrectly in some cases due to unnecessary width declaration (see commit). That is resolved.

**Comment by jlukic** [comment]
Added to docs
