### ISSUE TITLE
Events Calendar - Module or View (Not a Date Picker)

### ISSUE THREAD

**Issue by dcinzona** [Semantic-Org/Semantic-UI#1751]
I'm not asking for a date picker here, but something along the lines of http://eit.europa.eu/interact/events 
The calendar implementation they are using is responsive and seems like one of the more solid, mobile friendly calendar implementations I've seen.

Also used here: https://nflpa.com/player-planner-calendar (this example has a calendar "picker" on the side that converts to the full width calendar on mobile, but also has an indicator for each day that has an event).

Granted, something like this is a huge undertaking - but it would be really nice to see.

![screen shot 2015-02-04 at 7 58 51 am](https://cloud.githubusercontent.com/assets/52411/6040784/ca8e31cc-ac43-11e4-8354-ffb21b056e67.png)
![screen shot 2015-02-04 at 7 59 14 am](https://cloud.githubusercontent.com/assets/52411/6040789/cd70562c-ac43-11e4-97d1-e3dc981418a6.png)

**Comment by jlukic** [comment]
Thanks for taking the time to post.

I think this may fall in the category of a 'layout' rather than a common design trope that requires custom markup, like a comment feed, activity feed, etc.

I think the calender should be a component, but not necessarily the particular combination of buttons, calendar and listings as this can be quite arbitrary.
