### ISSUE TITLE
Extremely lagging /dist/semantic.css

### ISSUE THREAD

**Issue by TomZilla1** [Semantic-Org/Semantic-UI#1768]
I tried to use Dreamweaver CC with Semantic UI 1.8.1, I tried to link the /dist/semantic.css, it takes 10 seconds to load, and everytime I switch view from CSS to HTML file, it lags another 10 - 15 seconds.  I think it has to do with the @import thing at the top. How do I resolve this issue?

**Comment by jlukic** [comment]
If you are in china or somewhere where google is blocked see https://github.com/Semantic-Org/Semantic-UI/issues/1305#issuecomment-73416768

**Comment by TomZilla1** [comment]
I'm not in China. Can you provide further insight?

**Comment by Anachron** [comment]
This is offtopic, but anyway:
Using dreamweaver is really dangerous! You may speed up development first, but you will have to completely recreate the project once you figure out how limited and destructive DreamWeaver is. I don't mean to insult the program, just warning you because in my old company we had to rewrite a 200.000 LOC app for that reason.

**Comment by jlukic** [comment]
the @import rule is to load fonts from Google Fonts. For countries that have [restrictive firewalls](http://en.wikipedia.org/wiki/Golden_Shield_Project#Blocking_methods) like China, access to Google domains can cause timeout errors which can lock up the browser.

**Comment by ph7vc** [comment]
You could download the font and have semantic point to your local copy instead

**Comment by TomZilla1** [comment]
Thanks for the replies guys. I'll try to download Lato and manually point to it.
