### ISSUE TITLE
Default semantic-ui build exceeds IE9's 4096 selector rule

### ISSUE THREAD

**Issue by ericz** [Semantic-Org/Semantic-UI#1782]
IE9 (and below) ignores CSS rules beyond the first 4095 in any given file. The build semantic.css / semantic.min.css files surpass this, causing many CSS rules to be ignored resulting in all sorts of IE9 rendering issues.

For example, ui menu's are not visible in IE9 due to the required CSS rules not making the cutoff. This can be see in the menu documentation on semanti-ui.com

Note that a real version of IE9 is required to see this. IETester / IE9 browser mode will not emulate this issue.

See http://blesscss.com/ for more details.

**Comment by ph7vc** [comment]
Is this on a per file basis? or does this happen across multiple files at once?

Also, I'm sure in a production environment, one would use the build tools to include only the necessary components which would shrink the file size significantly. 

Never knew about this bug

**Comment by ericz** [comment]
It's per file. The Blesscss solution is to parse the file at build time and split into multiple files with `@import`s added, which is an effective workaround.

Using the build tools to only include the necessary components definitely will help though for suckers like me who prefer to just use it out of Bower etc. 

There are some Browserstack screenshots showing the drastic drop in fidelity in IE9: http://www.browserstack.com/screenshots/dca4c5219eb7b497e15dd864c16ac8b89972973c

Some of the IE9 rendering issues are due to lack of MutationObserver support which is used for several modules of semantic.js

**Comment by ph7vc** [comment]
I don't know this is something that can be solved by the framework itself. Keeping the framework in it's current state but shrinking the number of rules would be incredibly difficult.

I could see adding the BlessCSS solution as a part of the build tools for those who MUST support IE 9.

Or perhaps there could be a way to prioritize CSS rules so that it degrades well to IE9. So edge case things are put nearer to the bottom, or obscure rules that are rarely used. Still, I imagine that being rather tedious.

If the MutationObserver is causing an issue for IE9; that sounds like a separate bug rather than this "IE hard limit" obstacle.

**Comment by jlukic** [comment]
I'm removing IE9 as @ericz suggests. I think it's time.
