### ISSUE TITLE
Gulp build return error when choose RTL

### ISSUE THREAD

**Issue by mohamedsabil83** [Semantic-Org/Semantic-UI#1842]
Hi there, I wanna build RTL website using the new version of **semantic-ui**.

After completing **npm install semantic-ui** processing, and going to make **gulp build** order, I have the following message:

> Task 'build rtl' is not in your gulpfile
> Please check the documentation for proper gulpfile formatting

What I have to do ??

**Comment by jlukic** [comment]
Hi, it looks like a small typo in the task was causing it not to find the task. The task name is `build-rtl` not `build rtl`

You can run the RTL build task manually for now until patch comes out
```
gulp build-rtl
```

It will also be fixed in `1.9.3` to work with `gulp build` when `rtl: true`. Will be releasing shortly

**Comment by mohamedsabil83** [comment]
Thanx for quick reply. It's work.
