### ISSUE TITLE
[Search] the setting of searchFields does not work

### ISSUE THREAD

**Issue by gispace-** [Semantic-Org/Semantic-UI#1847]
When source data (local or remote) with custom attributes(not 'title' or 'description'), Search can't work, even set 'searchFields' correctly. For example:
source data:
{"c":0,"results":[{"name":"New Stuyahok"},{"name":"New Brockton"},{"name":"New Castle"}]}
code:
$('#some-search').search({
    apiSettings: {
        url: '/url_to_service?q={query}'
    },
    searchFields: ['name']
});

**Comment by jlukic** [comment]
Search fields only affects local search, remote search expects the returned object to be the search results.

**Comment by gispace-** [comment]
I test with v1.9.1. The searchFields doesn't work on local search neither. I think it's better if we can set searchFields for both local and remote data source.

**Comment by jlukic** [comment]
Search fields does work with local search.

Here's an example:
http://jsfiddle.net/6gz2sqbd/

**Comment by TimeBandit** [comment]
I hit this same roadblock and google brought me here. This is the nature of the problem as I see it.

When it comes to using search on a local object the code restricts the user to providing it with an array of object with only two keys; `title` & `description`. Anything else won't work.

I don't think this is user friendly nor intuitive as the option `searchFields` implies to me at least that you can specify which `keys` in the object have searchable `values`.

For example my data looks something like this straight out of a db query on mongo.

```
[
{CharityName: 'somename', CharityNumber: 1},
{CharityName: 'somename2', CharityNumber: 2},
{CharityName: 'somename3', CharityNumber: 3}
...
..
.
]
```
and naturally; for the sake of consistency I want to tell Search that my fields to search i.e `searchFields` are `CharityName` & `CharityNumber`, but I cant. I am forced to parse and output an object that only has `title` and `description` as keys. 

If would be great if I could specify `searchFields` that matched the keys in my data and also to specify more than just two keys because my objects contain at least 10 fields. I believe lines 1147 to 1151 in the search module might be the linked to this restriction if it was not intended.

**Comment by willstott101** [comment]
As an update to this issue this seems to be working and/or added now. A slight remnant of the old hard-coded values remained but I think I've squashed it with https://github.com/Semantic-Org/Semantic-UI/pull/6023
