### ISSUE TITLE
[Modal] Opening modal hides scollbars, causing the page content to move

### ISSUE THREAD

**Issue by ThiefMaster** [Semantic-Org/Semantic-UI#2061]
While I see the point of hiding the scrollbars, the fact that the page content jumps a bit to the right is quite ugly and irritating. Is there any way to avoid this?

**Comment by Einkoro** [comment]
Its the dimmer that causes this behaviour: 
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dimmer.less#L109

I used the following recently to prevent the scrollbar disappearing:

```
// Show the scrollbar to avoid the width jumping when toggling modals
body.animating.in.dimmable, body.dimmed.dimmable {
    overflow: inherit;
}
```

If it is possible I think disabling the scrollbar rather than hiding it would make more sense but the closest you can probably get to that is faking it with ``position: fixed; overflow-y:scroll;`` – probably better to just leave the scrollbar visible and enabled.

@jlukic: Any thoughts on changing this for 2.0?

**Comment by jlukic** [comment]
We can just trigger this for `scrolling modal` and not normal modals and be alright. I agree its much better.

**Comment by jlukic** [comment]
Fixed in `2.0`

**Comment by jlukic** [comment]
I had to revert this, wasn't thinking about consequences. 

Bootstrap actually appends divs on modal init to [determine scrollbar width](https://github.com/twbs/bootstrap/blob/master/js/modal.js#L257) its pretty ugly. 

There's no reasonable way to handle this without leaving the page scrollable while a modal is open, which is no good, or offsetting content by the width of a scrollbar in your browser, which requires the aforementioned fix. I'm going to have to circle around on this again.

**Comment by jlukic** [comment]
I'm removing this is a bug until a more adequate solution is available. From playing with this for a while it seems to be a big performance hit to recalculate.

**Comment by lubber-de** [comment]
We fixed this in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/468
See https://jsfiddle.net/smudoy1k/5/
