### ISSUE TITLE
More colors for SUI?

### ISSUE THREAD

**Issue by abdelouahabb** [Semantic-Org/Semantic-UI#2124]
Hi,
I wish there was more colors (for example dark blue (nigthy)) ?

**Comment by jlukic** [comment]
I've limited the vocabulary for colors since they can get out of hand quite quickly. I don't expect the colors to necessarily match up to a site 1 to 1 since this would be an impossible task.

I think the best way to customize is not to use colored variations, but to adjust the colors inside your theme variables.

**Comment by abdelouahabb** [comment]
ah, got it, thank you :)
