### ISSUE TITLE
[Modal] Detecting which button was clicked in modal

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#2191]
Hi,

Suppose I have a modal dialog with a form in it. The dialog has ```Cancel```, ```Delete``` and ```Save``` buttons. How can I detect which button was clicked using modal's built in events such as ```onApprove```? 

Here's the [fiddle](http://jsfiddle.net/andreyvk/xwe9h4sq/)

The feature would be useful when implementing option dialogs, for instance. I understand that I can manually bind to buttons with, say, jQuery ```on("click", ...)```, but that's not the ideal scenario. In some cases you might need to prevent dialog from closing (e.g. invalid form data), but that would not be possible if button event binding is done on the side.

**Comment by jlukic** [comment]
The `onApprove` and `onDeny` callbacks will not close the modal if the callback has `return false;`. This apparently is absent from documentation. I've added that.

Since people are expecting callback context to have modal as `this` I've added an additional parameter  to the callback which passes the activating element.

i.e.
```javascript
onApprove: function($element) {
  if($element.hasClass('ohnoes') {
     // dont close modal
    return false;
  }
}
```

**Comment by andreyvk** [comment]
Thanks @jlukic. That solves the problem
