### ISSUE TITLE
Start asking for monetary support

### ISSUE THREAD

**Issue by gottlike** [Semantic-Org/Semantic-UI#2201]
This is kind of "off topic", but after reading your comments in [this issue](https://github.com/Semantic-Org/Semantic-UI/issues/847), I feel it's important to tell you this. I would strongly consider doing these things in your place:
- stop coding right now and take a deep breath
- put the donate button right next to the download button
- add a donation banner explaining your/the projects situation and asking for support, similar to what Wikipedia does ([link](http://cdn.thewire.com/img/upload/2012/11/27/rendered/a8a702c2e0aed35de369c9360b92392f_623x246.jpg))
- make a list of features that people requested, or that you think would be nice and put a "donation pricetag" on each, so people can donate to increase priority for their favorite feature
- take a few days off coding and think about 1-2 other monetization opportunities

The above actions are not "evil" and at least 80% of the people will totally understand and support you! If you are "burned out", the project will probably not become successful anyway.. and nobody wants that.

I for one, am going to donate right now.

**Comment by mikeatm** [comment]
I second this,  the project is very valuable to a large  community (going by the  amount of forks and stars), let them know  its ok to support.

**Comment by jlukic** [comment]
Hey thanks gotlike for the thoughtful post, and also for the generous donation. :bow: 

I want to elaborate on some of the points you brought up and give some personal context about the state of the project.

How I work on Semantic UI
* I currently work full time Monday-Friday on Semantic UI from the [TNR](http:/www.newrepublic.com) offices around Union Square in NY. Although I haven't worked for them since last July they've been extremely gracious and have let me keep a desk here. 
* I worked from July-October to get `1.0` out, and have been working on `1-x`-`2.0` from October till now 
* I haven't taken on any supplemental work or contract work since then. My only income has been from donations.
* I also run another free site [myfav.es](http:/www.myfav.es) with 90k users that costs me about $100/month to keep up.

Money & Financial Status
* I've spent about 25-30k of my savings in the last 10 months to keep this up.
* My total living expenses in New York with rent, bills, etc, end up being around 3.5k per month after taxes. I could probably cut this down, to 2.5-3kish if I reduced my expenses, didnt go out etc.
* I receive on average in 2015, $500/month from the banner on semantic-ui, and $400 from donations. 
* This nets me at about a loss of around -($2-3k a month)

Ways I'm Thinking about Making Money

VC
* I've talked with a couple venture capitalists about turning Semantic UI into a company, similar to what Meteor did (raised $11million) or Ionic ($5 million).  It's a bit surreal I've almost kept pace with funded open source projects on GitHub despite their massive war chests
* Getting funding from VC is difficult because I don't have a team in the wings, or a cofounder, which is pretty much a pre-requisite for funding. Most of my good programming friends are gainfully employed. Additionally, seeking funding is a full time job with the amount of meetings and presentations, and could end up being a bust.
* If your curious you can see my investor presentation here  http://investor.semantic-ui.com/

Donation Visibility
* I'm planning with `2.0` to change the download page to a "Getting Started" page and make a personal plea, similar to what you recommended from Wikipedia, with each download. [Ubuntu](http://www.ubuntu.com/download/desktop/contribute/?version=14.04.2&architecture=amd64) also does this really well. 
* I'm hoping to create a better "about the project page", and add visibility to donation goals and current donators. I've been really awful about highlighting the generosity of our community so far.

Kickstarter / Crowdfunding
* I've been considering doing a Kickstarter specifically with the goals of creating a standalone theming site, (online themer, download & track packages, similar to npm.org), as well as a similar site for downloading prebuilt layouts. The scope of these projects are too large for me to consider tackling discretely without having some amount of financial runway.
* Creating an effective kickstarter video & monitoring the campaign is also a time investment which I need to scope out, which has been difficult with finishing 2.0


So where does this all net out for me.
* I'm going to see how effectively a 2.0 launch with increased donation visibility and new traffic helps make the project more sustainable
* Although sometimes I might come off as a bit *burnt out*, I am actually in great spirits. There is some GitHub issue fatigue which comes from having participated in 1700 threads, and knowing I dont have time to add everyone's feature, or give people advice on how to use SUI. 
* I have no plans of dropping Semantic UI development. To me, the principles behind the library have not been fully articulated, and I will try to pursue them as far as they lead.

**Comment by ikourfaln** [comment]
Just Keep up my Friend, I worked with Bootstrap, Foundation, UIKit, ... and more, I swear that Semantic UI is the best Frent-End Framework, so plz keep up, I see I big future here.
Im not a rich man, But Im supporting you by Sharring your Project everywhere, and visiting the website more than 10 times / day.
Thanx for All your hard work

**Comment by jlukic** [comment]
Thanks. I just want to make clear, I wouldn't want anyone to donate unless it makes sense for their financial situation.

**Comment by ShawnOceanHu** [comment]
Faith & Love, my friend.

**Comment by KapuzenSohn** [comment]
In the Company I work we use Bootstrap and for a selfmade House Automation I wanted to try something new and I started to use Semantic UI.
I must say that Semantic UI looks very nice and I love to use it.

Thanks for making such a beatiful UI.

**Comment by gottlike** [comment]
Okay, this sounds sensible. Glad you have a plan and working on it. Let's see how it turns out.. With this much momentum you should be able to get something going :)

**Comment by kappaknight** [comment]
Here are just a couple of thoughts - from a bootstrap entrepreneur...

1. Instead of gunning for VC's, (which you should still do), and asking purely for donations, why not see if companies or individuals would be willing to pay for setup? I may be the odd man out here in that I'm not a super technical developer, but I would like to mess with SUI to see what it can do. While I'm able to mess around with CSS/HTML and some JS, making server changes on a production machine is a bit scary for me. With that said, taking on a few of these gigs may also help you gain some insight into making the onboarding process easier.

2. For KickStarter video, have you thought about hiring a firm? http://friendlyhuman.com/ is based out of Atlanta's incubator space. I believe they have made videos specifically for the purpose of KickStarter before.

3. In addition to coders, have you thought about bringing someone into the team for marketing, PR, etc.? In terms of the overall picture, it seems like you want to be the CTO, and that leaves the CEO, CFO, and CMO positions open - and having people help take care of the other aspects of growing this brand will allow you to rest easier, and focus more on your core contribution to it.

**Comment by kappaknight** [comment]
4. If there's a job board or something, where people who are looking to test this out can be matched with people who are already familiar with this project (and vetted), that is another value added service that companies can pay for. (i.e. you can get a referral fee for matching those two groups up)

**Comment by martindale** [comment]
I'm a deep believer in this project, and I'd love a way to donate that doesn't give a percentage to PayPal or some other company.  Can I also ask that you publish a Bitcoin address?

**Comment by jlukic** [comment]
@martindale I'm still a bitcoin scrub. Can you explain to me what I need to do to set this up.

**Comment by kappaknight** [comment]
Is bitcoin still a thing? Assuming you guys are in the U.S., you can also transfer money via Square.com/cash for zero fees, or do it the traditional way and send a check.

**Comment by jlukic** [comment]
FWIW Here's the square link that will not take paypal fees
https://cash.me/$semanticui

**Comment by martindale** [comment]
@jlukic it's very easy – get [a Coinbase account](https://www.coinbase.com) (or use [my referral link](https://www.coinbase.com/join/martindale) if that's your fancy) and publish a Bitcoin address.  It's just like an email address, except it's where people can send you money.

I really don't like sending people to Coinbase, but that's the lowest-hassle mechanism available today.  If you're really interested in the fundamental ideology Bitcoin supports (and that includes not paying Coinbase a fee when you sell the Bitcoin), you could just [install Copay](https://copay.io/) and publish an address from there.

I'm happy to help at any point in the process.  I've accepted my pay exclusively in Bitcoin for some time now, and prefer to not touch fiat wherever possible – and would love to see one of my favorite projects benefit from the same underlying technologies.

**Comment by willchen90** [comment]
@jlukic Hey Jack, just wanted to see if you've made any decisions around the various options for financing your work for Semantic UI. I've used it for a couple of small projects and found it easy to use and really intuitive. I've shared your framework with several of my coworkers, and in particular the video of your talk at Meteor Devshop (the part about the GitHub replica was amazing!). I'm excited about the future of Semantic UI but do worry about you burning out after working so hard on the framework by yourself, essentially on a volunteer basis. Hope you're doing well!

**Comment by jlukic** [comment]
Thanks @willchen90 I appreciate your encouragement.

**Comment by Banandrew** [comment]
@jlukic you mentioned Kickstarter before, Evan You, the creator of Vue.js, was successful with [his Patreon campaign](https://www.patreon.com/evanyou)—I understand the projects are different, but maybe it can be another option for you to consider.

**Comment by kevinresol** [comment]
@jlukic yeah please consider setting up Patreon, it is just a few steps, much easier than kickstarter.

**Comment by brodybits** [comment]
@jlukic I would personally favor a Kickstarter campaign, with a minimum amount of at least $500 and goal of at least $100K to sponsor at least 1-2 years of your time for this. Reward could be a limited-time support retainer.

P.S. I wish @jlukic and other owners would add more maintainers badly needed to solve bugs, review patches, and look for even more trusted maintainers.
