### ISSUE TITLE
[Dropdown] Add API Integration for Large Lists

### ISSUE THREAD

**Issue by devmondo** [Semantic-Org/Semantic-UI#2205]
hi, 
amazing work, the most slick and clean UI i have seen.

i am using kendo now, and their dropdown, multi select, grid has something called virtualization, which basically load on demand extra server results, can we do this here ?

i saw the best and there is tags kind of ability, but it only allows you to add tags from predefined data, can we add custom user input so it acts as a true tag editor with server search ability.

thanks in advanced.

**Comment by jlukic** [comment]
I think kendo's grid component is very interesting. I would like to have something like a data grid for SUI, but haven't had the time to work on it.

The particular use-case of multi select using remote data makes sense to me, but popup, sidebar etc, I think should stay pure.

**Comment by ikourfaln** [comment]
Interesting feature :+1:

**Comment by devmondo** [comment]
:+1:

**Comment by jlukic** [comment]
I've done a first pass at this feature today, but it still needs some work. I'm planning on supporting remote sources only for `search selection` where there may be many more possible choices than selected choices.

One of the main issues with pulling in dropdown content remotely, is that it is impossible to preserve matching names for `values` on page refresh, in order to recreate multiselect labels, without including a second hidden input field that is used to match title to label. 

So I'm faced with either introducing a second `input` field only for this use case, or using values and not names for label text on page refresh.

I've also added a local caching option for `api` to avoid server-side roundtrips on repeated requests for the same url. It is disabled by default, but used with dropdown.

http://beta.semantic-ui.com/modules/dropdown.html#/examples

**Comment by ikourfaln** [comment]
Thank you @jlukic  :+1:  really useful
it will be cool if you add "loading" class after typing

**Comment by ikourfaln** [comment]
There is a problem when you View the Source !!

**Comment by devmondo** [comment]
:+1:

**Comment by jlukic** [comment]
The API that is being used in the docs examples for search and dropdown is having reliability issues with the express/nodejs server sometimes dropping database connections and giving a "bad gateway" error. This may make the example return results inconsistently.

I've added a new feature to store name/value pairs in `sessionStorage` in order to recreate them on page refresh. This allows the hidden input to only store the selected value, yet still magically retain the original name. This can be disabled with a setting `saveRemoteData: false`.

**Comment by ikourfaln** [comment]
Thanx for your hard work :+1:

**Comment by jlukic** [comment]
This is in `2.0`
