### ISSUE TITLE
search inside nested menu

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2233]
Hello, Jack!
is it possible to find "auto" or "1000" in my fiddle through the search box?
http://jsfiddle.net/efp8z6Ln/144/

**Comment by jlukic** [comment]
Search does not work for nested dropdown menus. This is intentional and is a UX decision.

**Comment by avalanche1** [comment]
Can you recommend a simple solution for it?
I tried to grok through your code, but my skills were too low...

**Comment by 3amprogrammer** [comment]
@jlukic can you justify this decision?

**Comment by AdventureBear** [comment]
I'm looking for a solution to using the Search box in react (or a basic input) in a Menu -> Menu.Item component but every implementation I try, I cannot pass any props (functions, state or otherwise) to the Search component.    How to solve this problem?   Many of the Menu examples show a search bar within the top menu and I've been unable to sort out the implementation.  Happy to share code if anyone is still paying attention to this issue.
