### ISSUE TITLE
[Icon] - Bug with icon size variations in next

### ISSUE THREAD

**Issue by lemartialou** [Semantic-Org/Semantic-UI#2309]
This is happening in Firefox, Chrome and IE (win7)

**Screenshot 1: from the beta docs**
![Imgur](http://i.imgur.com/gYDataH.png)

**Screenshot 2: when you click on "view source"**
![Imgur](http://i.imgur.com/Ay06SDK.png)

**Screenshot 3: when you click on "view source" again (the grey line is a chrome only bug)**
![Imgur](http://i.imgur.com/3wSZTrm.png)

**And the fiddle:** 
http://jsfiddle.net/lemartialou/ua0hayka/1/

**Comment by jlukic** [comment]
This is an issue how docs generated code, it tries to guess which parts of the content are part of the code example and which are supporting text. When there are spacers like <br> it appears to be removing them for the code sample.

The icon issue was a separate bug caused by missing line height on `massive`

**Comment by jlukic** [comment]
Fixed this last week
