### ISSUE TITLE
pls don't remove "dist/semantic.css" from "main" of bower.json

### ISSUE THREAD

**Issue by Cook1fan** [Semantic-Org/Semantic-UI#2327]
I use grunt-wiredep to inject css and js into html file.
it according to "main" of bower.json, scan .css and .js file.
![qq 20150530202330](https://cloud.githubusercontent.com/assets/2127458/7897336/d4fb6cac-070a-11e5-88c9-31387a92eb61.png)

**Comment by geemang2000** [comment]
:+1:

**Comment by kelostrada** [comment]
:+1:

**Comment by cvrebert** [comment]
`main` including Less instead of precompiled CSS is mandated by Bower's spec; see https://github.com/bower/bower.json-spec/pull/43 and #2244.
**wiredep** needs to update its docs/behavior to account for this; see https://github.com/taptapship/wiredep/issues/180.
Bower does probably need to add more fields to their spec to better accommodate precompiled CSS; I encourage you to "+1" on https://github.com/bower/bower.json-spec/issues/21.
At any rate, none of this is really Semantic UI's fault, it's merely following Bower's specification here.

**Comment by kowsheek** [comment]
:+1: This is annoying AF
