### ISSUE TITLE
Problem using a "dropdown active item"

### ISSUE THREAD

**Issue by opvini** [Semantic-Org/Semantic-UI#2378]
I am trying use a dropdown item, and it works fine, but when i try use "dropdown active item" on my top menu, the dropdown doesn't works... Can I do it or it is a bug?

Thanks a lot.

**Comment by ikourfaln** [comment]
I dont think its a bug. plz make a test case by forking this http://jsfiddle.net/efp8z6Ln/ and share it here.

**Comment by opvini** [comment]
I tryed on JDFFIDDLE and it doesn't work, but I can't share the link, so I am posting the simple code here. If you remove the "active" from a "dropdown", it works.

The script used:
$('.ui.dropdown').dropdown();

The HTML used:

[code]
  
  <div class="ui borderless pointing menu">
  
    <a class="item" href="principal.php">
      <i class="home icon"></i> Início
    </a>
    
    <div class="ui link dropdown active item">
      <i class="icon file"></i>Formulários <i class="dropdown icon"></i>
      <div class="menu">
      
        <a class="item" href="form_big.php"><i class="icon file text"></i> BIG - Boletim de Intervenção  </a>
        <a class="item" href="form_big.php?bos=1"><i icon class="icon file text outline"></i> BOS - Boletim Simplifcado  </a>
        
                <a class="item" href="lista_guardas.php">
        	<i class="icon shirtsinbulk"></i> Cadastro de Guardas  
        </a>      
        
        <a class="item" href="lista_provavel_desc.php">
        	<i class="icon list"></i> Prováveis Descrições
        </a>
              
        <a class="item" href="lista_bos.php">
        	<i class="icon folder open outline"></i> Ver Todos os BO's 
        </a>

      </div>
    </div>
    
           <a class="item" href="lista_usuarios.php">
        <i class="icon users"></i> Usuários
      </a>
        
    <a class="item" href="meus_dados.php">
    	<i class="icon edit"></i> Meus dados
    </a>
     
    <div class="right menu">            
        
    <div class="ui autocomplete search item" id="topo_busca">
      <div class="ui icon input">
      <form id="form_busca" method="get" action="lista_bos.php">
        <input class="prompt" type="text" placeholder="Localizar..." data-autocomplete-fields="opt=search" data-autocomplete-url="ajax.php" name="q">
      </form>
        <i class="search icon" id="btn_search"></i>
      </div>
      <div class="results"></div>
    </div>
        
        <div class="ui dropdown item">
          <i class="icon setting"></i>
          <div class="menu">
            <a class="item" href="meus_dados.php"><i class="icon edit"></i>Meus Dados</a>
            <a class="item" href="principal.php"><i class="icon help circle"></i>Ajuda</a>
            <a class="item" href="logout.php"><i class="icon power"></i>Sair</a>
          </div>
     </div>
        
    </div>
  </div>  
  </div>

[/code]

**Comment by jlukic** [comment]
There's no such thing as a `ui dropdown active item`. You just want `active item` no `ui` or `dropdown`

**Comment by gonssal** [comment]
I think there has to be a `ui dropdown active item`, at least for menus.

The most obvious use case is, when you have a dropdown menu item, you want to mark it as `active` when any of the submenu items is active. You might also want to place a link in the menu item, leading to a different place than the submenu (dropdown) items go, so you want it to be `active` when you are on that place.

Digging a bit into the code, it seems that when you `click` on a dropdown menu item, it fires the `dropdown` module `event.icon.click` function, that triggers the `module.toggle()` function. The problem here is that the `toggle()` function checks for `!module.is.active()` to show the dropdown. This leads to it never showing the dropdown if you set the `active` class to the dropdown menu item.

The most obvious use case is, when you have a dropdown menu item, you want to mark it as `active` when any of the submenu items is active. You might also want to place a link in the menu item, leading to a different place than the submenu items go, so you want it to be `active` when you are on that place.

Digging a bit into the code, it seems that when you `click` on a dropdown menu item, it fires the `dropdown` module `event.icon.click` function, that triggers the `module.toggle()` function. The problem here is that the `toggle()` function checks for `!module.is.active()` to show the dropdown. The `show()` function, used by `toggle()`, does the same check. This leads to it never showing the dropdown if you set the `active` class to the dropdown menu item.

As stated, I think being able to set a dropdown menu item as `active` should be possible, as is any other menu item. @jlukic, If you agree with this, I will try to refactor the code to make it possible.

**Comment by jlukic** [comment]
I think a dropdown menu should not appear with `active item` styles on page load. The UX behind this is a bit funny.

However adding `active` styling with dropdown visibility, should also not making `active item` styles appear form `menu`, this is also weird.

I'm going to re-evaluate the use of `active` particularly due to the latter case.
