### ISSUE TITLE
<doctype> and icons in HTML5

### ISSUE THREAD

**Issue by moxet** [Semantic-Org/Semantic-UI#2380]
I am working on a template based on HTML5 and facing a terrible issue. When i use `<doctype html>` the document seems fine with all icons but my tables are NOT responsive. Alternatively when i change the `<doctype>` to 4.0 all icons are showing but the responsiveness of tables are no more.

What could be the possible solution to resolve both problems. :weary:

**Comment by kasparhuebener** [comment]
Did you try with
```
<!DOCTYPE html>
```
(especially with the !) ?

source:
http://stackoverflow.com/questions/7020961/uppercase-or-lowercase-doctype

**Comment by moxet** [comment]
@kasparhuebener its not working dear. Kindly check the issue in this picture.

![Image of Yaktocat](http://i.imgur.com/Wr9DDb6.png)

**Comment by jlukic** [comment]
I think the conversation around the bugs being related to `doctype` declarations is a red herring. Virtually all projects that use Semantic UI use a doctype like `<!DOCTYPE html>`

Can you provide a public accessible example showing the incorrect behavior youre experiencing?

**Comment by moxet** [comment]
May be i am doing it wrong or something is missing but here is the example you can check the source as well.

File1:
`<!DOCTYPE>` suggested by you. The icons are fine while the table is NOT responsive.
http://softemblems.com/otp/file1.php

File2:
`<!DOCTYPE html>` No icon for shop while the table is Responsive.
http://softemblems.com/otp/file2.php

Please check and respond. If i am doing it wrong suggest alternative. May be i should add `<tablet stackable>` as additional class?

**Comment by sstok** [comment]
`<!DOCTYPE>` is not valid and makes it fall back quirks mode.
https://validator.w3.org/check?uri=http%3A%2F%2Fsoftemblems.com%2Fotp%2Ffile1.php&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

Also, you didn't set the encoding https://validator.w3.org/check?uri=http%3A%2F%2Fsoftemblems.com%2Fotp%2Ffile2.php&charset=%28detect+automatically%29&doctype=Inline&group=0

The actual problem is that you used the wrong class name :) use `archive icon` instead of `Archive icon` (notice the Uppercased Archive. all class names are in lowercase.)

**Comment by moxet** [comment]
Thank you @sstok for your recommendations, changing uppercase to lower works for me. But why it was fine in `<!DOCTYPE>` i wonder.

Between thank you i will set the character encoding as well. :)

**Comment by jlukic** [comment]
Thanks sebastian for your help.
