### ISSUE TITLE
[Transition] Transition Restores Pre-Transition Style Attribute (Which May Have Changed)

### ISSUE THREAD

**Issue by stevekr** [Semantic-Org/Semantic-UI#2402]
If modal size changes before transition ends it resets to wrong position.

http://jsfiddle.net/0qyo8jqo/

I have empty .ui.loader div in modal while it loads remote content with unknown height so it usually makes modal change size before animation ends.

**Comment by hpohl** [comment]
You need to refresh it after changing content: http://jsfiddle.net/0qyo8jqo/1/

**Comment by jlukic** [comment]
Hey steve, technically observeChanges should cover you, but because the `style` attribute changed during transition `restore conditions` at the end of transition is restoring the `style` value *before* the transition started, which is incorrect.

Basically, as currently written transition will clear any style changes that happen *during* a transition, [restoring the value](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/transition.js#L398) to what it was before a transition was called.

**Comment by jlukic** [comment]
Landed in https://github.com/Semantic-Org/Semantic-UI/commit/17eac4772cb3674323858369dfb26ed4291282fb

**Comment by stevekr** [comment]
Thanks!

**Comment by jlukic** [comment]
Example
http://jsfiddle.net/b9kgweo7/
