### ISSUE TITLE
[dropdown] [next] inline style missing font-size

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#2419]
Hi, this simple example of an inline field with dropdown
http://jsfiddle.net/84s8p87x/6/
doesn't have the right font-size.

Setting the font size like
https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/collections/form.less#L920
fixes the issue.

**Comment by kapouer** [comment]
TBH it doesn't completely fixes the issue:
the height of the dropdown aligns with the height of the input, but the labels are not aligned any more.

**Comment by jlukic** [comment]
I was actually just toying with this yesterday. 

Form labels use a slightly smaller font size than inputs, which gets peculiar when you mix both inline and normal styles, since those smaller labels are aligned horizontally making their difference in size more obvious.

I have some other things on my plate for docs today, but I will try to circle around.

**Comment by jlukic** [comment]
Was pruning for leftover open issues. 

Looks like this is fine in `2.0`
http://jsfiddle.net/0skc2a6o/

**Comment by kapouer** [comment]
i did not change `@emSize`, `@fontSize` variables - so it's certainly a misuse.
