### ISSUE TITLE
Right visible sidebar not working (using Meteor/Blaze)

### ISSUE THREAD

**Issue by Joe312341** [Semantic-Org/Semantic-UI#2425]
Hello, 

My goal is to setup a sidebar that is visible and can be toggled. 

It works perfectly if I use the "left" class but if I use the "right" class the pusher will not show up.

Relevant code: (as state in the title I am using Meteor)
```
<template name="layout">  
{{> header}}
<div class="ui bottom attached segment pushable test">
    <div class="ui right vertical visible sidebar menu">
      <a class="item">
        <i class="home icon"></i>
        Item1
      </a>     
    </div>
    <div class="pusher">
       <div class="ui basic segment">
      		{{> yield}} 
      </div>     
    </div>
  </div>
</template>
```
Regards,
Joe

**Comment by kennypinyan** [comment]
I had a quick look at this at it turns out it's not anything to do with meteor. I created a quick [test case on codepen](http://codepen.io/kennypinyan/pen/doVZYG). 

For some reason (and I'm no Semantic UI expert so it may just be bad markup) changing the class to `right` pushes the content off the screen to the left. If you click the button on that pen you will see it move.

**Comment by jlukic** [comment]
A sidebar generally "pushes" content by its width to appear. To have it overlay content use `overlay` on the sidebar.
http://codepen.io/anon/pen/LVzOJx
