### ISSUE TITLE
Possible bug in dropdown with remote content

### ISSUE THREAD

**Issue by chrisandchris** [Semantic-Org/Semantic-UI#2488]
To follow this issue, the demo on http://semantic-ui.com/modules/dropdown.html#remote-content is enough.

If you try to enter "al" (let's say you search for albatross) and after that you select "albatross" from the dropdown-list, "albatross" is added to the input field but the search value "al" is not removed. I think this is not a desired behaviour.

![screen shot 2015-07-01 at 17 21 48](https://cloud.githubusercontent.com/assets/2905794/8458152/ae114e4e-2015-11e5-9978-68716c3b9930.png)

**Comment by tcigrand** [comment]
Looks like it's only happening when you click on the tag, pressing entering correctly removes the search value.

**Comment by jlukic** [comment]
This was an intentional UX decision. If you are clicking a menu item in a multiselect you might have interest in clicking more in that list. Clearing your search and hiding the menu could be frustrating if you say, "wanted to select 2 from that list". 

As a counterpoint hitting "enter" is a hard stop to a query, letting you say "I want to go on to the next query"
