### ISSUE TITLE
[Icon Message] Loading icon is off-center on mobile (2.0)

### ISSUE THREAD

**Issue by loris** [Semantic-Org/Semantic-UI#2499]
Loading icon (such as `notched circle loading icon`) inside Message component are off-centered.
To reproduce: Have a look at the Icon Message section in the [Message page](http://www.semantic-ui.com/collections/message.html) using a smartphone (reproduced on iOS 9 / Safari 9 and Android 5.1.1 / Chrome 43)

![untitled](https://cloud.githubusercontent.com/assets/8362/8478200/13e09f30-20d0-11e5-9d24-02755c821a57.gif)

**Comment by celsworth** [comment]
I had a little mess around with this and found it occurs on iPhone but not iPad.

It seems to be due to the `width: auto` on `.ui.icon.message>.icon:not(.close)`, which is overriding an earlier `width: 1.18em`.

With it on iPhone the spinner gets a width of 36px but a height of 42px.

Take it out and both width and height are 42px and the animation looks correct again.

**Comment by jlukic** [comment]
It's worth noting with "FontAwesome" the widest glyph is not `1em` but [`1.18em`[(https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L400).

**Comment by jlukic** [comment]
I can see this is an issue but im unsure the cause. Safari iOS only.

**Comment by ceremcem** [comment]
Any progress here?
