### ISSUE TITLE
[Popup] moves aways from position: fixed elements on scroll

### ISSUE THREAD

**Issue by hpohl** [Semantic-Org/Semantic-UI#2771]
http://jsfiddle.net/74h2m63n/1/

Scrolling causes the popup to stay at the same position relative to the document.

Setting `position: fixed` manually resolves the issue: http://jsfiddle.net/74h2m63n/2/

**Comment by jlukic** [comment]
The expected behavior is for the popup to remain attached to the element, in most cases that element is statically positioned and moves normally with page flow. 

I can understand when the trigger is `fixed` it doesnt behave as expectedly. I have to check into whether it makes sense for `popup` to detect display of element and assign itself the same display. There are many.. edge cases with popups that have to be considered.

**Comment by dart-com-ua** [comment]
hpohl, thank you for solution. This bug is still present and clearly visible if use sticky menu and do scroll down. Popups will stay on the same place
