### ISSUE TITLE
!important on many css styles makes it harder to work with

### ISSUE THREAD

**Issue by badave** [Semantic-Org/Semantic-UI#280]
It's awkward to have a CSS library that you can't easily override.  .label.blue should not force the blue to be semantic-ui's blue!important. When I want to use .blue myself, it makes it harder to do.

**Comment by em** [comment]
There's never a good reason to use !important . Unless you have no control over the DOM or external stylesheets. Which is never the case. As someone theming semantic this is a constant headache and makes my own code bad.

@jlukic I don't really understand your argument. If a class, or context, changes the style of something, then you get greater specificity and problem solved. Perhaps you could provide a real example and I'd be happy to take a look at it and provide an alternative. I'm quite confident there really is never a case where !important makes sense.

Typically when people add !important it's because the underlying definitions they want overridden were overly specific. To fix that in CSS you are expected to update the offending definition and reduce it's specificity. But there you might find it is overriding something else overly specific. And that can go on for a while and make a relatively simple change very complicated. It's a rabbit hole. But one that can be avoided by writing good CSS and always using the lowest possible specificity to begin with. Something I'd expect from a CSS framework.

**Comment by avinashdvv** [comment]
what happens if i remove !important from the css. Any major issues that can cause issues
