### ISSUE TITLE
Unable to save file.

### ISSUE THREAD

**Issue by TreBey** [Semantic-Org/Semantic-UI#2809]
Hi, I am trying to edit some of the theme elements in the /src/themes/default directory to change the colors to my site's, but I get an error that doesn't allow me to make any changes to the files at all:

![screenshot from 2015-08-07 18 17 34](https://cloud.githubusercontent.com/assets/12147635/9147814/1ed38b5e-3d32-11e5-8527-d0f6a4719223.png)

Can someone assist me with what this issue may be? Thanks.

**Comment by fstanis** [comment]
This is not Semantic UI related - it's a linux permission issue. Check if you have the proper file permissions by typing `ll /home/magic/Code/iambey/semantic/src/themes/default/globals/site.variables` in a terminal.

**Comment by TreBey** [comment]
Thanks for the quick response. I'm sorry but I don't really know what the result of that command is telling me. It looks like the code within the files are not being rendered properly, but I'm not sure why. Here's an example of how all of my theme files look:

![screenshot from 2015-08-07 19 04 13](https://cloud.githubusercontent.com/assets/12147635/9148119/5acc81dc-3d38-11e5-88cf-4d1a74c00bc9.png)

 I just recently upgraded to Linux from Windows recently for the first time, so I am still new to the operating system. All of my other files within my project folder are allowing me to edit and save; it's just the ones in the semantic folder that have the rendering problem, and aren't allowing me to edit. Here's a screen shot of what I got back out of the terminal. Thanks!

![screenshot from 2015-08-07 18 58 41](https://cloud.githubusercontent.com/assets/12147635/9148121/61a1dbb0-3d38-11e5-84f6-c6b741029cbb.png)

**Comment by fstanis** [comment]
Please ask your question on a site like [the Unix & Linux Stack Exchange](http://unix.stackexchange.com/) or [Linux Mint Forums](http://forums.linuxmint.com/) since this is really not a good place for linux-related questions.

In short, your best bet is to do the following:

1. Right click on the folder where your project is or the folder where you downloaded semantic-ui and click on *Properties*.
2. Select the *Permissions* tab.
3. Make sure you are selected as the owner, your username is selected as the group and make sure *Create and delete files* and *Read and write* is selected everywhere where possible.
4. Click on the *Apply Permissions to Enclosed Folders* button near the bottom.

That should solve the problem. If it doesn't, please post it on the two sites I mentioned above, the people there are far more likely to be able to assist you.

**Comment by TreBey** [comment]
Thanks for the quick help. If your suggestion doesn't work I'll take it to the correct forum.
