### ISSUE TITLE
[Icons] Upgrade to Font Awesome 4.4

### ISSUE THREAD

**Issue by harangue** [Semantic-Org/Semantic-UI#2857]
http://fortawesome.github.io/Font-Awesome/icons/

A new release means new awesome icons! Would love to see these in Semantic.

**Comment by jlukic** [comment]
Lots of new icons, nice

**Comment by jholl** [comment]
@jlukic have you been working on this already?  Otherwise I was going to try and crunch out a PR for it.  A couple things, please let me know if they don't jive:

- Some of the icon names in Semantic UI are not the same in Font Awesome.  Semantic UI uses `i.icon.move` where Font Awesome uses `i.icon.arrows`.  Assuming it's possible (no Semantic UI names are used in Font Awesome) then I am going to add the correct Font Awesome name with the Semantic UI name noting in the `.overrides` and in the docs that the Semantic UI name is deprecated.

- I'd like to reorganize the docs and the `.overrides` to use headers and grouping consistent with the Font Awesome site so that it is easier to compare the two in the future.  This is going to mostly affect the way the icons appear in the docs compared to today, but should help in comparing the set in the future.

Thanks for your feedback.

**Comment by jholl** [comment]
bummer... Semantic ui uses `i.icon.map` for what Font Awesome uses as `i.icon.compass`; now in this latest version 4.4 of Font Awesome they introduced a `i.icon.map`

how do you want to handle?

I guess, depending if you want to break things when you merge this PR (may have to wait for different release), or we can add a custom Semantic UI class to the new Font Awesome `i.icon.map` for now and fix it at the next breaking release.

**Comment by jlukic** [comment]
PR is a good idea. Thanks for your help. 

Icons are ordered by UTF code. I'd prefer to keep the current groupings because it makes it much easier for us to update our docs.

With regards to icon names, generally they align with their usage instead of their literal representation. Map is also aliases to [`compass`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/icon.overrides#L706), but uses the more common name `map` to align with its general use. 

Any useful names which make it easier to 'guess the icon' without having to look it up, are added to aliases section, again UTF order is preferred.

**Comment by jholl** [comment]
Okay, 

For grouping, help me understand this:

> Any useful names which make it easier to 'guess the icon' without having to look it up, are added to aliases section, again UTF order is preferred.

`.icon.compass` (`.fa-compass`) is found within alias section and the current SU `.icon.map` (which is an alias) is found within "Web Content" section; I would have thought the reverse.  Is this unintentional?  Any/All SU (re)naming should always be in aliases section?

Also, there will be naming conflicts; how do you want to handle?

Font Awesome 4.4.0 released a `.fa-map` ("\f279") which I would think becomes `i.icon.map` -- however the current SU alias for compass (for "\f14e") uses this class. IMO it raises a broader question about how best to integrate Font Awesome into Semantic UI because I suspect as both projects grow naming conflicts will become more regular.  Do you continue to "extend" Font Awesome, making it more accessible with semantic classes (possible naming conflicts); or do you allow Font Awesome to generally dictate the name (possible non-semantic, hyph/abbr rules still apply) and "write-it-off" as the consequence of integrating a third-party library?

There are currently appx 200 Semantic aliases used; and appx 10 conflicts (where FA/Semantic classes used for a different icon than Semantic)  I organized all of them by UTF and pushed to fork [here](https://github.com/jholl/Semantic-UI/blob/font_awesome_4.4/src/themes/default/elements/icon.overrides).  I'll move them back into categories for PR.

**Comment by jlukic** [comment]
We've upgraded to 5.5 in our `2.2` release
