### ISSUE TITLE
Alternative Ember.JS implementation

### ISSUE THREAD

**Issue by mfeckie** [Semantic-Org/Semantic-UI#2858]
Hi @jlukic , Now that Ember.JS has gone 2.0, I've written an integration for Semantic UI's latest version.

So far supports
- [x] Checkbox
- [x] Radio
- [x] Accordion
- [x] Popup
- [x] Dimmer
- [x] Shape
- [x] Dropdown
- [x] Modal
- [x] Sticky
- [x] Progress

Repo here https://github.com/mfeckie/ember-cli-semantic-ui

Live doc site here: http://mfeckie.github.io/ember-cli-semantic-ui/

Would be cool to get your thoughts and maybe add to the supported integrations in the future?

**Comment by jlukic** [comment]
Hi, thanks this looks awesome. We have an official ember repo, that I understand is not aligned with  `2.0`.

However there is an [active PR](https://github.com/Semantic-Org/Semantic-UI-Ember/pull/46) for making changes. I think the best route is to determine whether these two repos can be consolidated to ensure a single channel for official semantic UI ember integrations.

**Comment by listepo** [comment]
+1 :+1:

**Comment by mfeckie** [comment]
@jlukic So I've had a look at the open PR and without wishing to criticise the work that's been done and is being done, I'm not happy to wait the amount of time its taking to get the library ported across to Ember 2.0  I have two pull requests open on that project that have been around for over a month now.  I was super happy to use the original implementation, but now I feel like it's time for an alternative.

The work I've done so far is all Ember 2 compatible, has live documentation, tests which are executed on push via CodeShip.  The library uses the feature already implemented via Semantic UI wherever possible and avoids any reimplementation of features as far as possible.  It implements more of the available feature of Semantic UI and I've got plenty of time to add it.

Perhaps there's room for two implementations?

**Comment by nathanpalmer** [comment]
@mfeckie I do apologize for the delay in us shipping 2.0 support. We tripled the customer base on our application and that put both Aaron and myself out of pocket for nearly 3 months. We're back into it now and just about to wrap up the upgrade branch.

As for the pull requests you submitted we commented on both of them at the time with relevant feedback so it's clear why they weren't pulled in. (the first we had already begun the dropdown changes and were published the day after and the second we asked for you to break the changes apart but never heard back.)

Personally I'd rather avoid two implementations, but understand that you were tired of waiting. We have all of the components built out in the prep-1.0 branch and will be publishing after a bit more review and testing.

@jlukic Since this was a brand new repo and wasn't forked from the semantic-ui-ember there isn't an easy path to merging. The components/modules themselves look to be implemented independently (and without the base class that makes it easy to pass properties into settings.) I do like the live docs though, would love to see that part of the official semantic ember repo.

**Comment by mfeckie** [comment]
@nathanpalmer Great to hear that you tripled your customer base and that was keeping you busy.  I've just gone back and re-read the comment on one of the PR's and I totally misread the request to split it up, so my bad there.

It's difficult to get communication correct without the benefit of human interaction, so I apologise for the negative tone of my feedback.  Open source is hard and I should have paid more attention to ensuring that I made it clear that I really appreciate the work that's been done on the library, but sometimes finding time to update is hard and must take a back seat to the stuff that puts food on the table!
