### ISSUE TITLE
Less modifyVars + Semantic-UI + build tools

### ISSUE THREAD

**Issue by veke** [Semantic-Org/Semantic-UI#2876]
This might be more of a Less problem but Im asking here first.
As a short description:
If you want to use modifyVars in build process (using semantic.less file), modifyVars are ignored.

I've created a small semantic like file structure for a little demo. Demo can be found here: https://github.com/veke/semantic-test   (npm install, then gulp to build) 
As you can see, in the output.css file .test background url is the default one found in site.variables. It should be "override" as it is overwritten in the less options (see gulpfile.js)

I have pinpointed the problem to & { @import '...' } statements in the semantic.less file.
Any idea why those modifyVars are ignored? If you take those & { } off, the variable is correctly overwritten but in the real semantic-ui font imports are duplicated...and maybe other problems, there must be a reason to use & { } imports. (what is that & { } actually doing?, i have not found any info about that)

But if you comment out @myVar from site.variables then modifyVars is working. Strange.
Comments?

**Comment by jlukic** [comment]
Using `& { @import }` creates a scope which allows for each component to modify the same variables.

For example, `@medium` is different for `button` and `label` but this works when using both files side by side because of  `& { @import }`. If you remove the scope then components will render incorrectly because variable modifications in components will modify other components. 

Our own gulp tools process each LESS file individually instead of `@import`ing components to avoid this issue, and this is a possible workaround for other systems.

**Comment by veke** [comment]
Ahaa. Okay, I need to study those semantic build processes.
Thanks.
