### ISSUE TITLE
clear dropdown issue with dynamic menu items

### ISSUE THREAD

**Issue by rive04** [Semantic-Org/Semantic-UI#2885]
After updating dynamically the items on a dropdown it is not possible to clear its content (with 'clear' method) if an item has been selected. The hidden input with the value is cleared, but the dropdown keeps displaying the previously selected text

You can find a running example at: http://jsfiddle.net/uskhekda/1/ (forked from the example provided at https://github.com/Semantic-Org/Semantic-UI/issues/1789#issuecomment-74102863 )

After reviewing something in the code, found that when refreshing menu items, the refreshData method is removing the placeholder cached version

**Comment by Zosimas** [comment]
A way for this to work is to restore defaults before changing the html like this:
```javascript
$('.ui.dropdown').dropdown('restore defaults');
```

**Comment by bpavot** [comment]
@Zosimas Your solution does not work for me: See http://jsfiddle.net/8cqm4nvo/2/

As far as I understand, module.refresh() cleans the cached data but never restores it. 
Althought, I understand the DOM was changed in the means time, so there is no way to restore it. Then it should not have been cleaned in the first place.

Same happens if you use 'restore defaults' instead of clear.

**Comment by abossard** [comment]
Here's another example of that behavior http://jsfiddle.net/abossard/1wL9yhdf/1/
When I changed the HTML the placeholder gets lost after clear. Regardless whether or where I place a 'restore defaults'.

**Comment by abossard** [comment]
A cheap workaround that seems to work is, to destroy the dropdown, then modify the DOM and later create it again.
http://jsfiddle.net/abossard/rojofzwo/2/

**Comment by faller** [comment]
I come across the same problem.
