### ISSUE TITLE
Inverted Dimmer Not Working

### ISSUE THREAD

**Issue by aacrouch** [Semantic-Org/Semantic-UI#2915]
I wasn't sure if you reopened issues ... but I am still having trouble getting the inverted dimmer to work.

The second blurring example is on this Semantic-UI page is supposed to be inverted and it does not work.
http://semantic-ui.com/modules/dimmer.html#/examples

**Comment by jholl** [comment]
@aleesley you can keep commenting within the original issue and maintainers can decide to reopen if they want; if this is a duplicate of #2890 you can close this issue and go back to that one.

if this is not a duplicate, when you say "it does not work" do you mean in your code or in the docs?

re: your issue in #2890; your issue needs to be replicated outside of your codebase to determine exactly what in semantic-ui is causing the bug.  Unfortunately, the bug could be from some dependency or other code in your project.  Best thing to do is create a jsfiddle with semantic as the only dependency and the minimal amount of markup, css and js to reproduce (you can [fork this one](http://jsfiddle.net/cfn1tz12/) and add anything else to recreate the bug)  To be honest, I've wanted to open issues in past but after getting them to work in jsfiddle knew that it had something to do with my own code... << headaches >> ensue.

**Comment by aleesley** [comment]
The inverted dimmer is not working on this Semantic UI page .. http://semantic-ui.com/modules/modal.html#dimmer-variations

**Comment by jholl** [comment]
Yes; for me in the docs it fails, except if it is the first click after refresh.


On Aug 26, 2015, at 16:21, Andrea Leesley <notifications@github.com> wrote:

The inverted dimmer is not working on this Semantic UI page .. http://semantic-ui.com/modules/modal.html#dimmer-variations

**Comment by jholl** [comment]
here's a [jsfiddle](http://jsfiddle.net/jholl/sydbx4ax/); the short of it is this seems to happen with multiple declarations of modals (really of dimmers) because dimmer removes `variation:inverted` and fails to re-add it on subsequent dimmer init.

checkout the debug in console and look at when the various events are called.  Click the modal buttons a few time and look at the Dimmer activation in one of the later clicks ("Showing dimmer") and you'll see in the Arguments[1] that `variation:inverted` is still there.

I think the issue is related to this:

inverted class is added to the dimmer in [`module.create()`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dimmer.js#L167-L169) as a `settings.varation`

that class would be removed with [`module.remove.variation()`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dimmer.js#L434-L439) when we invoke [`destroy`] (https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dimmer.js#L99-L106),
which is what happens when we open the second modal.  Except instead of recreating the dimmer, it initializes again, which looks to be why the inverted class is not added again.  If we add the inverted class on initialization instead of creation we might solve the issue, thus allowing dimmer to have different variations.

**Comment by jlukic** [comment]
The demos in docs are sometimes a bit crude. I'm pretty sure there's an issue with how the inverted demo re-uses code from other demos, but I haven't spent much time debugging.
