### ISSUE TITLE
[Popup] - Not showing on dynamic elements

### ISSUE THREAD

**Issue by Cyb3rWarri0r8** [Semantic-Org/Semantic-UI#3047]
**Steps to Reproduce**
I'm trying to get a popup to show on some elements generated by my javascript pulling data from a remote JSON, parsing it, then making corresponding elements. 

**Expected**
The popup should show on the element

**Result**
The Popup does not do this

**Testcase**
http://jsfiddle.net/93q75c5f/1/

**Comment by maturano** [comment]
There is a problem with your testcase :)

**Comment by jlukic** [comment]
Hi, fiddle is blank

**Comment by Cyb3rWarri0r8** [comment]
Sorry I updated it. Hopefully that link works now.

**Comment by jlukic** [comment]
You've included a lot of unrelated code. Keep in mind test cases should generally just include the affected code.

You will have to bind events in the callback for AJAX, otherwise the popup/dropdown code will fire when there is still no content on the page, not causing an effect.

http://jsfiddle.net/omnmdLz0/

**Comment by Cyb3rWarri0r8** [comment]
Understood. Thank you.
