### ISSUE TITLE
Interactive installation seems broken in babun(cygwin) shell on windows

### ISSUE THREAD

**Issue by zonov** [Semantic-Org/Semantic-UI#3051]
I can't choose any option. Arrows doesn't work. Of course there is PowerShell, but...no. Powershell sucks in many ways.

**Comment by jlukic** [comment]
Probably an issue with [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) the library that powers our installer

**Comment by zonov** [comment]
Thanks for information. I'll dig deeper. Do not close this ticket, please.

**Comment by NinjaByDesign** [comment]
Just FYI this seems to be an issue with node issue https://github.com/nodejs/node/issues/2996 saves everyone else from digging around to find a solution.

**Comment by jlukic** [comment]
Thanks ninja for update, I appreciate it.

**Comment by andreyfomin** [comment]
Hi,

Sorry for this email, I don't know who of you came first with that foolish idea to create interactive installation mode  but you have to understand that you are loosing a real big clients because of that.
I worked for IBM,HP,MERCURY,AOL and now all those companies are going to use Bootstrap
instead of Semantic UI. They have automatic build that tun command "npm install"  on travis-ci and all is jammed because of you interactive build questions.

**Comment by IonutBajescu** [comment]
@zonov could you please confirm whether the issue still exists?

**Comment by jlukic** [comment]
@andreyfomin There is now a `semantic.json` option `autoInstall` that skips the interactive installer. Let me know if you can get HP, Mercury, IBM, and AOL to sign up now. I'd be super excited :)

**Comment by IonutBajescu** [comment]
Closing this since the issue has been fixed.
