### ISSUE TITLE
Top visible segment sidebar with bottom attached button breaks above a certain height

### ISSUE THREAD

**Issue by audreyr** [Semantic-Org/Semantic-UI#3102]
A top sidebar with bottom attached button breaks when:
1. You add class `visible`.
2. The top sidebar is above a certain height.

I observed this on:
* Chrome Version 45.0.2454.101 (64-bit)
* Mac OS X
* No third-party framework in use

Steps to reproduce:

----------------------------------------------------------

First, observe the (correct) behavior at http://jsfiddle.net/audreyr/wkzw63u4/12/

It looks like this closed: 
![screen shot 2015-09-27 at 2 07 43 am](https://cloud.githubusercontent.com/assets/74739/10122009/acdfb330-64bc-11e5-96aa-8de7d30b4eb6.png)

It looks like this open: 
![screen shot 2015-09-27 at 2 07 49 am](https://cloud.githubusercontent.com/assets/74739/10122010/acdf9990-64bc-11e5-8f57-b3169b278fe7.png)

So far all looks fine.

----------------------------------------------------------

Second, when you add class `visible` to the sidebar, it no longer works: http://jsfiddle.net/audreyr/wkzw63u4/13/

Here, you can see that the segment is overlapping its bottom attached button:
![screen shot 2015-09-27 at 2 07 21 am](https://cloud.githubusercontent.com/assets/74739/10122014/f8734b90-64bc-11e5-8dc3-39adca88f027.png)

----------------------------------------------------------

Third, change the segment from 2 lines to 1, and the sidebar works again: http://jsfiddle.net/audreyr/wkzw63u4/14/

At this point it looks almost fine, except that the top of the bottom attached button is a little cut off:
![screen shot 2015-09-27 at 2 07 02 am](https://cloud.githubusercontent.com/assets/74739/10122018/2883c026-64bd-11e5-869e-038d4d8588b2.png)

----------------------------------------------------------

I also tried specifying the sidebar width to be `very wide`, but as far as I understand, that doesn't work for top sidebars.

**Comment by jlukic** [comment]
Thanks for your clear test cases.

> Second, when you add class visible to the sidebar, it no longer works: > http://jsfiddle.net/audreyr/wkzw63u4/13/

Since the page has to be offset on load, there's no way for it to know the content height to add the correct offset on `pusher`. Visible generally only works on load with 'standard size' sidebars. 

If you only have a single vertical sidebar, you can adjust the [`@height`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/sidebar.variables#L45) variable to specify what SUI assumes "standard" height is. 

However if your content flows, keep in mind this height will change in different browser widths.
