### ISSUE TITLE
Form validation, adding dinamic field get error in validaton

### ISSUE THREAD

**Issue by radici** [Semantic-Org/Semantic-UI#3141]
hi,
when add dinamically select combo to a form and add validation dinamically
i get and error:
Uncaught TypeError: Cannot assign to read only property 'identifier' of false

t.identifier=i

the i variable is not defined inside the form.js ?

**Comment by jeveloper** [comment]
+1 I'm seeing this as well.

Mainly happens when form contains at least one validation (semantic js) , When clicking away from the field (no matter if on: 'blur' or on: 'change' ) , this error shows up in console
Uncaught TypeError: Cannot assign to read only property 'identifier' of false , many times mind you

**Comment by jeveloper** [comment]
For developers, this is the area of code that fails:
if(!field.identifier) {
              module.debug('Using field name as identifier', identifier);
              field.identifier = identifier; //this is what fails
            }

Line 1292

**Comment by geekus** [comment]
I'm experiencing this in 2.1.4, but not in 2.1.3.

**Comment by Banandrew** [comment]
Same here on 2.1.4. What's weird, is that validation sometimes works, but triggers that error anyway.

**Comment by IonutBajescu** [comment]
In case anyone else is experiencing this issue, please upgrade to at least v2.1.5.

Closing the issue since it was fixed by #3131.
