### ISSUE TITLE
vertical `secondary` or `tertiary` segment has no effect

### ISSUE THREAD

**Issue by robmoggach** [Semantic-Org/Semantic-UI#3143]
hey there...
in the following changing the header class to be secondary or tertiary has no effect on the background colour...

    <header class="ui vertical secondary inverted olive padded segment">
      <div class="ui fluid container">
          <h1 class="ui header">
            <i class="left inverted olive dashboard icon"></i>
            <div class="content">
              Dashboard
              <div class="sub header">
                because every intranet needs a dashboard
              </div>
            </div>
          </h1>
        </div>
    </header>

**Comment by jholl** [comment]
I set up a code pen [here](http://codepen.io/jholl/pen/qOjyyg)

I'm having a little trouble understanding what you expect to happen?  Notice [here](https://github.com/Semantic-Org/Semantic-UI/blob/4ccfad5afe63339fc707b897913c3e72b4f3ab84/src/definitions/elements/segment.less#L507-L514) the significance of the `.inverted` class on colored segments; if you remove `.inverted` in the pen does that create the expected behavior?

**Comment by jlukic** [comment]
They are different colors, perhaps subtle.
http://jsfiddle.net/ob56et2n/
