### ISSUE TITLE
checkbox default onEnable and onDisable callbacks are incorrectly defined

### ISSUE THREAD

**Issue by sarbona** [Semantic-Org/Semantic-UI#3148]
After downloading Semantic-UI 2.1.4 I have tried to disable a checkbox using the command:

$("#pageCoreBasicSwiper").checkbox("disable");

It caused a null error because I don't have a onDisable callback and in semantic the empty callbacks are incorrectly defined as:

$.fn.checkbox.settings = {
...
onEnabled           : function(){},
onDisabled          : function(){},
...
}

Changing them to onEnable and onDisable worked correctly.

**Comment by jlukic** [comment]
Well thats bad :egg: :tired_face:

**Comment by jlukic** [comment]
Fixed in `2.1.7.`

I've left in the existing "typo" names `onEnable` and `onDisable` they should be consistent with other callbacks and use `onEnabled` and `onDisabled` however this would cause backwards compat issues.

The bug will no longer produce however, because the default settings object should now match spellings nonetheless.
