### ISSUE TITLE
Semantic-UI is not getting responsive in mobile

### ISSUE THREAD

**Issue by marcuslma** [Semantic-Org/Semantic-UI#3152]
Hello, actually I have a doubt.
I'm using Semantic-UI in Meteor.
My application has a => div class="ui two column grid stackable container"
In the browser works correctly when I reduce the size of Desktop to Mobile or Tablet.
However when I open the application in a real Mobile, such as an iPhone 4 or an Asus Zenfone 2, the application continues to show in two columns, just like the Desktop, when in fact it should be in one column.
Am I doing something wrong?

**Comment by jholl** [comment]
do you have a reproduction somewhere?
could this be related to `<meta viewport>` settings in your html `<head>`?

**Comment by Ligerx** [comment]
I'm not sure if this is the exact same issue you're facing, but:

[My website](alexwang.io) is built on meteor+semantic-ui. It responds correctly to desktop media queries, but not when I'm using my Galaxy s3 browser. An online viewport tester says my screen width is 360px, but I believe that my website is using the full pixel resolution (1080). So it never becomes small enough to be stackable and stays in 2 columns.

**Comment by marcuslma** [comment]
Hi!
Add the meta tag fixed the problem, thank you jholl.
However, as Ligerx asked, the package should handle this automatically?

**Comment by jholl** [comment]
Probably not going to get head meta viewport added by default to either project; it's app case by case.

You might have luck getting a note added to the semantic docs in the getting started or templates section - but i haven't checked if it already exists.

**Comment by alexpanov** [comment]
I have had the same issue I believe.
Semantic UI is so great at making the developers that are coming from the back-end background like myself good at creating beautiful interfaces.
Unfortunately, since I am relatively new to mobile (-first) development, I forgot to include the viewport meta tag.
No matter how wide or narrow I made my Chrome mobile preview, the segments would not stack. My text appeared considerably smaller than I anticipated too.
Adding
`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">`
to my `<head>` tag completely solved the issue.
Thanks for doing such an awesome job!

**Comment by dijonkitchen** [comment]
This should be mentioned in the docs somewhere.

**Comment by xDaizu** [comment]
Couldn't aggree more. This should be written in 90's style bold flashing text.

**Comment by WhitleyStriber** [comment]
Ace suggestion and fix @alexpanov
