### ISSUE TITLE
Propose: modesty

### ISSUE THREAD

**Issue by Wandalen** [Semantic-Org/Semantic-UI#3220]
First of all thanks for the great stuff you Jack and others provide. It helps me in my career.
I preferred semantic ui over alternatives because it was tolerant to other modules. When I started to get involved, CSS of semantic was not so aggressive as bootstrap and could coexist with others. But more and more it starts to look like bootstrap, occupying more and more territory and becoming too bulky. 
In my opinion semantic ui should not have homeless rules like that:
p {
  margin: 0em 0em 1em;
  line-height: 1.4285em;
}
I believe semantic would benefit from having all rules under classes and keeping all as simple as possible letting other projects to fill the space.

**Comment by aviemet** [comment]
For my projects, I actually feel exactly the opposite; that styles from a framework should apply by default without needing to add any classes to the markup. Needing to pepper my markup with `ui` in so many places seems like the opposite of semantic code.

I think it would be very helpful if we had the option of setting a sort of namespacing for the styles. Something like a settings file (like Foundation uses) where we could either prefix the classes or opt out of the `ui` class all together.

I used Semantic for a few projects a while ago, but ended up abandoning it because having to insert so many of the same class into my markup made me feel really uncomfortable. Foundation doesn't have nearly the amount of beautiful UI components as Semantic does though, and I don't like Bootstrap, mostly for the syntax of their class names.

**Comment by jlukic** [comment]
Thanks for the kind words 

You can omit the site theme from your build in your `semantic.json`

I consider `site` a component as much as any other.
