### ISSUE TITLE
search crash - Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by Hukuta** [Semantic-Org/Semantic-UI#3240]
![selection_140](https://cloud.githubusercontent.com/assets/3100053/10715996/062fef5a-7b32-11e5-8ea4-1c1b3a219e75.png)

Just add percent symbol to search query.

Any idea?

**Comment by Banandrew** [comment]
Hello,

```JavaScript
// This line fails:
var decodedValue = window.decodeURIComponent(value);
```

It tries to decode the `%` and fails, because it's an escape character—it can't be on its own according to the rules of encoding URIs. You need to change it to `%25` somehow to be used literally; try it, it won't blow up this time.

I'm just curious, why do you want to use the percent sign in there?

**Comment by Hukuta** [comment]
>I'm just curious, why do you want to use the percent sign in there?

For example, "liquid mixture 10%"

**Comment by Banandrew** [comment]
I see, the only thing I can recommend in the meantime is to change the percent sign to `%25` on `beforeSend` with `urlData`, regex and `.replace()`. It's annoying, but I don't see any other way; ([here's a JSFiddle for example](http://jsfiddle.net/Banandrew/odhhLtp0)).

**Comment by Hukuta** [comment]
Thanks
