### ISSUE TITLE
[Visibility] Allow configurable z-index for fixing content

### ISSUE THREAD

**Issue by zash80** [Semantic-Org/Semantic-UI#3370]
Currently when setting up fixed content the created element will get following element style 
```
style="position: fixed; top: 0px; left: auto; z-index: 1;"
```
This will collide e.g. with a dimmed image (z-index: 10) where the dimmer will scroll over the fixed content (e.g. a menu). It would be good to allow fixed content's z-index to be configurable.

**Comment by jlukic** [comment]
I agree it should be a setting

**Comment by esargent** [comment]
I also ran into this. Setting would be great. But also having a default like 10 or 100 (anything greater than 1) would allow me to sneak things in between without having to change the defaults.
My use case is a fixed top menu. I have some content that needs to be layered on top of each other, but when scrolling it covers the menu. If default were higher, this would all work fine.

I've noticed a number of places where semantic sets z-index very low as default. As a framework, it would be helpful to provide more spacing between the default settings so that everything works out-of-box, but you can still sneak things in where you want without changing defaults. This would also help people not make mistakes of changing just a single value that is meant to be relative to other values and then having the other content "disappear." I know a lot of people here are power-CSS studs. I'm just a poor back-end guy who loves the ability to leverage Semantic to do things I've never had the time to learn - and would probably screw it up if you don't help me protect myself from myself!

**Comment by jlukic** [comment]
I've added this with `2.2`
