### ISSUE TITLE
[Segment] floated segments have some margin

### ISSUE THREAD

**Issue by krtschmr** [Semantic-Org/Semantic-UI#3438]
2 left floated segments
the second is having margin-top, somehow just after i clicked on the sourcecode at the documentation. 
(but always with margin in my application)

http://i.imgur.com/WqXiTue.png

bug or i am stupid? :-)

**Comment by ffgregormueller** [comment]
This is correct and has an impact on Semantic-UI-React where floated segments never align vertically.

Can be reproduced by clicking on the `show source` button in the example (https://semantic-ui.com/elements/segment#floated):
![image](https://user-images.githubusercontent.com/28727932/29610068-59292e4e-87f9-11e7-9120-a35b56b425f6.png)

**Comment by Banandrew** [comment]
I wanted to open a proposal, but then realized that I don’t understand why these `.floated` variations have such margins, I can imagine some use cases, but it’s pure speculation—I mean, maybe there is no issue at all, and it’s like that by design. I think it’d be better to wait for the maintainer’s opinion.

**Comment by ffgregormueller** [comment]
I don't think, this is intended. In the example, the segments align perfectly fine first. If you press the "Show Source" button, the margins appear. If you hide the source again, they still have the margins (not like before). And why would you want them not to align? This also has the effect that in the react version of SUI, the segments are never aligned, because this issue always appears.

Maybe there is some reason but then it should be possible to choose to not have the margins (make it controlled).
