### ISSUE TITLE
The dropdown widget does not work with dynamic content

### ISSUE THREAD

**Issue by sofiahardcode** [Semantic-Org/Semantic-UI#3471]
Hi,

I'm having a huge headache with your dropdown widget. It works great for static content (eg adding an array with results at initialization). However, when you need to add/remove items dynamically, this widget just doesn't work. I cannot understand why you didn't expose a simple add/remove method, which will resolve all such problems the right way. 

I've read all similar tickets and the only solutions you provide are terrible workarounds which not only create an overhead, but also allow for more defects. This is not professional to say the least. 

What's the problem with exposing the above mentioned functionality? Why haven't you introduced it in the first place? Do you support this thing at all or not? 

Looking forward to hearing back from you.

**Comment by sofiahardcode** [comment]
This is by far the most unfriendly widget I've ever dealt with. I'll never use this semi-working framework for anything again.

**Comment by unplugandplay** [comment]
Love and kindness. Thanks and merry xmas.

**Comment by jlukic** [comment]
Buried underneath the rudeness is a decent suggestion, unfortunately, a behavior for adding/removing values from dropdowns.

**Comment by btbjosh** [comment]
Yikes. I'll try to be more polite in my similar issue ;) 

I am also having issues with the dynamic, reactive nature of Meteor feeding new values/arrays into the dropdown. Well, actually the dropdown will populate with new choices just fine. I'm really just having trouble refreshing them when the value choices change. Even with an autorun function, it doesn't seem to update the "selected text" of the dropdown. This code does however work to set the value because I can run `.dropdown('get value')` and it will return the proper value that is being set programmatically. What doesn't work in this scenario is the `.dropdown('refresh')` and I'm not sure why.

    Template.collectionFieldDropdown.onRendered(function(){
        var self = this;
        this.autorun(function(){
            self.$('#field_'+Template.currentData()._id).dropdown('set selected', Template.currentData().field);
        });
    });

**Comment by jlukic** [comment]
Another couple options you might consider
* If you initialized from a <select> call `.dropdown('setup menu')` to regenerate the menu and attach events
* If you initialized from full dropdown, add a new `item` to menu, then call `.dropdown('refresh')`

**Comment by jlukic** [comment]
Another couple options you might consider:

If you initialized from a `<select>` call `$('.ui.dropdown').dropdown('setup menu');` to regenerate the menu and attach events.

If you initialized from full dropdown, add a new `item` to menu, then call `$('.ui.dropdown').dropdown('refresh')`

Generally both of these will automatically happen because of `observeChanges`, but if you are using a framework like Meteor that manage lifecycle tightly you might need to do it manually.

**Comment by btbjosh** [comment]
Thanks for the response... 
By "do it manually" are you referring to `.dropdown('set text')` ?? I did try that and it seems to work within my autorun function. I just wasn't sure if there was something I was missing.
