### ISSUE TITLE
Placeholder in IE11 looks Bolder

### ISSUE THREAD

**Issue by MonishaSeshaiyan** [Semantic-Org/Semantic-UI#3476]
While using placeholder with Semantic UI for input tags in IE11, it looks bolder(like something have already made as an input). Please suggest if there is an default option/settings to avoid it. Thanks in advance...

**Comment by jokeronaldo** [comment]
May you take a screen shot and show us? It seens fine here, can't see **bolder** as you describing.

**Comment by avalanche1** [comment]
Closing because no test case.

**Comment by krosssc** [comment]
Re-opening as we have noticed this in our application too. The issue described in the ticket (bold text) is not quite right. It's the same color as input text (black for most cases) instead of a placeholder grey color.

Here is a screen shot showing IE on top and Chrome on the bottom
![placeholder](https://cloud.githubusercontent.com/assets/18007670/19697247/05327eb0-9ac1-11e6-9171-839629a4cf92.PNG)

IE 11 version: 11.321.14393.0
Chrome version: 53.0.2785.143
