### ISSUE TITLE
Add Back Peer Dependencies

### ISSUE THREAD

**Issue by kongdigital** [Semantic-Org/Semantic-UI#3511]
I was wondering what is the solution for 2.1.7 for installing peer dependencies? As it stands I'm using node v4.2 npm 2.14.7 and it's not installing the appropriate peer dependences.

I read the [issue](https://github.com/npm/npm/issues/6565) on npm but no one addressed the problem. What is the solution to install multiple peer dependencies on npm 2?

**Comment by jlukic** [comment]
Somehow a commit to remove peer dependencies got finangled into `2.1.7`. This would cause things to break in NPM < 3. 

Generally, removing peer depencies works A-OK for NPM 3 (the dep graph is flat). Since peer dependencies are ignored anyways, this works out great.

For SUI to support both NPM 2 and 3 we should probably still be leaving peerDependencies until NPM2 support is dropped (probably SUI `3.0`)

**Comment by kongdigital** [comment]
Thanks for fixing that i'll just use 2.1.6 in the meantime.

**Comment by amad4biz** [comment]
ok thanks I will stick with it until 2.1.8

**Comment by tiborsaas** [comment]
+1 on this issue. 
temporal fix is to copy `node_modules` folder to the project folder, where the `Gulpfile.js` is.
