### ISSUE TITLE
Semantic UI size vs Bootstrap size

### ISSUE THREAD

**Issue by Alekusu** [Semantic-Org/Semantic-UI#3559]
Hello everybody !

First, i must to say i'm a big fan of Semantic UI since 2 years.

In a time where the size of a page is one of the main point in the SEO strategy i checked the size of Bootstrap & Semantic UI.

For the combo JS+CSS minimized, Bootstrap 3 is 200ko, Bootstrap 4 is 150ko and Semantic UI is....750ko
The SEO specialists recommend the whole page should be under 1600ko. (with text, images, ads, etc)

Of course you can optimize it after with gzip compression but it's always better if initially the minimized files are very light.

What do you think about it ? Is there an initiative to make Semantic UI lighter ? It's a work in progress ? a top-priority task ? Or do you think it's not important at all ?

Thanks a lot :)
and congratulations again for your amazing work !

**Comment by petruavram** [comment]
@Alekusu you're supposed to use only the components that you require. Semantic UI is much bigger because it is much more feature rich, but I don't think that I personally can imagine of a real world situation where you need all the components in the same app or site and needless to say the same page or view. Use the build process (with Gulp) or download the components separately. You can either start with the minimum and build up if you're required to provide the best bandwidth performance, or pick a subset that you think you'll need before hand.
