### ISSUE TITLE
colored icon buttons loading issue

### ISSUE THREAD

**Issue by nicely** [Semantic-Org/Semantic-UI#3613]
if i use "icon button" with colored icon like this;

```
<button title="user" class="ui tiny  icon button"><i class="remove user icon"></i></button>
```

its okay but if i add "loading" attr into button class and gives a color as attr to "i" class , loading icon shows on icon  , icon is still appear on button it should hide normally.

```
<button title="user" class="ui tiny loading icon button"><i class="remove user icon"></i></button>
```

 This situation is only valid for colored icons , help :dash:  me

**Comment by Morrolan** [comment]
@nicely - your code doesn't match what you are saying, but I believe I have deciphered it.

<https://jsfiddle.net/Morrolan/cnorLz5a/>  demonstrates what you mean by adding colour to the icon rather than the button.  My question is, why would you do this?  What are you trying to achieve?

A test-case demonstrating exactly what you mean is always advised, as stated in the [contribution guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

**Comment by nicely** [comment]
:D Good question , i just wanted it for a good design i think semantic ui should be fit for all purposes.
