### ISSUE TITLE
Call for Active Board Maintainers

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI#3638]
I'm looking for individuals who would like to help manage the GitHub issues board. 

This would include 
- Explaining the necessary components for a bug report to be considered (isolated test case, reproducible steps, as outlined in the [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md))
- Labeling and categorizing issues 
- Removing stale threads 
- Helping keep me alerted to confirmed and urgent bugs that need patching

It's very enjoyable to build and distribute open source code, but it becomes difficult to keep up with the torrent of questions related to the project. I'm currently sitting at around 700 unread GitHub notifications which is just too much for one person to reasonably handle.

If you'd be interested in helping, and have some familiarity with the project, please feel free to reach out. jack@semantic-ui.com, or in this thread.

As a side note, I wanted to mention that I will be speaking at [Stanford's ACM](http://stanfordacm.com/) meetup this Wednesday for any students who happen to be around.

**Comment by ronaldo-systemar** [comment]
May I can help. I'm active at gitter and familiar with semantic-ui. BTW, a little suggestion, can you add an integration with VUE.js?

**Comment by xDaizu** [comment]
I'm **new** around here (been using Semantic UI for *a week*) but I am pretty interested in your project.

Your issue board actually looks **overwhelming* for a lone *solver* (or even a couple people); and that makes me feel *a lot* of respect about your labor.

I can't (and won't) do any PR because I'm still not confident about my knowledge of your arquitecture; I'm still learning where all the ropes are (and trying not to *hang myself* with them), but wherever I can I will try to help solving (or at least, *diagnosing*) issues whenever I see something I feel it is within my knowledge (and **hopefully**, I will do more *good* that harm :sweat_smile: )

**Comment by vinicius73** [comment]
Do you have interest in creating components for official VueJS?
I would be willing to contribute to this migration.

**Comment by Ryuno-Ki** [comment]
@xDaizu Anyone can ask questioners to follow the points outlined in the Contribution.md.

No coding styles needed. And labelling issues helps alot when glancing for specific bug.
Say, you're dealing with a certrain component, than it's prudent to look for other issues around the same component (-> efficiency).

Kudos to jack!
