### ISSUE TITLE
Dropdown selection default value incorrect when specifying apiSettings

### ISSUE THREAD

**Issue by aaroncox** [Semantic-Org/Semantic-UI#3685]
If you specify `apiSettings` and a `url` while initializing a dropdown, the default value uses the value of the hidden input rather than the item's true label.

I've created a [jsfiddle](https://jsfiddle.net/cav48k3r/) showing two identical dropdowns (with one varying test class name); one initialized with no settings and one initialized with only `apiSettings`. The first test loads "Item 1" correctly as the default value, and the second test loads "1" (the value), and does not display "Item 1" like it should be. 

Is there something wrong with how I set the defaults here or did I stumble on a bug caused by the use of remote api settings?

**Comment by challet** [comment]
I'm having a similar issue, I think it has to do with the *saveRemoteData* settings, which defaults to true. When setting it to false, your example works a bit better : the "1" is no more here, but the default is now empty.

I can see two issues here : 
* an "apiSettings: true" associated to an "saveRemoteData: false" always clear the dropdown. see [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L1824).
We might want to initialize with the div.menu (or select), then use the remoteData for changing the value, especially for multiple dropdowns.
* several dropdowns with the "saveRemoteData: true" will conflict their caches for the same values, since it is shared and keys don't identify from which dropdown it is related. see [here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L1852)

**Comment by noobiwan** [comment]
Related to #3560

**Comment by jlukic** [comment]
Conversation continued in #3560
