### ISSUE TITLE
Progressive disclosure on a form

### ISSUE THREAD

**Issue by Mihai925** [Semantic-Org/Semantic-UI#3697]
Hi Semantic-UI community,

I am interested in creating a form that will give users more inputs based on the completed (and validated) inputs, but I'm not sure if you support that yet. This practice is recommended by A/B testing folks such as GoodUI. Here is my concrete example and workflow that I want to implement:
- User wants to sign up, I give him inputs for Name & Surname
- I validate the inputs and after that I display another input with an e-mail address
- User write e-mail address and that's validated, so I add the password field and the submit button
- User writes the password and submits the form

Is there any way to do that? I can only see the option to prompt the user upon unsuccessful validation, but that's limiting what I can do.

**Comment by xDaizu** [comment]
[StackOverflow](http://stackoverflow.com/) would be the preferred site for such a question, there you can get more visibility and better help, since this is not a specific issue or feature request. But, since you are here, I will try to help you out :smile: 

Just to be sure of your desired behaviour, 

1. are the validated fields editable afterwards? 
2. If they are, what happens if a not valid value is added? Do the new inputs (email address) get hidden? Does it get ineditable until fixed? Does it just get invalidated?
3. How do you want to submit the form? Via normal POST or [AJAX](https://scotch.io/tutorials/submitting-ajax-forms-with-jquery)?

**Comment by sstok** [comment]
I understand the idea, and this is great for big forms like an product ordering form.
But remember to always give a good idea about the required information and time it will take, showing there are multiple sections (products, address information, payment, order overview and acceptance) is fine.

But adding more fields as they are filled-in, sounds like a horrible idea as it breaks the expectation of time (Oh wait, I thought it were only one field! wat? another one, OK. "Sixth". F-u :joy:  ).

This technique is actually called an accordion Form.
http://alistapart.com/article/testing-accordion-forms
https://ux.stackexchange.com/questions/48692/should-i-use-accordions-within-a-multistep-form 
http://baymard.com/blog/accordion-and-tab-design

Semantic-UI provides an accordion module that provide what you are looking for, you only need add some JavaScript logic to make it all work. http://semantic-ui.com/modules/accordion.html#/definition

But already said, StackOverflow is better place to ask these questions :+1:
