### ISSUE TITLE
[UI] Add Option To Disable Colored Variations

### ISSUE THREAD

**Issue by eyalw** [Semantic-Org/Semantic-UI#3737]
Hi, 
looking at the minified css of the button element for example shows its a whooping 70kb, for a button(!).
Now I know semantic-ui is feature rich, that's why I love it.
But it seems by looking at the code, that a major factor in the size of many components is due to repetition of style classes related to different colors.

I - personally, don't use any color besides primary, secondary, gray, positive and negative.
I could probably cut back on 40% of the library size if not more - if I could just select the colors I want by myself, instead of getting the 13 default color variations for each component.

Any way to remove these from code easily?

**Comment by larsbo** [comment]
A more specific selection of components (choosing variations like button colors or types like ribbon labels) during setup would be a great but I guess this produces a lot of work :smiley:

**Comment by eyalw** [comment]
Colors will affect all the components together and will reduce size
dramatically.

This is a must have, semantic is full of bloat for a simple user right now.
Feature richness does not matter when you don't use 80% of the stuff but
have to carry it around anyway

**Comment by ardamose123** [comment]
You can [create a custom Semantic UI build](http://semantic-ui.com/introduction/build-tools.html). Just change/override the LESS files to remove the rules you don't need and recompile Semantic UI.

That way, you can choose what components you need in order to make the build smaller in the **semantic.json** file and have finer-grained control over what you have in your site/application if you ever think of removing more than just colors.

**Comment by eyalw** [comment]
I know I can hack it, but tomorrow when you release a new version I'll be
stuck with understanding how to merge it.

This is a very legitimate feature, which will very much affect adoption of
semantic ui, since library size is a major issue in web

**Comment by chrismbeckett** [comment]
+1 - the bloat caused by all the fixed color classes is just terrible. Really, imho, all colors should be themed (primary, secondary, etc). Removing these through customization would require really extensive changes, that would be hard to upgrade. Excluding these as part of the build process would seem to make more sense.

**Comment by eyalw** [comment]
@chrismbeckett how do you recommend to remove the colors in the build process?

**Comment by jlukic** [comment]
I've tried to keep the lib LESS "lite" to prevent issues with porting the library once there was a viable alternative. Unfortunately that means choosing not to embrace LESS's [obtuse control structures](http://stackoverflow.com/questions/21440789/loop-through-array-of-variable-names-in-less).

**Comment by chrismbeckett** [comment]
Yeah, loops in SASS would make sense, in LESS they suck. 

I have only reviewed a couple of files, but in buttons for example, the fixed color variation code tends to be grouped together. What about just using an variable like @includeFixedColors and putting a guard clause around all fixed color code?

**Comment by jlukic** [comment]
I think this would be fine as an option in `global/site.variables`

Actually specifying an array of acceptable colors would be, very.. hard.
