### ISSUE TITLE
[Dropdown] - Search gets more results than it should

### ISSUE THREAD

**Issue by NoSoyTsundere** [Semantic-Org/Semantic-UI#3741]
**Steps to Reproduce**
1. Search a short text on a .ui.search.dropdown with fullTextSearch true
3. Example: "rose" on this jsfiddle: http://jsfiddle.net/bcqdq91e/7/
2. See the results.

**Expected**
With the 2nd dropdown I must get only 2 results.

**Result**
Get more results.

**Version**
Semantic-UI 2.1.7

**Testcase**
Please see this fiddle
http://jsfiddle.net/bcqdq91e/7/

**Comment by ardamose123** [comment]
I just noticed that the way Semantic UI's dropdown does its fuzzy search is by the ordering of the queries' characters. (https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L744)

In the "rose" example, it first looks for an "r", then looks for an "o" after the first match, then for an "s" after the second match… and so on.

That's why the "Barcelo" entry appears for "rose" but disappears for "roses". The matches are: "BA**R**CEL**O** GRAND FARO LOS CABO**S** - ALL INCLUSIV**E**". For "roses", there's no S after the final E, so it's discarded as a result.

Maybe this is intended behavior (so it's not a bug per se), but it'd be more natural to use a Levenshtein-based algorithm with a short edit distance or something like that, as an improvement.

**Comment by NoSoyTsundere** [comment]
I see.

So this basically breaks some sections in my current project because before this was working "fine".

I have opted for Dropdown and remote content and care by myself for the search.

http://semantic-ui.com/modules/dropdown.html#remote-content

I need to fix my other .ui.search dropboxes :C

**Comment by NoSoyTsundere** [comment]
@ardamose123 thanks for the reply ^^

**Comment by jlukic** [comment]
We implement fuzzy search, this is adapted from [this repo](https://github.com/bevacqua/fuzzysearch). This is similar to mistyping a search query into google.com.
