### ISSUE TITLE
[Validation] Issues with E-mail RegExp

### ISSUE THREAD

**Issue by paulborza** [Semantic-Org/Semantic-UI#3755]
Try this email address `hajdu karcsi@yahoo.com` and it will validate fine according to Semantic UI, but the fact is that email address is invalid.

**Comment by Morrolan** [comment]
@paulborza  Is it validating the full thing or is it validating ```karcsi@yahoo.com``` and dropping the first part?

Can you create an example case in jsfiddle?

**Comment by paulborza** [comment]
@Morrolan Here's the JS fiddle you asked for: [https://jsfiddle.net/x0Lq0s8o/3/](https://jsfiddle.net/x0Lq0s8o/3/)

You can reproduce the bug there per the 3-step instructions I've added.

**Comment by jlukic** [comment]
Thanks for Thanks a lot for filing this issue, and including an easy to understand test case. I've added a milestone, and will try to take a look as soon as I can.

**Comment by ScopeyNZ** [comment]
This is a lot worse than just spaces. It appears to return true if a valid email is at least part of the string. Try `<script>alert('hello');</script>guy@example.co.nz` - returns valid.

It appears the regex is missing the start and end delimiters ('^' & '$'). 

Try `(new RegExp("^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$", 'i')).test('guy@example.co.nz')`. - I copied the code from the regex used in master.

I haven't really done any further testing on this but that appears to solve the issue.

**Comment by jlukic** [comment]
I'd accept a PR here. Regex's related to emails appear to have been solved in the completely generalized case literally nowhere on the internet.

**Comment by Ryuno-Ki** [comment]
@jlukic Um, there are [RegExes for this](https://gist.github.com/justingit/7012331/), but you don't want to build them by hand. The spec isn't [easy to grasp](https://en.wikipedia.org/wiki/Email_address#Syntax) so I'd suggest doing it the Perl way here.

**Comment by daneren2005** [comment]
I will weigh on what I am using since I found the default one to be worthless a long time ago: `var regex = new RegExp("^[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$");`

This was to fix the old rule only requiring an email in the string instead of being the entire string (ie: The first example at the top) as well as it fixed not allowing upper cases in emails.  On a production site I haven't seen any issues from this regex in quite a while, though I doubt it solves all problems with the default regex.

**Comment by jlukic** [comment]
Fixed in #3955 with a reasonable email RegExp from @kevinresol. If there's any that don't pass that filter feel free to ping me.
