### ISSUE TITLE
[Search] onSelect fires before the value is set in the field

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#3811]
Hi,

Here's the [fiddle](http://jsfiddle.net/andreyvk/6dwxq4vz/) confirming the issue

**PROBLEM**
- User searches on smth
- `onSelect` fires
- Value of the input field is set **after** `onSelect` is executed

This leads to a problem of data inconsistency, if form is submitted right away from inside the `onSelect`

**WORKAROUNDS**

Use timeout

```
onSelect: function(result, response) {
      setTimeout(function() {
          //submit form
      }, 200);
}
```

Set value manually

```
onSelect: function(result, response) {
      $("#search-field").val(result.title);
      //submit form 
}
```

**Comment by willstott101** [comment]
Looking at the code this is because setting the value of the field is considered default behaviour. So by having this callback fire before, you can cancel it by returning `false` from onSelect.
Other frameworks will have a `beforeselect` and `select` event where only the `beforeevent` is able to veto. Perhaps something like that would be useful?

**Comment by andreyvk** [comment]
@willstott101 Absolutely agree on that. Just wondering when project will be active again.
