### ISSUE TITLE
[Dimmer] - inconsistent behaviour

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#3944]
1st strange behavior:
go to http://semantic-ui.com/modules/dimmer.html#/definition, Content Dimmer. press 'show html' button (<>), press + button to show dimmer - it will appear without content.
Press 'show html' button again - dimmer controls (+/-) will become unresponsive.

2st strange behavior:
go to http://semantic-ui.com/modules/dimmer.html#/definition, Inverted Dimmer. press 'show html' button (<>), press + button to show dimmer - it will be black.
Press 'show html' button again - dimmer controls (+/-) will become unresponsive.

**Comment by IonutBajescu** [comment]
Bugs confirmed on Chrome 49 - OS X.

- In the first bug the +/- buttons are located between the example and the annotation. Moving the buttons *after* the annotation div should fix the bug.
- In the second bug the code toggling seem to change the example's div class into `html`, thing that might confuse the +/- buttons.   

I'll try release a pull request into https://github.com/Semantic-Org/Semantic-UI-Docs with fixes as this issue is related to the docs.
