### ISSUE TITLE
Hanging letters like 'g' in input fields are getting cropped.

### ISSUE THREAD

**Issue by Herteby** [Semantic-Org/Semantic-UI#3969]
The input fields (in the default style anyway) have a line-height of only ~1.2em and then a vertical padding of ~0.7 em. As letters are not allowed to extend into the padding, this causes the hanging letters in many fonts to get cropped, which looks ugly.

![example](https://cloud.githubusercontent.com/assets/6474685/14855759/a03ac45e-0c95-11e6-8c61-f36ced7ff877.png)

This could be resolved by putting the vertical padding into the line-height instead (ie. 0 vertical padding and ~2.6 em line-height).

**Comment by jlukic** [comment]
Can you provide an example jsfiddle. The purpose of setting a line-height is to avoid differences in total input height caused by differences in how browsers calculate default line height which can change `vertical-align` to be slightly off.

The line-height uses is the same as chrome's line-height for Lato, or Arial with descendors.
