### ISSUE TITLE
Display bug for divider on chrome canary

### ISSUE THREAD

**Issue by James1x0** [Semantic-Org/Semantic-UI#3986]
Can't seem to find a similar issue, but this is how vertical dividers are being displayed for me on chrome canary. (52.0.2722.0)
![displaybug](https://cloud.githubusercontent.com/assets/6146261/14983418/735c1550-10fa-11e6-9fe2-8ed772c3ec08.png)

Chrome stable, firefox, etc. show the expected result.

**Comment by jlukic** [comment]
The damn canary is chirping.

I really dont know, looks like `position: relative` isnt being respected. Thank god they fix bugs before stable :wink:

**Comment by James1x0** [comment]
Just fyi, https://bugs.chromium.org/p/chromium/issues/detail?id=618423#c5

**Comment by cbiesinger** [comment]
This bug should be reopened -- Chrome made a change to follow the current spec. MS Edge already implements the new behavior, and Firefox will follow. It would be best if Semantic updated the code to work with the new behavior (it may be helpful to use width:0 instead of position:absolute)

From the Chrome bug:
"""
This is position: absolute, not relative.

We have updated our implementation to match the spec. absolutely-positioned elements are now positioned according to the spec:
https://drafts.csswg.org/css-flexbox/#abspos-items
"""

**Comment by James1x0** [comment]
👍🏻

**Comment by James1x0** [comment]
@jlukic This is still biting in 54.0.2817.0 canary with chromium not planning on fixing this.

**Comment by James1x0** [comment]
@jlukic Quick update, this bug is now present on all latest channels of chrome including stable.

**Comment by musically-ut** [comment]
Also facing this bug. Are there any easy work-arounds?

**Comment by jmgibson1976** [comment]
Im having the same issue when testing on Edge. The issue seems to originate in /definitions/elements/divider.less, as best I can tell anyhow

    /*--------------
        Coupling
    ---------------*/

    /* Allow divider between each column row */
    .ui.grid > .column + .divider,
    .ui.grid > .row > .column + .divider {
        left: auto;
    }

when {left:auto} is removed everything seems to be in the right place via edge, chrome, & ff. Not sure what else it will have an effect on or how best to override it yet. Perhaps someone can confirm and come up with a solution.

**Comment by rodoneill** [comment]
Not sure what the resolution is here, but my quick fix is to add the 'centered' class to the parent grid. This works for me with a single vertical divider (two or more will collapse onto each other).

Removing the left: auto rule allows vertical divider to display correctly in Chrome but creates the issue in FF. Hopefully a solution arrives soon.

**Comment by jmgibson1976** [comment]
That's interesting. I'm running Firefox 47 on Linux Mint and it had no negative effect when I removed left: auto; however, it did properly position the divider in Edge on Windows 10 and Chrome (Version 52.0.2743.116 (64-bit)) on Linux Mint. I double checked.

**Comment by jmgibson1976** [comment]
That's interesting. For me, removing left: auto in FF (build 47 on Linux Mint) had no negative effect; however, in Edge on Windows 10 and Chrome (Version 52.0.2743.116 (64-bit)) on Linux Mint) the divider was now positioned properly.

**Comment by jlukic** [comment]
https://github.com/w3c/csswg-drafts/issues/401
and
https://bugs.chromium.org/p/chromium/issues/detail?id=633011

**Comment by IonutBajescu** [comment]
Merging into #4342.
