### ISSUE TITLE
Feature Request: ScrollSpy

### ISSUE THREAD

**Issue by nickretallack** [Semantic-Org/Semantic-UI#400]
Bootstrap has a feature called ScrollSpy where it will change the active state of menu items as you scroll down a page.  It would be nice if this was packaged in the javascript for Semantic UI too, for its menus.

**Comment by qJake** [comment]
Sticky menus are not what ScrollSpy does, and not what this feature request is about.

ScrollSpy will highlight the corresponding menu item when the user scrolls down to a particular anchor on that page. So, if a page has Introduction, History, Description, Summary, and Footer, and the user scrolls down the page so that they are viewing the Summary section on their screen, the "Summary" menu item will receive the "Active" class.

I vote to re-open this issue, as I think a "scroll tracking" module would fit very well with the "Sticky" module, or even a menu tab interface with scrollable content inside.

**Comment by JasonCubic** [comment]
Definitely re-open this issue.  You use scroll spy all over the Semantic-ui site and never explain how to do it.

**Comment by Banandrew** [comment]
The documentation uses SUI’s [visibility](https://semantic-ui.com/behaviors/visibility.html) component to do that, you can see it [here](https://github.com/Semantic-Org/Semantic-UI-Docs/blob/master/server/files/javascript/docs.js#L163). We should probably just add an example on the `visibility`’s page to explain the use case; I’ll create a separate issue in `Semantic-Org/Semantic-UI-Docs`, maybe someone will take care of it.
