### ISSUE TITLE
Site global site.overrides is not loading at the end, but at the beggining of the css

### ISSUE THREAD

**Issue by pmaojo** [Semantic-Org/Semantic-UI#4021]
Is that normal? The styles I add on the site.overrides files on the site/globals folder are not inserting at the end but at the beggining, so no property I am trying to override makes effect.

**Comment by jlukic** [comment]
Hi, thanks for posting, unfortunately although your question is valid, this is a usage question, and not appropriate for posting on GitHub Issues.

To help make this board manageable for maintainers to effectively work on actionable changes to the library, we've limited posts on this board to specific bug reports or feature requests. To see how we differentiate between the two, please check out our [Contributing Guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md).

To help get answers to your question (or get feedback that might allow you to repost this issue) you might want to check out one of our other support resources. 
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [ProjectTalk](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI) 
* Our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by pmaojo** [comment]
I will post a test so you can see, the site overrides are not at the end of compiled file

**Comment by steve-gray** [comment]
@pmaojo / @jlukic - We're seeing the same issue here. The overrides are being added at the top of the file, not the end - so are effectively unable to be used to override anything without setting !important on every single selector, which seems contrary to expected behavior.

If this isn't a regression, but actually a usage question: is there a specific example of this working on the latest Semantic-UI?
