### ISSUE TITLE
[Accordion] opening accordion should not unhide all tabs in content

### ISSUE THREAD

**Issue by szumm** [Semantic-Org/Semantic-UI#4042]
Hi all,
I'm using accordion with some tabs nested in it's content. I was expecting that opening the accordion will show up the active tab, but accordion forces showing up all data-tab contents. Tried to workaround it by removing 'transition visible' classes and clearing up style attr on onOpen callback but no luck.

**Testcase:**
http://jsfiddle.net/c89x3jts/1/

**Comment by lholznagel** [comment]
Would be nice if the Testcase won´t link to the default template from semantic-ui.

Maybe a look at the docs under [Accrodion/Settings](http://semantic-ui.com/modules/accordion.html#/settings) and then the settings under `Behavior` will help you?

Can´t help any more because I don´t really understand your problem here.

**Comment by szumm** [comment]
I've updated the testcase link. Now it should show the correct testcase.

**Comment by lholznagel** [comment]
For me there is still the default example. Tested in Chrome and Firefox

**Comment by IonutBajescu** [comment]
Please check the **Multiple Tab Groups** section from http://semantic-ui.com/modules/tab.html#/examples

**Comment by szumm** [comment]
Recreated testcase from the ground up: http://jsfiddle.net/svzvtn48/

**Comment by szumm** [comment]
@IonutBajescu thanks! This solves this issue.

**Comment by jlukic** [comment]
This is a setting `animateChildren`, which defaults to `true`.

http://jsfiddle.net/0q6pxgmx/
