### ISSUE TITLE
resetting dropdown

### ISSUE THREAD

**Issue by ctilley83** [Semantic-Org/Semantic-UI#4134]
The behavior in the comment directly after issue 492 was close still seems to exist.  restore defaults does not correctly restore the default text

https://github.com/Semantic-Org/Semantic-UI/issues/492

**Comment by AJRedDevil** [comment]
I faced the same problem. 
I tried it with Angular Js 2.
In my case, the problem exists in the code, where it produced error - "no property length for undefined".
After looking in the error stack I figured out the problem was in the library code. Here is the fix.

`SemanticDropdownComponent.prototype.ngAfterViewInit = function () {
        var _this = this;
        var options = Object.assign({
            onChange: function (value, a, b) {
                if (b != null && b.length) {
                    _this.onChange.emit(b[0].innerText);
                }
            }
        }, this.options);
        jQuery(this.dropdown.nativeElement)
            .dropdown(options);
    };`
