### ISSUE TITLE
[Sidebar] - background turns white after opening sidebar, doesn't revert when closing it

### ISSUE THREAD

**Issue by DHNCarlos** [Semantic-Org/Semantic-UI#4177]
A work colleague discovered an interesting UI issue during a project. The project has a darker background and utilizes the Sidebar component. Whenever opening the Sidebar it turns the background white and never returns back to the original color even after closing the sidebar.

Proof of concept: https://jsfiddle.net/ywwh5dw5/

The problem seems to originate from the `.pushable` class that is attached to the body when the Sidebar is opened. If we were to remove the class then the background is correct.

The current workaround is that we come the class when the sidebar becomes visible:

```
$("element").sidebar("setting", {
  onVisible: function() {
    $("body").removeClass("pushable");
  }
}).sidebar("show");
```

I've also tried attaching the background to both the `body` and the `.pusher` but the background still gets overwritten.

Is this intentional or a bug?

**Comment by jlukic** [comment]
This is a global variable `@pageBackground` which is in `site.variables` pusher needs to assign a color because some animations occur to animate under the current page.

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/sidebar.less#L138

I'd recommend setting your main site variables with your project as this can help set a lot of the components correctly as well that inherit from them.
