### ISSUE TITLE
tooltip not fully visible

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI#4187]
not sure if this is a bug, but maybe not the best demo of tooltip since the text can't all be seen

![image](https://cloud.githubusercontent.com/assets/957271/16428850/c0e8643c-3dae-11e6-9ff4-0ee3a4c04ef2.png)

**Comment by dorsha** [comment]
I also had this issue:
![image](https://cloud.githubusercontent.com/assets/5429033/16430768/fd8ca3cc-3d85-11e6-9143-1f3e9fb684d4.png)

The left side bar is: `ui left vertical sidebar`
It reproduced also for top fixed menu (`ui top fixed menu`).

It is important to fix, since we don't one to handle and hack the tooltip style.

**Comment by jlukic** [comment]
I'm guessing the tooltip doc demo issue is on mobile where there is no margin?

@dorsha If you want popup to be clipped by something that is not `body` use `boundary` setting and JS popups. CSS only popups cannot do any special logic for positioning, just animate in and out.

**Comment by dorsha** [comment]
OK, make sense.

**Comment by Maxhodges** [comment]
@jlukic was not on mobile but the browser was not full-screen so sidebar was hidden. Here's the context

![image](https://cloud.githubusercontent.com/assets/957271/16458116/f18191d6-3e58-11e6-8c96-1ef5bfa5094b.png)
