### ISSUE TITLE
API call on dropdown doesn't automatically load returned results in menu 

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#4288]
Maybe I am doing this wrong or maybe my assumption is wrong however, my expectation is that if I make API call on a dropdown that the returned results would be automatically displayed in the menu. This is not happening.  I am also using **on : 'now'**.

http://jsfiddle.net/kmd1970/wc8mzz3p/

**Comment by perke** [comment]
You might wanna try replicating example from [dropdown usage page](http://semantic-ui.com/modules/dropdown.html#remote-content)

**Comment by kmd1970** [comment]
Thanks, that is as helpful as saying "Just Google it". :) 

I've read the docs and I even inspect the .js files. Also, I am asking about $('.classname').api() not $('.classname').dropdown({apiSettings:{ } }).

**Comment by jlukic** [comment]
This is not planned or expected behavior. The only API/dropdown integration currently is using `apiSettings` in the dropdown's settings object. 

You could load a dropdown with `on: 'now'`` from a button but you would have to do this manually by writing values to a `<select>` or to the `dropdown menu` itself.
