### ISSUE TITLE
[Dropdown] - useLabels: false should display label if only one item is selected

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#4303]
Multiselect `useLabels: false` should still display one label in case only one item in dropdown is selected. (who cares about '1 selected' text anyway?) Or have a separate setting to enable that functionality.

**Comment by Panman8201** [comment]
IMO, separate setting. I'm using `data-label` as another source for search, but I don't want the actual label to ever show, even when selected, including only one item. By using `data-label` (instead of `data-text`) along with `useLabels:false` I'm able to successfully achieve this. Or, another option would be to introduce a `data-meta` that also applies towards dropdown searching.

**Comment by Panman8201** [comment]
Edit: I mis-understood this option at first.

👍  Now that I understand this, but perhaps an `'auto'` option that would enable this functionality? That way it doesn't break backwards compatibility and still allows for either way of handling one selection. Although I can understand not wanting string 'auto' within a boolean setting...
