### ISSUE TITLE
[Modal] Cannot auto vertical scroll when the content has only a grid

### ISSUE THREAD

**Issue by zhaoyao91** [Semantic-Org/Semantic-UI#4328]
if a put a grid inside the content, although it's high enough, it won't go into vertical scroll mode

**Comment by zhaoyao91** [comment]
![image](https://cloud.githubusercontent.com/assets/3808838/17082986/1384be52-51c3-11e6-98f0-bb420400cdd5.png)

**Comment by GDay** [comment]
You have placed images inside a modal and now the modal became too big for your screen, right? 

The easiest way to fix this is to add a max-height style to the contents of your modal. For example: `<div class="content" style="max-height: 500px:">` that should add a scrollbar to it.

If that solves your problem I would suggest you to add that max-height to your css file instead of inline, but that are details, really...

**Comment by jlukic** [comment]
Make sure your images have defined heights, otherwise they will not calculate to the correct size before loading (it cant guess the size of the loaded image).

You could also do something like call `modal('refresh')` after images load.

**Comment by zhaoyao91** [comment]
@jlukic I have tried calling `refresh` after all images loaded, but it took no effect. I also notice that if I didn't put the images into grid-columns, it will scroll correctly. So I guess there is something wrong with the algorithm of calculating the height with grid.
