### ISSUE TITLE
.ui.segment.column padding bigger top/bottom?

### ISSUE THREAD

**Issue by aristidesfl** [Semantic-Org/Semantic-UI#4383]
2em padding on top/bottom vs 1em on sides: Bug? or what is the idea?

https://jsbin.com/hitegopofu/1/edit?html,css,output

--------------------
EDIT: `.ui.grid.segment` has a similar problem

**Comment by jlukic** [comment]
This is touched on [in the columns section of docs](http://semantic-ui.com/collections/grid.html#column-content), but combining UI components on the same element generally will not work unless specifically mentioned in the docs. 

This is because the css styles may conflict when applied together, (for instance padding creates the gutters in a column, but is used to create spacing in a segment).

**Comment by aristidesfl** [comment]
@jlukic There is no documentation in the columns section about segment. Usage of segment + column/grid is supposed to be supported since there are rules for `.segment.colum` and `.segment.grid`. The values of those rules just need to be reduced by half to match the rest of the default theme.

**Comment by jlukic** [comment]
`Since columns use padding to create gutters, content stylings should not be applied directly to columns, but to elements inside of columns.` - directly from docs

**Comment by aristidesfl** [comment]
@jlukic then what are these rules for?
https://github.com/Semantic-Org/Semantic-UI/blob/ebb1cab098cad4509d8b173bd1d185b7472711f6/src/definitions/elements/segment.less#L86-L96

**Comment by jlukic** [comment]
I believe these are orphaned rules, since they are a few years old. Probably should remove.
