### ISSUE TITLE
Modal positioning with dynamic content

### ISSUE THREAD

**Issue by jlafleche** [Semantic-Org/Semantic-UI#4439]
If your modal has dynamic content that increases the vertical size of a modal, the modal scroll for out of content viewport doesn't work.

http://jsfiddle.net/hg2n5zn8/1/
^ Problem Modal shows the bug, 'Good' Modal shows what I would expect to happen after expanding the content.

This may be an expected limitation of the modal component, feel free to consider this a feature request.

**Comment by dutrieux** [comment]
Normally you need setting the observeChanges to true, but that doesn't work actually with your sample because, the MutationObserver is configuree with 'childList' and 'subtree' notify but not with 'attributes'.

To solve you problem you can after show your data, refresh the modal like this : http://jsfiddle.net/hg2n5zn8/3/

**Comment by jlafleche** [comment]
thx!
