### ISSUE TITLE
Syntax error in current http://semantic-ui.com/dist/semantic.js

### ISSUE THREAD

**Issue by cueedee** [Semantic-Org/Semantic-UI#4523]
The currently deployed semantic.js at http://semantic-ui.com/dist/semantic.js (MD5: 86de11b5f7d572f0d25d9d96c4dd3ade) produces this error:

> Uncaught SyntaxError: Unexpected identifier `semantic.js``:`**`17425`**

This is currently breaking [your jsfiddles](http://jsfiddle.net/efp8z6Ln/).

The offending line is the `className :{` line in the snippet below:

``` js
  17418   // page up/down multiplier. How many more times the steps to take on page up/down press
  17419   pageMultiplier : 2,
  17420 
  17421   selector: {
  17422 
  17423   }
  17424 
  17425   className     : {
  17426     reversed : 'reversed',
  17427     disabled : 'disabled',
  17428     labeled  : 'labeled',
  17429     vertical : 'vertical',
  17430     doubled  : 'double',
  17431   },
```

Obviously, it needs a `,` separating it from the `selector: { }` immediately above it.

Strangely enough I seem to be unable to locate this bit of code in the repo,  except for the as of yet unmerged pull request #4212, but that [does not include this error](https://github.com/Semantic-Org/Semantic-UI/pull/4212/files#diff-0a3b03a7a9ced3ca79dafdd4a521f1c2R1093).

**Comment by IonutBajescu** [comment]
Can confirm it's broken.

The problematic code can be found in the "slider" branch, which is still WIP by the looks of it.
https://github.com/Semantic-Org/Semantic-UI/commit/943ae4933376b6a4d726e10fcbe220334ca5d237#diff-52cb3744b99612b0af91190a82e69b59R1099

Not entirely sure how it made its way into the docs, since the last docs change was only meant to be a version bump to *2.2.4*.
https://github.com/Semantic-Org/Semantic-UI-Docs/commit/16c65a79884da2915978d9242d60b22bd27f9fe6

Most probably just a mistake or Jack was testing something. cc @jlukic

**Comment by amingilani** [comment]
Ummm, is there an ETA on this? I'm literally waiting on the bower build to begin working. Is there also a workaround for this?

Using bower with 2.2.4 doesn't work. However requiring files form a CDN works like in this [fiddle](http://jsfiddle.net/gilani/c8oj034h/1/]

**Comment by IonutBajescu** [comment]
This appears to have been fixed at some point in the past.
