### ISSUE TITLE
How to add Semantic-ui to Webpack with vue-cli

### ISSUE THREAD

**Issue by afrianjunior** [Semantic-Org/Semantic-UI#4620]
yesterday, im have a problem with semantic ui js to import in webpack with vue-cli.

but now that problem is resolved. im just share how do im solve this problem.

`import semantic from 'semantic'` // error

i try again.

`import semantic from 'semantic-ui'` // error again

hmm, webpack does not recognize semantic.

but im try this

`import semantic from 'semantic-ui/dist/semantic.js'` // yes, it works!

if i'm wrong, please comment. thanks!

**Comment by saitonakamura** [comment]
which package do you install, `npm i semantic-ui`?

**Comment by afrianjunior** [comment]
yups, i'm work with NPM

**Comment by saitonakamura** [comment]
I suggest that your directory structure looks like this
```
|-- webpack.config.js
|-- node_modules
|-- semantic-ui
  |-- dist
    |-- semantic.js
```

[How webpack resolves](http://webpack.github.io/docs/resolving.html)
So you achieve it three in a 3 different ways (oh you, webpack)

* Adding [resolve.root](http://webpack.github.io/docs/configuration.html#resolve-root) option
This is the recommended way, since your semantic ui dist don't have depth dependency structure
```
var path = require('path')

resolve: {
  root: [path.resolve('./semantic-ui/dist')]
}
```

* By extending [resolve.moduleDirectories](http://webpack.github.io/docs/configuration.html#resolve-modulesdirectories) (it defaults to `["web_modules", "node_modules"]`)
It suits for package managers with depth dependency structure since it moves to the parent directory until application root [like node resolve](https://nodejs.org/api/modules.html#modules_folders_as_modules) but not for this case, it's an overkill
```
resolve: {
  moduleDirectories: ["web_modules", "node_modules", "semantic-ui/dist"]
}
```

* By adding an [relolve.alias](http://webpack.github.io/docs/configuration.html#resolve-alias) to semantic
But this option clearly lacks flexibility
```
resolve: {
  alias: {
    semantic: path.resolve('./semantic/dist/semantic.js')
  }
}
```

**Comment by saitonakamura** [comment]
I also suggest using `semantic-ui-css` package if you don't use custom theming or some other features you can hack within gulp build step
It sticks right into `node_modules` so you can import it without dancing around

**Comment by krisanalfa** [comment]
For me, I use `semantic-ui-css` package and add:

```
require('semantic-ui-css/semantic.css')
require('semantic-ui-css/semantic.js')
```

In my `main.js` file.

**Comment by janat08** [comment]
require('semantic-ui-css/semantic.css')
require('semantic-ui-css/semantic.js')

Will raise error:
Uncaught ReferenceError: jQuery is not defined(…)

**Comment by krisanalfa** [comment]
Of course before you requiring ui-css, you can:

```js
window.$ = window.jQuery = require('jquery')

require('semantic-ui-css/semantic.css')
require('semantic-ui-css/semantic.js')
```

**Comment by janat08** [comment]
Uncaught TypeError: Cannot create property '_Ctor'
That happened:
vue.common.js?e881:3328 Uncaught TypeError: Cannot create property '_Ctor' on string '/pages/homePage.vue'(…)Vue.extend @ vue.common.js?e881:3328extractGuard @ vue-router.js?e71f:1420(anonymous function) @ vue-router.js?e71f:1451(anonymous function) @ vue-router.js?e71f:1532(anonymous function) @ vue-router.js?e71f:1532flatMapComponents @ vue-router.js?e71f:1531extractEnterGuards @ vue-router.js?e71f:1450(anonymous function) @ vue-router.js?e71f:1353step @ vue-router.js?e71f:1270step @ vue-router.js?e71f:1277step @ vue-router.js?e71f:1277runQueue @ vue-router.js?e71f:1281confirmTransition @ vue-router.js?e71f:1351transitionTo @ vue-router.js?e71f:1303init @ vue-router.js?e71f:1919beforeCreate @ vue-router.js?e71f:508callHook @ vue.common.js?e881:2455Vue._init @ vue.common.js?e881:3224Vue$3 @ vue.common.js?e881:3272(anonymous function) @ main.js?3479:38(anonymous function) @ app.js:700__webpack_require__ @ app.js:554fn @ app.js:85(anonymous function) @ app.js:585__webpack_require__ @ app.js:554(anonymous function) @ app.js:577(anonymous function) @ app.js:580

**Comment by janat08** [comment]
Uncaught TypeError: Cannot create property 'Ctor'
That happened:
vue.common.js?e881:3328 Uncaught TypeError: Cannot create property 'Ctor' on string '/pages/homePage.vue'(…)Vue.extend @ vue.common.js?e881:3328extractGuard @ vue-router.js?e71f:1420(anonymous function) @ vue-router.js?e71f:1451(anonymous function) @ vue-router.js?e71f:1532(anonymous function) @ vue-router.js?e71f:1532flatMapComponents @ vue-router.js?e71f:1531extractEnterGuards @ vue-router.js?e71f:1450(anonymous function) @ vue-router.js?e71f:1353step @ vue-router.js?e71f:1270step @ vue-router.js?e71f:1277step @ vue-router.js?e71f:1277runQueue @ vue-router.js?e71f:1281confirmTransition @ vue-router.js?e71f:1351transitionTo @ vue-router.js?e71f:1303init @ vue-router.js?e71f:1919beforeCreate @ vue-router.js?e71f:508callHook @ vue.common.js?e881:2455Vue.init @ vue.common.js?e881:3224Vue$3 @ vue.common.js?e881:3272(anonymous function) @ main.js?3479:38(anonymous function) @ app.js:700__webpack_require @ app.js:554fn @ app.js:85(anonymous function) @ app.js:585__webpack_require_ @ app.js:554(anonymous function) @ app.js:577(anonymous function) @ app.js:580

**Comment by janat08** [comment]
Can't tell if lack of semantic installed ought to result in an error.

**Comment by italomaia** [comment]
The suggestions by @saitonakamura did not work form me. 
The module still could not be found. 
@afrianjunior (import semantic from 'semantic-ui/dist/semantic.js') and @krisanalfa suggestions worked like a charm!

**Comment by HadrienChapel** [comment]
Hello everyone, If you were like me, working with the latest vue-cli project, and use semantic as css framework and got errors when you want to use semantic queries (which use jquery $), i give you answers i got from this topic and others I watched before:

in the App.vue (the main Vue file), import semantic with: import semantic from 'semantic-ui/dist/semantic.js' like wrote before, and for styling, you can import into <style></style> balise
'@import url("../semantic/dist/semantic.min.css");' and don't forget to include jquery in the index.html

otherwise, @afrianjunior  @krisanalfa  thanks for your help, i was stuck for some days didn't know why jquery actions wasn't working in my app

**Comment by afrianjunior** [comment]
if you work in vue ssr, you can use webpack.ProvidePlugin, like this:

``` javascript
plugin: [
  new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    }),
]
```

in App.vue 

``` javascript
<script>
  const inBrowser = typeof window !== 'undefined'
  if (inBrowser) {
    var semantic = require('../semantic/dist/semantic.js')
  }
</script>
```

``` css
<style>
  @import '../semantic/dist/semantic.css';
</style>
```

**Comment by imaia** [comment]
Also generating your semantic ui dist assets inside your src/ folder works quite nicely.

**Comment by VSG24** [comment]
@krisanalfa  Your solution seems elegant however the `require` syntax only works for `js` not `css` for me, am I missing something?

**Comment by krisanalfa** [comment]
@VSG24 Have you added [css-loader](https://github.com/webpack-contrib/css-loader) yet? If not, try to add it and see if it works.
