### ISSUE TITLE
[Nag] - Nothing happens when you click to run the code

### ISSUE THREAD

**Issue by sunildhillon** [Semantic-Org/Semantic-UI#4687]
**Steps to Reproduce**
1. Nothing happens when you click to run the code on the nag page of semantic-ui.

**Expected**
Nag was supposed to be generated 

**Result**
No result, but the result was expected. 

**Testcase**
It is live on the website page (Nag page)

latest chrome browser with windows 8.1 as OS being used.

**Comment by KillerJK** [comment]
I also was confused by this, but it seems to be working properly.
Both "run code" buttons use the same nag at the bottom.

The code for "show" will show the nag if the "accepts-cookies" cookie doesn't exist.
The code for "clear" will remove the cookie.

When you load the page, the nag is displayed.
If you click on the "x", "accepts-cookies" cookie will be created and the nag will disappear.
Show code won't work, because the cookie is there (telling the code the user accepted the nag and it shouldn't be displayed again). You must click the clear code button to remove the cookie, and then the show code will work, making the nag visible again.

So...
1. Click "x" in the nag
2. Click clear code
3. Click show code
