### ISSUE TITLE
[Dropdown] Backslash \ breaks multiple dropdown

### ISSUE THREAD

**Issue by AgileJoshua** [Semantic-Org/Semantic-UI#4688]
JSfiddle: [https://jsfiddle.net/agilejoshua/c24s8hdp/1/](https://jsfiddle.net/agilejoshua/c24s8hdp/1/)

When an option in a multiple select dropdown contains a backslash in the value then once it has been selected it stays visible (as if it where selected) even when it has been removed. The "get value" behavior of the dropdown is correct but the UI doesn't remove the item from the selected field.

**Comment by jlukic** [comment]
Can confirm, thanks!

**Comment by jaideeprana** [comment]
The issue lies in the code '$removedLabel = $labels.filter('[data-value="' + value +'"]')', its line no. 7061 of semantic.js(version 2.2.6). '\' seems to have special meaning because of which filter on labels returns an empty array. The following code fixes it: '$removedLabel = $labels.filter('[data-value="' + value.replace(/\\/g, "\\\\") +'"]')'. Appending an extra '\' escapes the '\'.
As I applied this solution on semantic.js located in dist folder and not on the src files, I will apply it and send a pull request for the fix for revision.

**Comment by jlukic** [comment]
Fixed in `2.2.8`
