### ISSUE TITLE
Safary GRID error

### ISSUE THREAD

**Issue by blackmode** [Semantic-Org/Semantic-UI#4702]
My Safary (v.5.1.7 for Windows) display examples/homepage.html  this way:
![image](https://cloud.githubusercontent.com/assets/5569648/19889050/103fdf24-a033-11e6-9352-de6206a94e33.png)

**Comment by sstok** [comment]
Are you using any special plug-ins? Adblock, Ghostery, etc.

Else try clearing your cache, sometimes the network may lag causing these problems.

**Comment by blackmode** [comment]
@sstok I have no plugins in safary, it's clear version and history is clear too... Try safary for windows and check it on your own...

**Comment by IonutBajescu** [comment]
I don't think Semantic UI supports Safari for Windows since only Safari Mac is listed in the readme: https://github.com/Semantic-Org/Semantic-UI#browser-support.

Personally I'd recommend you to change your browser, as far as I know Safari for Windows has been unofficially discontinued by Apple and hasn't received any update since 2012.
