### ISSUE TITLE
number type validation not showing error message when input is blank

### ISSUE THREAD

**Issue by SylarRuby** [Semantic-Org/Semantic-UI#4771]
Error message not displaying if the field is blank. It only shows when I input a letter.

**HTML:**

```
<input type="text id="demo" value="abc" /> // Error will show
<input type="text id="demo" value="" /> // No error and form can be submitted
```
I should be able to input integer or decimals only, ie 2 or 2.74

**JS:**

```
$('.ui.form')
  .form({
    fields: {
      demo: {
        identifier: 'demo',
        rules: [
          {
            type: 'number', // changing this to decimal works, but I need not only decimal
            prompt: 'You must enter a number'
          }
        ]
      }
    }
  })
;
```

**Comment by dopeboy** [comment]
There are two issues here:

1. The form is passing validation if the input is empty. You do not want this.
2. You would like to only accept integers and decimals as valid input.

For (1), you will need to specify an additional rule stating that the form cannot accept empty input. See [this](http://semantic-ui.com/behaviors/form.html#validation-rules) section for more.

For (2), the documentation defines the type "number" as integers and decimals. So that is enough.

I've thrown together a small example here: https://jsbin.com/moyixodube/edit?html,js,output

**Comment by SylarRuby** [comment]
@dopeboy Sorry for late reply. Adding an additional rule solved it. Thanks.
