### ISSUE TITLE
Problem with UI popup module

### ISSUE THREAD

**Issue by mau79** [Semantic-Org/Semantic-UI#4860]
329/5000
Hello to all,

I have a problem with a semantic ui module "calendar". Basically if you use it in a modal or a sidebar with the popup calendar appears below the sidebar or modal. I wrote to the module developer and he has sent me to report this issue here.

How can I solve it?

Greetings and Happy New Year to all

Mau

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Closing the issue until there’s a test case.

**Comment by BoleLee** [comment]
I also met this problem, outside the modal, the popup is nice; however, inside the modal, popup didn't appear.  I have make a test case in the JSFiddle: [http://jsfiddle.net/BoleLee/cqoyLay4/] (http://jsfiddle.net/BoleLee/cqoyLay4/). 

I'm confused because it work well when I use semantic with rails by [semantic-ui-sass gem](https://github.com/doabit/semantic-ui-sass), resently, I switch to webpack, and the problem appear.  

Waiting for your reply, thanks. @Banandrew

**Comment by Banandrew** [comment]
Hi @BoleLee, it happens, because of the popup’s `observeChanges` property being `true` by default. The property attaches [mutationObservers](http://devdocs.io/dom/mutationobserver) to automatically run `destroy` when the element is removed from the page's DOM, and that’s exactly what happens when the modal is being initialized at line 4:
```JS
$("#J_btn_modal").click(function() {
  $("#J_modal").modal("show");
});
```
Here’s what happens in detail:
1. A popup is initialized and a `mutationObserver` is created.
2. When the button is clicked, the modal is initialized. The modal component always moves a modal’s HTML from its original place in DOM to a certain wrapper during the initialization; inspect the source to see it.
3. The popup’s `mutationObserver` sees that the modal’s HTML was removed and destroys the popup.

You can fix this either by setting `observeChanges` to `false` in your popup’s settings, or by initializing the modal before initializing the popup. I hope the explanation wasn’t too confusing, please let me know if you have additional questions.
