### ISSUE TITLE
[Icon] Update Font Awesome to 4.7.0

### ISSUE THREAD

**Issue by PhilipDavis** [Semantic-Org/Semantic-UI#4892]
As a result, a few icons are missing (e.g. 'mouse pointer', 'delete calendar')

**Comment by loris** [comment]
+1

**Comment by richardtallent** [comment]
The current version of SUI is 2.2.7. I don't know what it comes with but I would guess 4.5+. 4.7.0 is the latest. I added FA manually to my pages so I'd have the latest rather than relying on SUI's bundled version. For a few icons, this meant adding my own `i.blah.icon` CSS classes to support a glyph not yet officially given an SUI class.

I suspect I'll need to do the same when 5.0 Pro is released, so it's a good habit to have already. (There's also a good chance FA will support ligatures (e.g., `<i class="icon">facebook</i>`), in which case I'd likely move away from specifying the icon using a CSS class anyway.)

**Comment by Banandrew** [comment]
Closing the issue, because Font Awesome was already updated to 4.7 with #4766, and will soon be released along other changes with 2.2.8.

**Comment by PhilipDavis** [comment]
@Banandrew Thanks for addressing this issue!  Are you saying that semantic-ui-icon will also be updated to Font Awesome 4.7? I am not using the full Semantic UI package.

**Comment by Banandrew** [comment]
@PhilipDavis Do you mean https://github.com/Semantic-Org/UI-Icon? It should, I think the robot automatically updates those, though, it delayed the 2.2.7 for some reason—hopefully, it won’t happen again. Since you’re not using the full SUI package, did you know you could remove components from your Gulp pipeline by [modifying](http://semantic-ui.com/introduction/build-tools.html#semanticjson) semantic.json file?

**Comment by PhilipDavis** [comment]
@Banandrew Hmm... I have neither a Gulp pipeline nor a semantic.json... I've been doing `npm install --save semantic-ui-icon` (and other select Semantic UI packages).

**Comment by Banandrew** [comment]
@PhilipDavis I thought it was something you might want to know; If you follow the default installation process with `npm install semantic-ui --save` that will install everything the framework has to offer to `node_modules`, you can use the default build tools to build production-ready CSS/JS from the source (basically `cd` into the folder where the framework was installed, and run `gulp build`). If you follow that route, you don’t have to rely on `semantic-ui-icon` to be updated, you just modify `semantic.json` by removing components that you don’t need from `components` array—when you do that, production files are built without those components, so, say, if you only need icons, it will only put `semantic-ui-icon` in your `semantic.min.css`.

**Comment by PhilipDavis** [comment]
@Banandrew awesome, very good to know. Thanks for the tip!  :)
