### ISSUE TITLE
Beginner friendly issues?

### ISSUE THREAD

**Issue by tarang9211** [Semantic-Org/Semantic-UI#4901]
Hey guys! Are there any beginner friendly issues I can start out with? I use this library at work and would love to help out!
Please do let me know!

**Comment by vinayakkulkarni** [comment]
Just search whatever problems you face in the search bar on [Issues](https://github.com/Semantic-Org/Semantic-UI/issues) page
These might come in handy
For any initiation related issue:
#4565 
For Responsive Help
#1114

**Comment by Banandrew** [comment]
@tarang9211 Hello, and thanks for participating! I’d also recommend to join the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), because beginner-friendly questions pop up there quite often. I’ll close this issue—it’s almost been a month, and I don’t think you’ll be getting any more feedback. Also, please see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board, and why the issue was closed.
