### ISSUE TITLE
Setting "@defaultBorderRadius: 0em;" does not change "Label" component

### ISSUE THREAD

**Issue by felixis-1** [Semantic-Org/Semantic-UI#4912]
Setting the "@defaultBorderRadius: 0em;" value in "site.variables" does not have any impact on the border radius generated for "Label" component.

**Comment by Banandrew** [comment]
@felixis-1 

Because it’s a different variable—`@borderRadius` in `src\definitions\elements\label.less`.

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
