### ISSUE TITLE
Sidebar problem on mobile

### ISSUE THREAD

**Issue by bunyaminsg** [Semantic-Org/Semantic-UI#4939]
I am having a trouble with sidebars. In my phone and in the chrome's device simulator the sidebar is not disappearing until the pusher content fills the screen. 

I am using Angular2 and I used the sidebar as 
```

$(this.el.nativeElement)  // this is equal to $('.ui.sidebar')
      .sidebar({context: this.context})  // this.context is '#app'
      .sidebar('setting', 'transition', 'overlay');
```

```
<div id="#app">
<div context="#app" class="ui left vertical menu sidebar" style="margin-top: -1rem !important;">
  <div class="ui item padded container center aligned" style="margin-top: 1rem; background-color: rgba(30,30,30,0.2) !important;">
    <img class="ui circular image small centered padded" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRgOdsPLyxMsGbuttXJjzM-DhBW-CvIF2w2PLxcOEYGLjGMZ_Y_">
    <h3>Dr. English Muffin</h3>
    <h6>Practitioner</h6>
  </div>
  <a class="ui item"><i class="large home icon"></i> Home</a>
  <a class="ui item"><i class="large plus icon"></i> My Patients</a>
  <a class="ui item"><i class="large inbox icon"></i> Inbox</a>
</div>
<div class="pusher">
    ....
 </div>
</div>
```
I also tried moving sidebar from inside of the div to body, however result is the same. 

Another problem is that when I scroll the sidebar up or down, it may disappear and pusher stays dimmed.

Here are the screen shots:

![11](https://cloud.githubusercontent.com/assets/17711596/22245229/96fbdebe-e237-11e6-853f-d4580ca975d6.png)
![22](https://cloud.githubusercontent.com/assets/17711596/22245233/983389e4-e237-11e6-86f0-d5cbcd93545a.png)
![33](https://cloud.githubusercontent.com/assets/17711596/22245230/972ea934-e237-11e6-834b-701d0325a3cb.png)
![44](https://cloud.githubusercontent.com/assets/17711596/22245232/97c0ad16-e237-11e6-9fab-32cb902259c9.png)

**Comment by Banandrew** [comment]
@bunyaminsg 

I had a similar problem with Vue 2, and solved it by overriding a rule in `src/site/modules/sidebar.overrides`:
```LESS
.left.sidebar {
  // Additional rules that you need.
  z-index: @topLayer !important;
}
```
If it’s not enough to make it work, then I forgot to mention some additional steps that I made; join the community on Gitter, I’ll dig into my case, and we’ll think of something. I’ll close the issue for now, because it only seems to appear when you use SUI’s sidebar in combination with front-end frameworks, but If we end up finding that it’s not the case, we’ll reopen it in no time. The following is a standard response.

Please use the [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI), the [official forums](http://forums.semantic-ui.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) to ask usage questions; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
