### ISSUE TITLE
gulp build command ignores *.overrides files completely

### ISSUE THREAD

**Issue by tarvos21** [Semantic-Org/Semantic-UI#4982]
Changes in `src/themes/github/collections/menu.overrides`, or any other `*.overrides` files, are ignored by the `gulp build` or `gulp build-css` command, they just do not show up in the final `semantic.css` or `semantic.min.css`.

Anyone encounters the same problem?

I install and use Semantic-UI as the guide says.

**Comment by Banandrew** [comment]
Hi @tarvos21,

I’ve reached out to you on Gitter, and will be closing this for now as a usage question, and if it turns out to be a bug, I’ll reopen it. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by tarvos21** [comment]
@Banandrew, thanks great for you response, I have seen your message on Gitter.
Finally, I discover it's caused by a missing right curly brace in the LESS file, but I got no warning message, anyway, it's a good lesson for me. Thanks again. Sorry for my wrong usage of the issue function here.
