### ISSUE TITLE
Missing icons.woff2 in material ui theme

### ISSUE THREAD

**Issue by nakhade** [Semantic-Org/Semantic-UI#4983]
I've build the material ui theme by changing the theme from default to material for all the elements in theme.config.

When I use that in my application, I get following error message:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5555/css/themes/material/assets/fonts/icons.woff2

I looked at the - semantic/dist/themes/material/assets/fonts folder, but I don't see icons.woff2 generated there.

and I can see that in semantic.css, woff2 is being referenced:

/*******************************
             Icon
*******************************/

@font-face {
  font-family: 'Icons';
  src: url("./themes/material/assets/fonts/icons.eot");
  src: url("./themes/material/assets/fonts/icons.eot?#iefix") format('embedded-opentype'), **url("./themes/material/assets/fonts/icons.woff2") format('woff2'),** url("./themes/material/assets/fonts/icons.woff") format('woff'), url("./themes/material/assets/fonts/icons.ttf") format('truetype'), url("./themes/material/assets/fonts/icons.svg#icons") format('svg');
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}

Is this a bug? or am I missing something in the build procedure? I cannot get icons displayed when using material ui, but if I change to default theme, then icons are displayed.

**Comment by Banandrew** [comment]
@nakhade can you please elaborate on your directory structure, where did you install SUI, and where’s the compiled CSS ended up being?

**Comment by nakhade** [comment]
Hi @Banandrew 

I built it from the source - v2.2.7
![image](https://cloud.githubusercontent.com/assets/1238896/22641181/89bf950e-ec4d-11e6-8547-353e5e373d09.png)

Added to my application:
![image](https://cloud.githubusercontent.com/assets/1238896/22641170/7fde4aee-ec4d-11e6-973a-6af153ff3850.png)

Error in the console:
![image](https://cloud.githubusercontent.com/assets/1238896/22641145/63072d6e-ec4d-11e6-9b85-bd16b9848571.png)

**Comment by Banandrew** [comment]
@nakhade sorry for the delay, will it work if you copy the default theme’s icons, so that they’ll be available under that path?

**Comment by Banandrew** [comment]
Closing the issue until there’s a reply.

**Comment by elTallarin** [comment]
Building with webpack, I have this same issue and also images are not being copied

**Comment by elTallarin** [comment]
Copying the files manually from default fix the webpack build issue, but the icons are not being displayed for me.

**Comment by acrich** [comment]
I've got the same issue as @elTallarin . I moved back to default and it works. Copying icons.woff2 from default solves the 404 but the icons aren't displayed. There are a lot of differences in the two icon.overrides files, which might be the reason. There's clearly a problem with icons in the material theme and this issue shouldn't be closed.

**Comment by Banandrew** [comment]
Hello everyone, I’ve took a closer look at it. It doesn’t use Font Awesome like the default theme, it uses something called `Material Icons`, so font files are different, icon names are different, and `content` values are different—that’s why it’s not enough to just copy the contents of the `default` theme into `material` and have working icons. You could do that, but the icons will be appearing much bigger and inconsistent with the theme, so it’s not really an option.

* Material Design went a long way since the `material` theme was introduced into SUI, and it doesn’t seem to resemble the design language anymore.
* Being incomplete, it can’t be used in production, not even as a foundation.
* Being somewhat inconsistent with the documentation, it’s confusing to use.

Packaged themes have never been complete, and I always felt like they were there just to give developers an idea on how to use them, and since other themes already do that, maybe it’s a good idea to remove the `material` theme from the framework altogether—it only confuses people, not to mention the points above.

Do we need to ship the framework with a `material` theme, and for it to be as complete as the `default` one? Things like [Materialize](https://github.com/Dogfalo/materialize) seem to be popular, but I’m not sure how they’re being used—as a foundation, or as is.

**Comment by Banandrew** [comment]
Forgot to mention the missing `*woff2`, it uses the defaults, so to fix it, you can put the following in `installation_folder/site/elements/icon.variables` and rebuild:
```LESS
@fontName: 'icons';
@src:
  url("@{fontPath}/@{fontName}.eot?#iefix") format('embedded-opentype'),
  url("@{fontPath}/@{fontName}.woff") format('woff'),
  url("@{fontPath}/@{fontName}.ttf") format('truetype'),
  url("@{fontPath}/@{fontName}.svg#icons") format('svg')
;
```

**Comment by Banandrew** [comment]
Closing as resolved.
