### ISSUE TITLE
[Divider] Text not centered

### ISSUE THREAD

**Issue by J3Rik0** [Semantic-Org/Semantic-UI#4985]
The .divider text is a bit off center, I fixed it by changing the left style from auto to 50%.

.ui.grid>.column+.divider, .ui.grid>.row>.column+.divider {
    left: auto; /* 50% to center */
}

![divider not centered](https://cloud.githubusercontent.com/assets/1242984/22628214/d4645204-ebd8-11e6-9daf-59dea35cee72.PNG)

![divider centered](https://cloud.githubusercontent.com/assets/1242984/22628233/300ce198-ebd9-11e6-946e-15f7aa1a4649.PNG)

**Comment by richardtallent** [comment]
Rather than screen shots, can you provide a JSFiddle example demonstrating the issue, and specify the browser you're using?

**Comment by J3Rik0** [comment]
Here you go @richardtallent https://jsfiddle.net/1dL7hec3/
So far I've noticed that the centering issue comes from the wrapper containers, if you use the divider in a standalone column the text is centered properly.

I'm using Version 58.0.3004.0 (Official Build) canary (64-bit), it does the same thing in the latest stable Chorme (Version 55.0.2883.87 m (64-bit)) and Firefox Developer Edition (53.0a2 (2017-02-06) (64-bit))

Let me know if you need any other references.

Cheers

**Comment by Banandrew** [comment]
Hi @J3Rik0,

Thanks for posting, this is a known issue: #4342. The short version is that the current implementation of a divider stopped working in Summer 2016, because browsers changed the behavior of `left: auto;` property as per W3C CSSWG specifications. The fix is coming, but it’s going to take a lot of time—you’ll have to be using an override for now. For more information, please see the original issue.

Also, let me know if you need any help figuring out how to override the `left:auto;` property.
