### ISSUE TITLE
icons showing up as squares

### ISSUE THREAD

**Issue by dmc2015** [Semantic-Org/Semantic-UI#4993]
Not sure why but my icons are not showing.
I have tested some other things and it seems to work, but icons don't.

This is just a sample project.
https://github.com/dmc2015/roku-app

You can do 'npm install' and then 'electron src/index.html'

  <i class="wheelchair icon"></i>

**Comment by Banandrew** [comment]
Hi @dmc2015,

That’s because your app’s `photon-entypo` font is overriding SUI’s `Icons` font:
```CSS
.btn-dropdown:after, .icon:before {
  font-family: photon-entypo;
  // font-family: Icons;
}
```
The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
