### ISSUE TITLE
[Dropdown] Possible bug using selectObserver in dropdown.js

### ISSUE THREAD

**Issue by nosheenzazafd** [Semantic-Org/Semantic-UI#5018]
I was getting the following error when trying to activate a search dropdown that allows user additions:
```
dropdown.js:166 Uncaught TypeError: Cannot read property 'observe' of undefined
    at Object.select (dropdown.js:166)
```
Looking at the source code, I noticed that every time `selectObserver` is dereferenced, it is guarded with `if(selectObserver)`, except for the statement at [line 165](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L165). I believe this statement also needs to be guarded with the same check. I did this and it fixed my problem. If needed I can provide more details to reproduce this error, however it seems to be a logic bug in the code.

**Comment by chrispnc** [comment]
@nosheenzazafd it's been a while since you posted this issue, but since the issue is still open I thought I would post my fix in case you or someone else runs into the same problem.

I had the same error you had, and in my case this was caused when both 1) allowAdditions is set to true, and 2) there is a selected option in a select box before the select box has `.dropdown` called on it.

My fix was to not set an option as the selected item before calling `.dropdown`, and then set the selected item in the `.dropdown` arguments like this:

`.dropdown('set selected', 'my_selected_value'))`

I hope this helps.

**Comment by lubber-de** [comment]
Fixed in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/785
