### ISSUE TITLE
How wide can a grid column be?

### ISSUE THREAD

**Issue by lmj0011** [Semantic-Org/Semantic-UI#5026]
in bootstrap you have
`col-lg-12`

What's the equivalent in Semantic-ui?

fyi, the forum was down, at the time of me making this post/issue:
![down](https://cloud.githubusercontent.com/assets/9396189/23022174/1cfd7b64-f415-11e6-9606-8d1a1a3e13a3.png)

**Comment by vinayakkulkarni** [comment]
Dear @lmj0011, Please take a look at the [Grid](http://semantic-ui.com/collections/grid.html) system by SUI.
`sixteen wide column` should work for you :)
Also, for very basic usage questions like this, ping us on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI)

PS. Also, instead of screenshot, fork this [jsFiddle](http://jsfiddle.net/efp8z6Ln/) to post a test case

**Comment by Banandrew** [comment]
Hi @lmj0011, you could also use `.sixteen.wide.computer.column` to be more specific while transferring `.lg` class to SUI.
