### ISSUE TITLE
[Dropdown] Multiple select only returning last selected value

### ISSUE THREAD

**Issue by sbaker7** [Semantic-Org/Semantic-UI#5057]
I'm trying to implement a form which allows a user to select multiple values and submit them. However, against what is specified in the docs, it is not creating delimited values. I am only getting the last selected in the results.

I am using php and jquery. Both are the latest versions, as well as the latest version of semantic UI. I have even copied and pasted the examples from the docs with no luck. I'm not sure if this is a bug or the documentation has missed a flag I should include.

According to the docs, I should just be able to do the following and it will work: 

```
<script>
  $('#list').dropdown({
    delimiter: '|'
  });
</script>
<select id="list" class="ui search selection multiple dropdown" name="list" placeholder="Select 1 or more options..." multiple="multiple">
  <?= $listoptions ?> // some list of options, as you'd expect. Nothing special.
</select>
```

Say I selected 1, 2 & 3, the last one I selected would be the only one available in the $_POST variable. Is this a bug or am I/the docs missing something?

EDIT: pretty much exactly as above but was requested, [code on JSFiddle](http://jsfiddle.net/ocfajnzo/1/). You can also hit the 'run code' button under the multiple selection heading on the docs and see it isn't creating the input field it's meant to be as specified in the code below it. [Multiple Selection Documentation](http://semantic-ui.com/modules/dropdown.html#multiple-selections)

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by sbaker7** [comment]
[JSFiddle link](http://jsfiddle.net/ocfajnzo/1/)

Couldn't get any more generic than that. When receiving the data at the other end, I only get the last value selected.

**Comment by Banandrew** [comment]
@sbaker7 Thank you. The browser submits the data:

![image](https://cloud.githubusercontent.com/assets/6409354/23245937/55f872e8-f9a1-11e6-861c-57d019194c85.png)

Please change `name="list"` to `name="list[]"` and let me know if it helped.

**Comment by Banandrew** [comment]
@sbaker7

I’ve just read your comment on Gitter and realized that I missed your other question; you’re not getting a hidden input with comma-delimited values when you initialize a dropdown directly on a `<select>` element, because a dropdown then uses its `<select>` element to manipulate values.

Another option is to initialize a dropdown on pre-existing HTML, in which case it will use a hidden input to store values with a delimiter. Other than that, the difference between the two is only in performance—it’s faster if it doesn’t need to build a dropdown’s HTML for you.

**Comment by sbaker7** [comment]
Hi Banandrew, the square brackets work fine for my case, thank you. I didn't mind how it sent the values, I just wanted to make sure I got all selected values when the form submitted. This however doesn't match up with the idea of using a delimiter as it just posts an array of values and doesn't match the docs.

The only way I got it to work with the delimiter was actually to write my own function on onChange() to set a hidden input. I could have just been doing something wrong (most likely) but trying to initialise dropdown on even the provided code on the website didn't seem to work for me.

I suppose my main issue is that it'd make sense to make sure the docs are updated to demonstrate working cases. They do work to demonstrate selecting multiple values, but it certainly doesn't work from a form submission point of view where you actually collect data. Examples should include the brackets to return an array and/or initialising so the delimited hidden input that supposed to occur according to the docs actually does occur. It's all good to be able to select values but if you can't use those values, then it becomes a little pointless.

**Comment by Banandrew** [comment]
@sbaker7 

Sorry for keeping you waiting. There’s no need to do anything inside of the `onChange()` callback, like I said, if you want to use a delimiter, you need a hidden input that’s available only when you use pre-existing HTML. The following initialized [pattern](http://semantic-ui.com/modules/dropdown.html#/usage) will send the data with a delimiter:
```HTML
<div class="ui multiple search selection dropdown">
  <input type="hidden" name="list">
  <i class="dropdown icon"></i>
  <div class="default text">Default text</div>
  <div class="menu">
    <div class="item" data-value="value">Text</div>
  </div>
</div>
```
```JS
$('.ui.dropdown')
  .dropdown({
    delimiter: '|'
  })
```
```
------WebKitFormBoundaryHuceWyeb0fGIsBhQ
Content-Disposition: form-data; name="list"

a|b|c
```
I’ll submit a PR to the documentation repository in the next few days to improve [the part](http://semantic-ui.com/modules/dropdown.html#multiple-selections) that was confusing, but I don’t think we should be putting square brackets everywhere, because it’s not the framework’s concern—it’s a feature of the PHP language (some other technologies allow you to do it as well, but not all); it will be wrong to enforce the PHP view of things, since the HTTP protocol doesn’t know anything about arrays, nor it cares about brackets in general, and SUI can be used with any kind of back-end technology.
