### ISSUE TITLE
[Dropdown] Refresh Search Results Manually

### ISSUE THREAD

**Issue by aoturan** [Semantic-Org/Semantic-UI#5068]
I am new at Semantic ui. Usually I use jquery or bootstrap at my projects but for once, I preffered semantic ui. I am using dropdown control with remote api for my search and suggestion box. What I am trying to do is when user select an item, I want to call an api request and refresh results.

How can i trigger an api call when user select an item. I tried various behaviour but I failed at all. 

Thanks and hope best.

**Comment by aoturan** [comment]
Oh, I forgot to metion about bug. When I use dropdown for remote data, events like onselect, refresh etc.. are not working. Should i convert it to search?

**Comment by vinayakkulkarni** [comment]
I use this following snippet for search..
```javascript
let t = this;
$('.ui.search').search({
        onSelect: (result, response) => {
            t.$refs.inputSearchQuantity.focus();
            t.searchProductQuery = result.name;
            t.searchedProduct = {
                "id": uuid(),
                "sku": result.sku,
                "name": result.name,
                "in_stock": result.in_stock,
                "item_id": result.id,
                "quantity": 1,
                "price": result.price,
                "tax_id": result.tax_id,
                "tax": result.tax,
                "tax_name": result.tax_name,
                "total": result.total,
                "shipping": 0
            };
        },
        apiSettings: {
            url: '/api/v2/products?q={query}'
        },
        fields: {
            results: 'data',
            title: 'name'
        },
        searchFullText: true,
        selectFirstResult: true,
        showNoResults: true,
        maxResults: 7,
        duration: 300,
        minCharacters: 3,
        cache: false
    });
```

Hope this helps.

🍻 


PS. You're missing a test case for this but I'll close it for now as search would give you the intended result

**Comment by Banandrew** [comment]
Hi @aoturan,

Just letting you know that we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

Here’s a list of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by aoturan** [comment]
Hi all,

Thanks for your help, but I think this is not a usage question, enhancement may be.

The reason of using dropdown component is multi select function. I couldn't find multiple select function when I convert it to search compnent. 

On the other hands when I use Dropdown, I could not get selected items and conduct call events. What I need is, dropdown component working with search api. I need manage request and other events.

Beside all, these forums are not very usefull when topic is Semantic-Ui. You can find anything about jquery, bootstrap... etc but not for semantic-ui.  Maybe given up semantic-ui will be the best ways. Obviously I havent preffered this way yet because I liked it. Firstly I want to use then contibute in it.

Thanks Again,
Be safe.

**Comment by Banandrew** [comment]
@aoturan 

Can you please elaborate on your use case again, you want to hit a route, show some results, then if one of those results is chosen, hit some route again and refresh the results—what happens if a user selects something for the second time? Do I understand it correctly that this dropdown should also allow a user to select multiple things?

`.multiple` dropdowns do work with API searching. Maybe you’ll be able to hack something up by combining `onChange` and some [behaviors](http://semantic-ui.com/modules/dropdown.html#/usage), the problem with that, though, is there’s currently an issue where  `onChange` gets triggered during the keyboard navigation, so I’m assuming your route will be hit every time a user presses arrows to navigate, but it’s not the case for `.multiple` dropdowns.

It is a valid usage question, but I’m not sure how to file it as a feature request—`onChange` getting triggered with keyboard navigation *is* an issue, but it’s going to be fixed; maybe we’ll figure it out if we’ll talk a bit more. In any case, if the functionality that you need is very specific and isn’t covered out of the box, you don’t have to ditch the whole framework, as the dropdown component is only a small part of it—it’s very easy to use another library for the functionality, you’ll just need to tweak its styles for the universal look.

**Comment by aoturan** [comment]
@Banandrew 

Yes, My request is a little bit specific, you are right. For my current project's necessity, only at first time I need to change data when user selected an item regarding to user's selection. Other selection behaviours can work normally.

I haven't find any solution yet. I think if I use searchbox with multi-select behaviour, I will be ok.

Is it possible or not? 

There is a mis-understand about my usage of Semantic-Ui framework. Of course, I am not using this framework only for the sake of dropdown. And also I could not change Semantic framework with another one at this point. 

I will continue to ditch this framework.  If you know how can i handle my limitation, I will be very glad.

**Comment by jlukic** [comment]
Hi @autoron your question is valid and worth having someone answer, but falls into the category of "Can Semantic UI do (X)". 

Not putting these kinds of questions here makes it easier for the volunteer maintainers to effectively manage the upcoming tasks for this project and connect them to milestones in the project

Please [check out contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md#usage-questions) for me details.

**Comment by Banandrew** [comment]
@aoturan I don’t know if it’s possible—don’t have experience building something like that with SUI; you’ll have to try it out yourself. If you’ll have other questions, though, send a message on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI).
