### ISSUE TITLE
minified css contains repeated license

### ISSUE THREAD

**Issue by pareeohnos** [Semantic-Org/Semantic-UI#5084]
Apologies if this is a duplicate issue. I did search before posting and found nothing but might have missed, but basically, after somehow screwing up my local copy install of SUI, I did a clean install (and thus update in the process) and noticed that the minified CSS it produced contains the same license for every single module that has been included which seems a bit of a waste?

I won't past a bunch of code as obviously it's quite large but heres a screenshot of what I'm referring to:

<img width="1347" alt="screen shot 2017-02-24 at 22 49 39" src="https://cloud.githubusercontent.com/assets/1657075/23324075/a76cb18c-fae3-11e6-82b8-21410e554de0.png">

Whilst not a ridiculous amount of saving, removing all comments apart from the very first license comment (obviously you want to be keeping that) the file size drops from 561KB to 536KB (and that still includes a number of new lines that I didn't remove for speed).

I appreciate this isn't a massive concern but thought I'd open an issue, as I don't think this is really something that should be occurring in a completely minified file.

**Comment by debloper** [comment]
I believe it's because of the compression settings of minification set to keep the licence intact for each CSS minified. Ideally one license segment for the entire part that shares the same license should be alright.

In this case, however, the retention of license segments looks intentional, as each of them start with `/*!` instead of regular `/*`comment block, as it tells clean-css (the minifier) to keep those comment blocks.

I'm unsure it's a problem in the build-tools, cause the build tool is working as intended.

If anything, the forced retention of license blocks from individual files has to be switched to regular comments to address this.

**Comment by pareeohnos** [comment]
I guess it makes sense for the individual files that may be produced, but certainly the combined file I don't think it should be repeated. Not sure what the best way to stop this but hopefully it can be resolved.

**Comment by j-f1** [comment]
Perhaps someone could create a PR that strips all of the comments and prepends a new license comment.

**Comment by debloper** [comment]
@pareeohnos one way to handle this is to not ignore comment in the non-minified version, as that's what should be intended, and remove comments from minified version; so, replacing the `/*!` to `/*` should do the trick.

**Comment by pareeohnos** [comment]
Great thanks, I'll give that a go. Is this something I should do just for myself or would this be something SUI would benefit from? I can try and put together a PR if so

**Comment by debloper** [comment]
I think it'd help everyone if you send in a PR, but I'm not the project owner, so mine is just a suggestion. :)

**Comment by pareeohnos** [comment]
heh alright, well I'll take a crack at it and see if it gets merged :)

**Comment by lubber-de** [comment]
The community fork [Fomantic-UI](https://fomantic-ui.com) fixed this by https://github.com/fomantic/Fomantic-UI/pull/1813
