### ISSUE TITLE
[Modal] Add width/height properties to be able to set custom modal sizes with JavaScript

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI#5109]
Hi there, I was wondering if it would be possible as an Enhancement to be able to pass in a specific size (pixels), rather than large, small etc. Right now, setting the modal size in CSS results in a bit of a mess, because of all the modal breakpoints at different screen sizes which have arbitrary margin set on them as well as %. Centering the Modal with flex box seems like it might solve a lot of the issues

**Comment by Banandrew** [comment]
Hi @raptoria, I’m a bit confused, can you please elaborate, what’s your use case that you think it’s a problem? All modals are already of a specific size in pixels, and start to use per cent values only on mobile devices to make them fluid on those screens. Because of that, setting a specific size won’t change much—if small is 760px on computer screens now, it will still be 760px on computer screens. Have I understood you correctly?

**Comment by philrykoff** [comment]
I assume you mean something like this, @raptoria ?

```javascript
$('foo').modal({
   width: 400,
   height: 200
});

```
This would be interesting for popups, too.

**Comment by raptoria** [comment]
Yes @philrykoff  that's exactly what I mean.

**Comment by kmd1970** [comment]
Yes, custom width and height for modal and popup would be nice.
