### ISSUE TITLE
why the file is clean...

### ISSUE THREAD

**Issue by rohitdesigner** [Semantic-Org/Semantic-UI#5149]
![capture](https://cloud.githubusercontent.com/assets/17812216/23800374/7e42bbce-053f-11e7-9459-abfe47cc8d66.JPG)

**Comment by Banandrew** [comment]
Hi again @rohitdesigner,

Because it’s a file for your changes if you need to override the defaults. See [“Theming”](http://semantic-ui.com/usage/theming.html).

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
