### ISSUE TITLE
Dropdown multiple selection preserve select order

### ISSUE THREAD

**Issue by brunotourinho** [Semantic-Org/Semantic-UI#5166]
Hey there!

When you select multiple values, the order you pick them is completely ignored.

Is there a way to preserve the order I pick the options?

Fiddle here:
https://jsfiddle.net/cawcxtqc/

**Comment by Banandrew** [comment]
Hi @brunotourinho,

Try to use the full dropdown HTML pattern with `get values` behaviour: https://jsfiddle.net/yfLxbjjx/3/

**Comment by brunotourinho** [comment]
Hello @Banandrew, thanks for your quick answer!
Shouldn't this behavior work for both "select-option" and the full html template?

**Comment by Banandrew** [comment]
@brunotourinho

It works with pre-existing HTML, because pre-existing HTML uses a hidden input with a delimiter to store its values, for example, `<input type="hidden" name="number" value="5,3,2">`—the order is obvious here. But when you initialize a dropdown on a `<select>` element, it hides that `<select>` element, then uses it to manipulate values instead of a hidden input in full pattern’s case.

If you look at the `<select multiple>`, how it looks in browsers by default—let’s take a look at [the first example I could find in Google](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple)—there’s no way to figure out the order of selected options, all we can know, is that they are selected.

Therefore, it shouldn’t work for both, because it can’t, and there’s no point in making the `<select>` element behave the same way, because the full pattern with a hidden input already exists to solve this problem.

**Comment by brunotourinho** [comment]
@Banandrew thank you for the explanation!
