### ISSUE TITLE
Documentation page popup bug

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [Semantic-Org/Semantic-UI#5177]
In the documentation page for [popup](https://semantic-ui.com/modules/popup.html#/examples) browse to any popup, it works fine. Now open the code for it `<>` symbol for any example, then the popup does not show up for the same. Even after you close the shown code.
Is that suppose to happen?

**Comment by Ilphrin** [comment]
I saw the same issue. Used Firefox 52 and Firefox Developper Edition 54, both under Ubuntu 16.04

**Comment by Prabhakar-Poudel** [comment]
I'm on Ubuntu 16.04. Sounds like OS specific issue.

**Comment by Banandrew** [comment]
I think it’s universal, I could see it on Windows 10 as well.

**Comment by Purus** [comment]
I can see this issue in Windows 10.

**Comment by falco467** [comment]
Hi!

This seems to be an issue with the property "observeChanges: true" - it seems that some changes in the DOM trigger the Event-Handler and so Eventlistener will destroy the Popup. If you just change something in the DOM the popup-element may be destroyed and not be automatically rebuild.

**Workaround:** Create your Popups with "observeChanges: false" - this will solve the problem and should probably be the default setting.

This should probably be the default behaviour, especially for popups with "inline: true" or a template in the DOM, since automatic destruction is usually not needed.
