### ISSUE TITLE
Dropdown: how to show no results when used with responseAsync?

### ISSUE THREAD

**Issue by xxRockOnxx** [Semantic-Org/Semantic-UI#5183]
I can see the `div` with no message in dev tools but it's not visible.

I tried `callback()` `callback({success: false})` `callback({success: true, results: []})`

As a workaround, I  do `callback({ success: true, results: [ {name: 'No results found.', disabled: true}] })`

Also btw, I can show results even if `success` is false. Is that intended?

I am trying to save search results locally to prevent frequent fetching on server. Is there also an option that allows this? Looked at the docs already. Thought there might be an undocumented option.

**Comment by vinayakkulkarni** [comment]
Hi @xxRockOnxx, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment]
Hi @xxRockOnxx, if the `results` array is empty, it will show the no results message; [here’s the demo](http://jsfiddle.net/Banandrew/o4yesdkd). Mocked responses work a bit differently, it just [checks if the response is there](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/api.js#L642) without checking the `success` property, and if it’s not, it throws an error (so you could use `response = false` to mock the error)—I’m assuming that’s because a developer knows what’s generally going to end up in the response, so yes, I think it’s intended.

I don’t think there’s an undocumented option to do that.
