### ISSUE TITLE
[HELP] Create kanban board with semantic-ui

### ISSUE THREAD

**Issue by renatomarinho** [Semantic-Org/Semantic-UI#5229]
I onwer the project Laravel GitScrum (https://github.com/renatomarinho/laravel-gitscrum) I will migrate to Semantic-UI. I'm with difficult to create a kanban board similar to that:

![GitScrum kanben](https://camo.githubusercontent.com/aa39cc4566db01beb639eadb223992770a48faa1/687474703a2f2f692e696d6775722e636f6d2f54527a524970552e706e67)

Can someone help me? Anyone know any examples?

**Comment by Banandrew** [comment]
Hi @renatomarinho,

I don’t think you’ll be able to make something like that with the default components, so there’ll have to be some custom code involved. Here’s a couple of thoughts:

* I’d try using `.ui.grid > .four.column.row` for the general layout, or if it doesn’t work for some reason, custom Flexbox layout.
* Every column should be a custom segment—they already attach to each other with `.ui.segments > .ui.colored.segment`, but all default colored variations have a colored border at the bottom, so you’ll have to move it to the top; it’s just a `box-shadow`, so not a big deal. The grey background should be a custom scrollable segment.
* Cards should probably be `.ui.card` elements, because that will give you a good base, but you’ll also have to move the colored border to the top.

I work with Laravel, so if you have some questions when you’ll actually start implementing SUI into the project, you can find me in our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI). With frameworks like this it’s always a journey when you’re trying to figure out how to use the default components to achieve a UI pattern; I could also take a closer look at it in the development branch when it’s available.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; please see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.
