### ISSUE TITLE
width of dropdown when using <select> tag with class as 'ui search dropdown'

### ISSUE THREAD

**Issue by srikalak** [Semantic-Org/Semantic-UI#5230]
when i use semantic UI in my existing project and add class 'ui search dropdown' to all my select <select> tags width specified in the style tag is never getting reflected in the ui. 
` <select class="ui search dropdown" style="width:100px">
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>     
    </select>`

when i see in developers tools the resultant code drop down is as below

`<div class="ui search dropdown selection"><select style="width: 100px;">
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option> 
    </select><i class="dropdown icon"></i><input tabindex="0" class="search" autocomplete="off"><div class="text">Alabama</div><div tabindex="-1" class="menu transition hidden"><div class="item active selected" data-value="AL">Alabama</div><div class="item" data-value="AK">Alaska</div></div></div>`

the style tag is never getting copied to the div tag hence the width set in style tag of select is  never getting reflected. Any suggestions

if this code is changed as below it works. But how do i do that i do not want to change all my select tags to div in the application

` <div class="ui search dropdown selection" style="width: 500px"><select >
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>  
    </select><i class="dropdown icon"></i><input tabindex="0" class="search" autocomplete="off"><div class="text">Alabama</div><div tabindex="-1" class="menu transition hidden"><div class="item active selected" data-value="AL">Alabama</div><div class="item" data-value="AK">Alaska</div></div></div>
`
any suggestions how this can be done

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/Banandrew/7z4vaeon).

**Comment by srikalak** [comment]
Hi Andrew,

      Please find my test case in [jsfiddle ](https://jsfiddle.net/88fgvttj/3/) 

there are four dropdowns and everything has width set setup in style. but only the once that have <div> tags will reflect the width. the width set up in <select> are never getting reflected all uses semantic ui class  "ui search dropdown". Why isnt my code working?

**Comment by Banandrew** [comment]
@srikalak Because you’re applying it to `<select>` element that becomes hidden when you initialize a dropdown with `dropdown()`. Use [full HTML pattern](https://semantic-ui.com/modules/dropdown.html#/usage) to be able to set width like that—like you did for one of the dropdowns that’s working.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

Please use one of our other support resources in the future:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
