### ISSUE TITLE
Why `Card` cannot be `inverted` ?

### ISSUE THREAD

**Issue by cemremengu** [Semantic-Org/Semantic-UI#5249]
As the title says, why is it not possible to make the card have inverted attrbiute ?

**Comment by vinayakkulkarni** [comment]
You can use a `ui segment` with [inverted colors](https://semantic-ui.com/elements/segment.html#colored) if you want, which gives you the similar look with inverted variant?

**Comment by cemremengu** [comment]
I can but `segment` does not have properties like `card` does to arrange items ? Event if I wrap the card in an inverted segment it looks like there is a white hole in the segment so it won't inherit the inverted properties of segment.

The `Card` can be colored but the color is for the border not the fill.

**Comment by Banandrew** [comment]
Hi @cemremengu, because the `.inverted` variation doesn’t exist; it’s a known enhancement: #3478. There’s [a comment](https://github.com/Semantic-Org/Semantic-UI/issues/3478#issuecomment-274318599) there that might help you to implement it in your project, it’s a bit confusing if you’re not fluent with SUI structure and how to work with the source, so please let me know if you need help with that—but if you do, please use either this thread, or [our Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by i-priyanshu** [comment]
> You can use a `ui segment` with [inverted colors](https://semantic-ui.com/elements/segment.html#colored) if you want, which gives you the similar look with inverted variant?

but when we use it with the  raised+link  class it got overwritten and the whole card turns into white color on hover...

**Comment by lubber-de** [comment]
The active community fork [Fomantic-UI](https://github.com/fomantic/Fomantic-UI) has got an `inverted` variant for the `card` element already since 2 1/2 years 
https://fomantic-ui.com/views/card.html#inverted

![image](https://user-images.githubusercontent.com/18379884/109542596-87c65480-7ac5-11eb-8808-19232a3fa268.png)
