### ISSUE TITLE
dropdown `refresh` method not disabled/enabled option

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [Semantic-Org/Semantic-UI#5273]
hi
why method refresh in `dropdown` not enabled or disabled status options ?

[example](https://jsfiddle.net/ue81hwx5/)

version : 2.2.10

**Comment by Banandrew** [comment]
Hi @abolfazl-ziaratban, that’s because you’re initialized a dropdown directly on a `<select>` element; when you do that, `<select>` becomes hidden, and the actual dropdown that you see is just dynamic HTML, so when you manipulate the hidden `<select>` you don’t see any changes. A better option would be to use [pre-existing HTML instead](https://semantic-ui.com/modules/dropdown.html#/usage).

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
