### ISSUE TITLE
Switch to Lato 2.0

### ISSUE THREAD

**Issue by salaros** [Semantic-Org/Semantic-UI#5278]
Please consider switching to [lato-font](https://github.com/betsol/lato-font), because version 2.0 sup­ports 100+ Latin-​​based lan­guages, 50+ Cyrillic-​​based lan­guages as well as Greek and IPA pho­net­ics.
It can be fetched as Bower/NPM dependency (just like jQuery is)

**Comment by Banandrew** [comment]
Right now the framework uses Google Fonts that’s is in the process of updating the font to `2.015` google/fonts#6. They rolled out an update that messed up the aesthetics early this year, and had to revert it back. They seem to be steadily getting there now—even the font’s designer is helping—so I think the issue’s going to automatically resolve itself in a couple of months; to a degree, at least.

The current implementation is convenient, because it’s just `@font-face` with LESS variables, so it’s very easy to switch Lato to something else—either on Google Fonts, or self-hosted. I think that adding an actual “heavy” dependency will be an overkill, hurting not only developers that don’t need Lato, but also that don’t need those additional glyphs.

**Comment by jlukic** [comment]
Nice find on the google font issue. You can swap to using local font paths instead of google fonts by using `@importGoogleFonts: false;`. 

I actually swapped to using the latest Lato from Latofonts.com in the semantic-ui.com docs because the rendering is that much better.

**Comment by salaros** [comment]
@jlukic I know, I have already did that. Basically I have redefined Semanti UI asset's installation path to my project folder, excluded it from Git and have created a "child theme" with just the site/global/site.variables file containing `@importGoogleFonts: false;` 
Recompiled Semantic UI with Gulp and then I added Lato 2.0 and it worked, since I haven't changed any other font-related rule, but I just wanted to avoid all these things )) that's why I reported this problem.

Anyway @Banandrew's comment sounds reasonable, hard-coding Lato 2.x as Bower/NPM dependency is really too much :)
