### ISSUE TITLE
Transitioning one component to replace another works quirky

### ISSUE THREAD

**Issue by ehudkaldor** [Semantic-Org/Semantic-UI#5315]
Hi all,
I'm trying to create a login page where it will first only show the username, and on clicking, will swap the username element with the password one.
the code is below. however, when I click the button, the container of both elements grows to the size of both, then the transition occurs and then the container shrinks back. what am i doing wrong?

HTML:
```
<form class="ui large form">
          <div class="ui stacked segment">
            <div class="transition visible field" id="input_username">
              <div class="ui left icon input">
                <i class="user icon"></i>
                <input type="text" name="username" placeholder="${'messages:login.username' | t}">
              </div>
              <div>
                <div class="ui fluid large teal button" click.delegate="moveToPass()" id="moveToPass_button">continue</div>
              </div>
            </div>
            <div class="transition hidden field" id="input_password">
              <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password" placeholder="${'messages:login.password' | t}">
              </div>
              <div class="ui buttons">
                <div>
                  <div class="ui fluid large teal button" click.delegate="moveToPass()">back</div>
                </div>
                <div>
                  <div class="ui fluid large teal button" click.delegate="login()" id="login_button">login</div>
                </div>
              </div>
            </div>
          </div>
        </form>

```

Javascript:
```
moveToUser() {
    $('#input_password')
     .transition({
       animation : 'fly right',
       duration  : '1s'
     });
     $('#input_username')
      .transition({
        animation : 'fly left',
        duration   : '0.5s'
      });
  }

  moveToPass() {
    $('#input_username')
     .transition({
       animation : 'fly left',
       duration   : '0.5s'
     });
// .onHide(
    $('#input_password')
     .transition({
       animation : 'fly right',
       duration  : '1s'
     });
  }
```

**Comment by Banandrew** [comment]
Hi @ehudkaldor,

That’s because the transitions happen simultaneously. Use `onComplete()` callback to run the second transition after the first one. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
