### ISSUE TITLE
Error: Cannot find module './../build/javascript'

### ISSUE THREAD

**Issue by adamdonahue** [Semantic-Org/Semantic-UI#5323]
Assume an existing project.

I install `gulp` (3.9.1) and `semantic-ui` (^2.2.10), and save these as development dependencies.
When prompted during the `semantic-ui` install I choose 'Automatic' and set my semantic directory to `public/semantic`.

I change into `public/semantic` and run `gulp build`; things build fine.

I check in all these files (including `dist`, to be safe).

I then create a new branch from this branch.  Same structure.  I run `npm install` to install _all_ the dependencies (now including `gulp` and `semantic-ui` in the `package.json`).  I change into `public/semantic` and run `gulp build` and get this:

```
$ gulp build
module.js:471
    throw err;
    ^
Error: Cannot find module './../build/javascript'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/adamdonahue/workspace/proj/public/semantic/tasks/collections/build.js:9:20)
    at Object.<anonymous> (/Users/adamdonahue/workspace/proj/public/semantic/tasks/build.js:23:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

Any quick ideas on what might be going on?  I suspect it's a dependency issue between `npm` packages.

**Comment by adamdonahue** [comment]
I found the issue.

**Comment by naickyserrano** [comment]
@adamdonahue Hi, we have the same exact issue. May I know what did you do to fix this problem. Your prompt response will be greatly appreciated. Thank you

**Comment by lafritay** [comment]
@naickyserrano and anyone else who hits this issue: I tracked this down to an issue with my .gitignore file.  I'm using the default Visual Studio .gitignore file.  It has an entry to ignore and folder named "build".  When you run "npm install semantic-ui" it copies a folder called "build" into semantic/tasks (as well as doing a bunch of other things).  Generally, you commit the results of that into your git repo.  Since the "build" folder is ignored though, it is left out of that commit.  Further, restoring the sematinc-ui package will short circuit if it detects that semantic is already installed.  Thus, if you pull a repo that has this issue, "npm install" won't recreate the missing "build" folder and thus you'll see this error message.

The fix here is to either remove the "build" entry from your .gitignore file or add an explicit entry to your gitignore file for this folder.
