### ISSUE TITLE
[Dropdown] You need this code to FIX ui dropdown dynamic change/selection.

### ISSUE THREAD

**Issue by kaddyadriano** [Semantic-Org/Semantic-UI#5402]
```
 //Fix ui dynamic selection
$(document).on('change','input, select',function(e){
		$('.ui.dropdown').each(function(k, el){
			el = $(el);
			var select = $('select',el).first().val(),
				text = $('select option[value="'+select+'"]',el).html();
			$('.text', el).html(text);
			$('.item', el).removeClass('active selected');
			$('.item [data-value="'+select+'"]', el).addClass('active selected');
		});
	});
```

**Comment by Banandrew** [comment]
Hi @kaddyadriano, can you please elaborate, what’s the problem that it’s fixing?

**Comment by kaddyadriano** [comment]
I was updating select inputs dynamically with javascript however, the ui dropdowns were not updating to the new passed values with JS. for example I would have 'One' selected from ui dropdown but when I change the value to 'Two' with JS, the ui dropdown would not change the text to 'Two' but the hidden input will change with no problem. The code is to listen to the change of select input and update the ui dropdowns.

**Comment by Banandrew** [comment]
@kaddyadriano I think it’s unnecessary, there’re two methods that already do it:

* `dropdown('set selected')`
* `dropdown('refresh')`

If the first can’t be used for some reason, you can use the [full HTML pattern](https://semantic-ui.com/modules/dropdown.html#/usage) instead of initializing it on a `select` element directly, change a dropdown’s options dynamically and finally `dropdown('refresh')` it to update everything. You shouldn’t be changing `select` elements directly.

There’s a possibility that you need to use `select`, then it’s a use case, and the solution—whatever it may be—doesn’t concern the framework in any way. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by kaddyadriano** [comment]
Gotcha! Thanks!
