### ISSUE TITLE
Dropdown ignores `disabled` attribute on `option` tags.

### ISSUE THREAD

**Issue by svanimpe** [Semantic-Org/Semantic-UI#5417]
In my project, I have to adjust the options shown in a `select` based on the value selected in another `select`. Using jQuery, I dynamically add/remove the `disabled` attribute on the options I wish to hide/show. Semantic UI seems to ignore this attribute however and still shows (and lets me select) disabled options. I have also tried using the `disabled item` style class, instead of the `disabled` attribute, but that didn't change anything.

**Comment by Banandrew** [comment]
Hi @svanimpe, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

[Here’s an example](http://jsfiddle.net/Banandrew/efp8z6Ln/545/) of `.disabled.item` working.

**Comment by svanimpe** [comment]
See http://jsfiddle.net/gcx7vyns/

The number in the second `select` is 1 by default, but once the value in the first `select` changes, the options in the second `select` should change so that only `option`s less than the value of the first `select` are enabled. According to the documentation at https://semantic-ui.com/modules/dropdown.html#/usage the call to `setup menu` should recreate the menu based on the `option`s in the select, but that doesn't do anything.

**Comment by Banandrew** [comment]
@svanimpe I see, there’s currently an issue with `setup menu` not working properly (#4029), and I’m closing this thread as a duplicate. If you don’t need to support clients that don’t have JavaScript enabled, you can initialize a dropdown on [the full HTML pattern](https://semantic-ui.com/modules/dropdown.html#/usage) (my example also uses it) instead of a `select` element, and use various methods like `set selected` and `get value` to do what you need to do—you can find the full list of methods right below `setup menu`. If you do need the support, though, you’ll either have to produce a lot of code duplication as a workaround, or use a third-party library.

Also, for the future, you used `setup menu` incorrectly. When a dropdown is initialized, it hides a `select` and recreates it with `div` elements, so when you run a SUI method, you need to run it on a parent `div`, which copies all of a `select` element’s classes. So, it should be `$(.ui.dropdown).dropdown('setup menu')` instead.

If you have other questions, I’ll be happy to answer them in our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by Banandrew** [comment]
@svanimpe Forgot to mention, in that original thread, there’s a comment that describes several workarounds that might help, it’s the 4th from the top.
