### ISSUE TITLE
"Middle aligned list" not working?

### ISSUE THREAD

**Issue by rongchaua** [Semantic-Org/Semantic-UI#5451]
Hi all,
I'm learning to use Semantic UI. I create a very basic example working with Grid and List but I can't get the list vertical center aligned. "Middle aligned list" doesn't work in my test case.

Demo:
https://jsfiddle.net/wc8mzz3p/18/

Screenshot:
![capture](https://user-images.githubusercontent.com/6661713/26941317-619aaf5a-4c7e-11e7-947b-d2019adeefdb.PNG)

The text and icon are not vertical-center aligned. I'm not sure if it's a bug or I make a mistake?

Thank you.

**Comment by Banandrew** [comment]
Hi @rongchaua, this happens, because you have two `.content` containers in an item, and if you inspect them separately with developer tools, you’ll see that their height is different; the `Power` one is actually correctly aligned in its container, but since the container is smaller than the other `.content` container with buttons, you can’t really see it. One option is to set the height of your smaller container to be exactly 36px, the size of your other container: https://jsfiddle.net/Banandrew/bg1t6j7d/2/ I assumed you’d want to align icons as well, so we also have to override an icon’s `vertical-align` to align it with the content. Please note that this solution is not very good, since we need to hardcode the numbers, but it can work for the sake of the example.

You can put that custom CSS in `installation_folder/src/site/elements/list.overrides`, then rebuild the framework with `gulp build`. You can read more about theming [here](https://semantic-ui.com/usage/theming.html). I’d also like to mention that SUI is not a complete bulletproof solution, it’s just a boilerplate for a developer to work with.

If you have more questions in the future, I’ll be happy to answer them in our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).
