### ISSUE TITLE
right floated button in inverted segment

### ISSUE THREAD

**Issue by ForzaSFerrari** [Semantic-Org/Semantic-UI#5490]
I just wanted to ask if this is a error or normal? I've not founded a solution for it in documentation.

https://jsfiddle.net/37kxwex8/

**Comment by Banandrew** [comment]
Hi @ForzaSFerrari, it is normal.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by ForzaSFerrari** [comment]
If this is normal. Wouldn't it be fine to improve this for the future?

**Comment by Banandrew** [comment]
@ForzaSFerrari I don’t think so. I apologize, because I don’t have time to write an elaborate answer, but the gist of it is that `.right.floated` uses the `float` property that takes it from the normal flow of the web page—that should be enough to find an answer. You didn’t find it in the documentation, because it’s out of scope; in the end, SUI is just a boilerplate for engineers, therefore, it’s a developer’s responsibility to deal with some CSS-related issues.
