### ISSUE TITLE
"$().dropdown('set selected', value)" no effect after update “select option”’

### ISSUE THREAD

**Issue by zhangyuanliang** [Semantic-Org/Semantic-UI#5516]
In my project, need update 'select option' and select one option.
Why the update is no longer work later.
JSFiddle example: https://jsfiddle.net/zhangyuanliang/a94rs9a6/9/

**Comment by leonidas-o** [comment]
I would say, your css selector is wrong and your value should be '1'.
so somethibng like: 
`$('.dropdown').dropdown('set selected', '1');`

**Comment by zhangyuanliang** [comment]
@leonidas-o I forgot to modify it, but it was not the problem.
JSFiddle example:  https://jsfiddle.net/zhangyuanliang/a94rs9a6/9/

**Comment by zhangyuanliang** [comment]
@vinayakkulkarni  My problem has not been solved, why is it closed?

**Comment by Banandrew** [comment]
Hi @zhangyuanliang, sorry for the confusion, it was closed, because although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board. Please use one of our other support resources in the future:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

On your question, you have two options here. One is to use the `setup menu` method—it’s barely documented, but [there’s a PR to fix that](https://github.com/Semantic-Org/Semantic-UI-Docs/pull/329/files), you can use it in the meantime—here’s an example:
```JS
// This is everything that should be in your `on click`:
$('.dropdown')
  .dropdown('setup menu', {
    values: [
      {
        value: '3',
        text: 'three',
        name: 'three'
      },
      {
        value: '2',
        text: 'two',
        name: 'two'
      },
      {
        value: '1',
        text: 'one',
        name: 'one'
      }
    ]
  })
  .dropdown('set selected', '1')
```
Another option is to use [the full HTML pattern](https://semantic-ui.com/modules/dropdown.html#/usage) instead of initializing a dropdown on a `select` element directly. This way, you can modify a dropdown’s HTML and call the `refresh` method to update it internally, [here’s an example](http://jsfiddle.net/Banandrew/txpeqn09/).

When you initialize a dropdown on a `select` element, it hides a `select` element and uses it only for storage, so it’s pointless to manipulate it directly. If you have more questions, I’ll be happy to answer them in this thread.

**Comment by zhangyuanliang** [comment]
@Banandrew Thank you very much. I still have a question: where i can find some examples of the use of behavior, like the usage of 'setup menu'.

**Comment by Banandrew** [comment]
@zhangyuanliang Other than the PR that I mentioned, nowhere. What is confusing about it? Its usage is pretty straightforward, the structure is always the same like in the example above, and `setup menu` removes all options from a dropdown, then recreates a menu using the values that you passed to the method.

**Comment by zhangyuanliang** [comment]
@Banandrew  I have understood your answer.  Just thinking about how to better reference your official documents. My English is not good Please understand. Thank you again for your answer.

**Comment by Banandrew** [comment]
@zhangyuanliang Not sure I understand, if you mean examples of various behaviours that are listed at the bottom of [the dropdown component’s usage tab](https://semantic-ui.com/modules/dropdown.html#/usage), the documentation doesn’t have them, well, maybe some of them, but not all, and not in one place—they’re probably scattered across all tabs. You’ll just have to read their descriptions and try them out.

If you’re stuck doing something, you can always ask a quick question in our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by j94305** [comment]
I have run into similar problems. "set exactly" does not seem to work AT ALL for dropdowns getting data from a remote service. Documentation for many Semantic UI components is sparse and incomplete - to put it mildly. After some looks into the source code, I came up with a solution different from the ones that were suggested here and in other postings. In fact, no changes to the Semantic UI source were necessary - simply a new function.

var initializeDropdown = function (elem, ids) {
  $(elem).dropdown("set value", ids);
  var idList = ids.split(",");
  for (var i = 0; i < idList.length; i++) {
    var value = someFunctionToTranslate(ids[i]);
    $(elem).dropdown("add label", ids[i], value);
  }
}

Use like this (assuming a function someFunctionToTranslate() is defined):

initializeDropdown("#my-dropdown", "1,93,22,19");

Given an element identifier and a comma-separated string of some identifiers, this will set the value of the dropdown and fix the visual appearance by adding the necessary label objects. The existing function "set exactly" does not seem to achieve that... no time for me to check why. I'm posting this just in case anybody needs a solution to this question as well. My approach works nicely with 2.2.13. I'll check out 2.3.0 to see if the problem still persists.

**Comment by tyan-nguyen** [comment]
I don't know why, but when use setTimeout it's working:
setTimeout (function(){ $('.dropdown').dropdown('set selected', '1'); }, 500);

**Comment by bakeiro** [comment]
same here with timeout, any suggestion? it's this solved in fomantic-UI?

**Comment by lubber-de** [comment]
@bakeiro It's related to the browser implementation of MutationObverser.
My [proposed solution](https://github.com/fomantic/Fomantic-UI/issues/919#issuecomment-518667171) in fomantic-ui was to use the "change values" behavior instead of the timeout
See  https://jsfiddle.net/6tge5q13/
