### ISSUE TITLE
[Form Validation] IE11 not work as expected

### ISSUE THREAD

**Issue by jslixiaolin** [Semantic-Org/Semantic-UI#5525]
hello,this is some bug about form validation.
if the last input element placeholder is Chinese,the form validation will auto active in IE11 browser,which make the last input validated error.
here is code https://jsfiddle.net/xiaolinli/50z8bxxs/  , you need to run the code in your ie11 browser
thanks

**Comment by Banandrew** [comment]
Hi @jslixiaolin, it’s a bug in IE11, and unfortunately, nothing can be done about it on our end. [Here’s the issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/) with all the details, it was fixed in Edge, but they did nothing about it in IE. Apparently, it happens when an input’s placeholder contains non-ascii characters, which the Chinese characters are.
