### ISSUE TITLE
[Icons] Issues on massive icons?

### ISSUE THREAD

**Issue by ForzaSFerrari** [Semantic-Org/Semantic-UI#5556]
Shouldn't it look a bit different at the bottom or is it the normal look on massive icons?
https://jsfiddle.net/7L91d7w4/2/

**Comment by Banandrew** [comment]
Hi @ForzaSFerrari, that’s normal, because `.ui.icon.button`s have their own size classes. The correct markup is:
```HTML
<div class="ui massive icon button">
  <i class="facebook icon"></i>
</div>
```
If you need the buttons to be even bigger, add a custom button size.

**Comment by ForzaSFerrari** [comment]
When you give me the correct markup, why are different sizes in documentation for icons? ;) 

For me I've changed a bit on these things and everything is now in the middle.

**Comment by Banandrew** [comment]
@ForzaSFerrari Because that is how CSS works. If you look at the source, the size of both icons and buttons is controlled by the `font-size` property, and both components use the same variables to set their respective `font-size` values, `@massive` for `.massive`, and so on. So I still stand by what I said, I think it’s the correct way of doing it, you could even override one of the variables in `src/site/globals/site.variables` if you think you’re not going to be using it.

**Comment by Banandrew** [comment]
@ForzaSFerrari Actually, I lied to you, and the default theme sets their own sizes in `icon.variables`—sorry about that. It doesn’t change much, though.

**Comment by ForzaSFerrari** [comment]
No problem. Everyone makes mistakes. From my side I don't always have the experience to implement my things into your things. So I have to do it on my own way. Even if Chrome for example says there's some unknown property names.
