### ISSUE TITLE
[Dropdown] Multiple select send order

### ISSUE THREAD

**Issue by WallaceMielniczki** [Semantic-Org/Semantic-UI#5584]
Preciso enviar varias informações em ordem de seleção no select mas ele "Reorganiza", além disso ele apaga o que foi selecionado do select. Teria uma forma de resolver isso?

**Comment by Banandrew** [comment]
Hi @WallaceMielniczki, `get values` method gets values in the order of selection, can you elaborate? A test case will help, could you please fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/) to show how you use the dropdown component?

**Comment by WallaceMielniczki** [comment]
https://jsfiddle.net/WallaceMielniczki/ca0rovs3/13/ eu preciso enviar sem AJAX pelo method POST tem como?

**Comment by Banandrew** [comment]
@WallaceMielniczki You can’t preserve the order by initializing a dropdown on a `select` element, because that’s how `select` works in HTML. Instead of initializing it on a `select` element, you can [use the full HTML pattern](https://semantic-ui.com/modules/dropdown.html#/usage) instead, here’s an example: https://jsfiddle.net/dmbwrms8

The full HTML pattern allows you to send your values in the order of selection as a value of a hidden `input`. The values will be separated by a delimiter, a comma by default, but you can change it like so:
```JS
$('.ui.dropdown')
  .dropdown({
    keys: {
      delimiter: 188, // Comma keycode.
    }
  })
```
Then you can use something like `explode(',', $request)` on your back-end to create an array from it. If you have more questions, I’ll be happy to answer them in this thread.
