### ISSUE TITLE
[Dropdown] Should Be Able to Set Exactly When Using API

### ISSUE THREAD

**Issue by mbbuehler** [Semantic-Org/Semantic-UI#5601]
I found two issues with the dropdown when using an API for retrieving data:

1. "set exactly" only works after clicking on the dropdown. If you use "set exactly" right after running the fiddle (press upper button), nothing happens.
2. "set exactly" does not change the value of the input

Are there any workarounds for these issues?

http://jsfiddle.net/2vdgwrty/1/#

**Comment by Banandrew** [comment]
Hi @mbbuehler,

1. This would be an equivalent of hitting an endpoint to retrieve some data, and then setting the value; current behavior is expected. You could either return options initially with a page, or do something like this instead of `set exactly`:
```JS
$('.ui.dropdown')
  .dropdown('set value', 'value')
  .dropdown('set text', 'text')
```
2. It doesn’t work, because you’re using `get value` incorrectly. When you initialize a dropdown on a `select` element, the component hides it and generates this markup with `select` instead of `input` for data storage:
```HTML
<div class="ui dropdown">
  <input type="hidden" name="gender">
  <i class="dropdown icon"></i>
  <div class="default text">Gender</div>
  <div class="menu">
    <div class="item" data-value="male">Male</div>
    <div class="item" data-value="female">Female</div>
  </div>
</div>
```
Afterwards, all methods should be called on a `.ui.dropdown`—not on a hidden `select`/`input`. You can also initialize a dropdown on existing markup, it’s much faster.

If you have other questions, I’ll be happy to answer them in this thread. You can use our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI) as well.

**Comment by mbbuehler** [comment]
Hi @Banandrew 
Thank you very much for your reply. The functions work nicely for single selects. 

But for selects with attribute `multiple="multiple"` it won't work like this. Is this behaviour intended? How can I set values and text for multiple selects?

**Comment by Banandrew** [comment]
@mbbuehler `multiple` variation uses the same HTML pattern as the one I posted above, the only difference is in the name, it’ll be `.ui.multiple.selection.dropdown` instead. In case of `multiple` dropdowns, a hidden input stores multiple values with a delimiter, e.g.: `<input type="hidden" name="gender" value="male,female">`. By default, the delimiter is a comma, but it can be anything you like. So, you can use `set value` like so:
```JS
$('.ui.dropdown')
  .dropdown('set value', 'male,female')
```
Instead of `set text`, you could use the `add label` method, which is undocumented, but that’s okay:
```JS
$('.ui.dropdown')
  .dropdown('add label', 'value', 'text', false)
```
The last parameter is a boolean, which tells the method if it should animate a label, you probably want it to be `false`.
