### ISSUE TITLE
[Sidebar] After toggling sidebar then the page unable to scroll down

### ISSUE THREAD

**Issue by jerry9030** [Semantic-Org/Semantic-UI#5604]
I would like to create a parallax scrolling page.
[https://jsfiddle.net/chiahong/je4ygkcj](https://jsfiddle.net/chiahong/je4ygkcj)

To create a parallax scrolling page, so I set
`.pusher {
  height: 100%;
}`

But after toggling sidebar, the page unable to scroll down, what should I do?
Thanks !

**Comment by Banandrew** [comment]
Hi @jerry9030,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)

**Comment by hounsellal** [comment]
Thank you @jerry9030 for posting this question. I had the problem of the pusher not being able to scroll down after toggling away the sidebar (also, when the sidebar was toggled to visible, the pusher would jump to the top). 

After reading your question, I realized that it was because I had set height: 100% on my pusher. I removed that (which I guess I didn't need at all) and everything works fine now. Just a note for others that have experienced this issue.
