### ISSUE TITLE
[Dropdown] Can't get values after invoke $.dropdown('set values', values)

### ISSUE THREAD

**Issue by Eng3l** [Semantic-Org/Semantic-UI#5666]
When a dropdrown values are changed by `$('#dropdown').dropdown('set values', values)` and you call `$('#dropdown').val()` does not return the selected value.

In my code I have two Dropwods one with some years and other that list months that are included in those years. When a years is selected months are updated with `set values` but then I can't get selected month. I order  to deal with this issue I did this:
``` html
<div class='ui form'>
  <div class='field'>
      <label for="year">Year:</label>
      <select name="year" class="ui dropdown" id="year">
        <option value="2017" data-month="[1, 2, 3]">2016</option>
        <option value="2017" data-month="[4, 5, 6]" selected>2017</option>
      </select>
  </div>
  <div class="field">
    <label for="month">Month:</label>
      <select name="year" class="ui dropdown" id="month">
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
      </select>
  </div>
</div>
```

``` javascript
$(function (){
    $('#year').dropdown({
        onChange: function (value, text, $selectedItem) {
            var arr = [];
            var months = $('#year').find(':selected').data('month');
            for (var i = 0; i < months.length; i++) {
                var m = months[i];
                arr.push({value: m, name: m});
            }
            arr[arr.length - 1].selected = true;
            $('#month').dropdown('change values', arr);
        }
    });
  $('#month').dropdown({
       onChange: function (value, text, $selectedItem) {
            $('#month').data('value', value); //To deal with issue
        }
 });
});
```

PS: I tried to make JSfiddle but didn't work 😞  .

**Comment by Banandrew** [comment]
Hi @Eng3l, here’s a working example, hopefully, it will clear things up: https://jsfiddle.net/mma1rwt1/

When you initialize a dropdown on a select element, it hides a select element and uses it only for storage, so it’s pointless to manipulate it directly with methods like `val()`—it basically constructs [this markup](https://semantic-ui.com/modules/dropdown.html#/usage), “Initializing Existing HTML” section, with hidden `select` instead of hidden `input`—so you can also initialize your dropdowns on pre-existing HTML, it’s actually faster. All dropdown component’s methods should be called on already constructed `.ui.dropdown` container, and not hidden form elements.

If you have more questions, I’ll be happy to answer them either in this thread, or in our [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI).

**Comment by Eng3l** [comment]
OK I realize that but I think that it should work with something like this:
``` javascript
$('.ui.dropdown.month').dropdown('get value')
```
But it returns null after setting new values.

**Comment by Banandrew** [comment]
@Eng3l Sorry about that, we’ll investigate. In the meantime, it does work with pre-existing HTML: https://jsfiddle.net/Banandrew/mma1rwt1/2/

**Comment by Eng3l** [comment]
Well, by using onChange I did save temporally the value and get it back when posting AJAX request or submitting form. I will try to find out a way to solve this issue.

Thanks.

**Comment by wrycu** [comment]
This is still an issue.

**Comment by azarisaeed** [comment]
I fixed it by add the same list to my select options too
```
for (var i = 0; i < response.length; i++) {
      var item = response[i];
      inner = inner + "<option value='" + item.value + "'>" + item.name + "</option>";
}
```
