### ISSUE TITLE
fa equivalent

### ISSUE THREAD

**Issue by humbertocruz** [Semantic-Org/Semantic-UI#5674]
hello, there is a json lib with equivalent names for icons by fontawesome ? I am building a app that use semantic ui on admin and react-native for mobile clients. thanks

**Comment by Banandrew** [comment]
Hi @humbertocruz, if I understood you correctly, no. SUI uses the same classes as FA with [the following changes](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/icon.overrides#L8).

**Comment by websevendev** [comment]
If possible it would still be nice to have some sort of a map specifying the relationship between the SUI and FA icon classes, such as

```
// SUI => FA
[
	'lab' => 'flask',
	'mail' => 'envelope',
	'options' => 'sliders',
	'payment' => 'credit-card',
	'privacy' => 'key',
	'protect' => 'shield',
]
```

my use case being Accelerated Mobile Pages where you can only import the normal FontAwesome styles, so if the main website is using Semantic UI icon naming then on AMP pages the classes need to be remapped in order to be displayed.
