### ISSUE TITLE
ui card bottom attached icon buttons, each has a form

### ISSUE THREAD

**Issue by orkhon** [Semantic-Org/Semantic-UI#5676]
I'd like to create a card, which has two bottom attached icon buttons. The issue is, each button has its own form. I tried many things but I couldn't achieve what I'd like to see. 

Here is what I'd like to see (without form): https://i.imgur.com/BCtKBcx.png (buttons are attached to the bottom of the card with equal widths)
Here is what I get (with form): https://i.imgur.com/s7SifO8.png (buttons are sticked to the left with small sizes)
Here is my code:

```
<div class="ui bottom attached icon buttons">
	<form action="#/" method="post" class="ui form">
		<button class="ui button" type="submit">
			<i class="blue refresh icon"></i>
                </button>
	</form>
        <form action="#/" method="post" class="ui form">
                <button class="ui button" type="submit">
			<i class="red remove icon"></i>
                </button>
	</form>
</div>
```

**Comment by Banandrew** [comment]
Hi @orkhon, you’ll have to write custom CSS that you can put in `installation_folder/src/site/elements/button.overrides`. If I was doing it for myself, I’d use JavaScript, because it’d be much quicker than using CSS overrides. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
