### ISSUE TITLE
Semantic.min.css doesn't produce url that starts with  ./

### ISSUE THREAD

**Issue by Artkoch** [Semantic-Org/Semantic-UI#5696]
webpack 2 
semantic-ui ^2.2.13
npm 5.3.0
node v7.7.4

gulp build compiles semantic.min.css in which urls start with / , but in semantic.css file urls start with ./ which is desired outcome for the min file as well.

I'm guessing this is the reasons I'm getting err
```
ERROR in ./~/css-loader?modules!./~/resolve-url-loader!./semantic/dist/semantic.min.css
Module not found: Error: Can't resolve 'themes/default/assets/fonts/icons.woff2' in ...
```

How can I make it compile min file with ./

**Comment by fendy3002** [comment]
This is caused by bug at Gulp Clean CSS tools (or minifyCSS task in semantic ui's gulp). It caused the webpack to try to resolve the path as module path (node_modules one) instead of relative path.

One of the workaround I found is to modify `config/tasks.js` configuration file. Add `rebase: false` attribute to both `settings.minify` and `settings.concatMinify` then rebuild (clean first for sure) using gulp.
