### ISSUE TITLE
[reactjs] Icons have a margin offset which leads to their wrong alignment

### ISSUE THREAD

**Issue by akscram** [Semantic-Org/Semantic-UI#5709]
Icons have a margin offset, that's why they wrongly aligned: https://react.semantic-ui.com/elements/icon
![screenshot from 2017-08-27 23-22-58](https://user-images.githubusercontent.com/596792/29753317-f57c8f3c-8b7f-11e7-9fd9-c937d9d5e971.png)

**Comment by Banandrew** [comment]
Hi, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by akscram** [comment]
@Banandrew Thank you for your response, actually this problem is reproduced for all icons exactly on the page which I mentioned (you can inspect icons on the page): https://react.semantic-ui.com/elements/icon

I also have made it reproducible on JSFiddle: https://jsfiddle.net/t0w4fwm9/3/

**Comment by Banandrew** [comment]
@akscram Thank you, I asked, because I wasn’t sure in what context you used an icon. The margin exists, so that you could place some text next to an icon, and it was aesthetically correct; the menu component has got the `.icon.item` variation that you can use to remove the margin, and the icon component itself has got the `.fitted` variation that should help in other use cases. The following is a standard reply.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
