### ISSUE TITLE
Popup module lacks documentation

### ISSUE THREAD

**Issue by JamesJGoodwin** [Semantic-Org/Semantic-UI#5735]
Hello. I'm having an issue with popup usage. Here's my code:
```javascript
$('.sort-element').accordion({
	selector: {
		accordion: '.sort-element',
		title: '.sorter-description',
		trigger: '.sorter-description',
		content: '.sorter-content'
	}
});
```
As you can see, I've changed default selectors for my own needs and since then I've met some issues that should be documented:
1) How to specify if some exact element have to be hidden or shown on page load?
2) Opening animation is not playing when selectors are changed. Only closing animation appear. And opening animation is nothing but opacity change.

Reproduction link: https://jsfiddle.net/JamesJGoodwin/a3yw61ry/

Regards,
Andrew.

**Comment by Banandrew** [comment]
Hi @JamesJGoodwin, the accordion uses some CSS rules to work. The `selector` property remaps the classes for the JavaScript part of the component, but it cannot automatically provide the necessary styles for it. Whether you want to copy and rename the deafult styles, or simply modify them—is up to you.

If I didn’t miss anything, you only need the following styles to make it work, but you might want to apply more:
```CSS
.sort-element .sorter-description ~ .sorter-content {
  display: none;
}

.sort-element .active.sorter-content {
  display: block;
}
```
Personally, I don’t think the fact that there’s some CSS involved should be documented, at least because it’s always implied in web development. That should answer point 2, as for point 1, it’s documented—`.active.item`/`.active.content` are in the examples, and work properly if the necessary CSS is there.
