### ISSUE TITLE
BUG: semantic ui not allowing double quote inside dropdown

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5750]
Hi,

I created the minimmal example to reproduce this bug.

1) open http://quemfazsite.com.br/temp/teste-criar-site123.php
2) select the second option inside the dropdown menu (bbb) and the script will show the bbb value in a div at the top of the page
3) select the first option inside the dropdown menu (aaa) and the script will show the aaa value in the div at the top of the page;
4) now select the third or forth option, it will display null depending on your browser

I tried using " (double quote) or using &quot; but none of these work. The biggest from is that if you try to retrieve data from that form using PHP it will have null assigned to it.

I really need to use double quote inside the dropdown menu, is there any workaround while the good community tries to fix?

**Comment by Banandrew** [comment]
Hi @batata004, this is somewhat related to the other issue that you opened, you’ll see why. When you initialize the dropdown on a `select` element, it hides a `select` element, creates a dropdown using a certain HTML pattern, and uses that `select` only for storage, so you should be using the dropdown’s methods like `get value` instead of `val()`.

When you initialize the component on a `select`, it takes this already existing `select` and construct a certain HTML pattern out of it, so when you use straight quotes, it actually produces invalid pattern. There’re multiple solutions to the problem:

* Use [pre-existing HTML](https://semantic-ui.com/modules/dropdown.html#/usage) instead of initializing the component on a `select` element directly. You’ll be using something like that:
```HTML
<div class="item" data-value="&quot;test&quot;">&quot;test&quot;</div>
```
* Use [curly quotes](http://practicaltypography.com/straight-and-curly-quotes.html), because it’s typographically correct:
```HTML
<option>ddd &ldquo;ddd&rdquo; ddd</option>
```

**Comment by batata004** [comment]
My Friend thanks for clearing this out. 

1) I can change my code to use `get value` instead of `val()`, not problem at that! BUT when the browser sends the data to the server it does not work. So just changing to "get value" will not solve this problem, unfortunatelly;

2) Why using the code below does not work?

`<option>aaa&quot;aa&quot;aaa</option>`

I think you should not only make it work with `&ldquo;` but also with `&quot;` cause in HTML specs you can even use `&quot;` to escape double qoute inside a HTML parameter and it's valid and will work! Example:

`<div onclick="alert(&quot;hi&quot;);">AA</div>`

So why cant it work with &quot;? It would be much more intuitive...

3) you see my friend, semantic ui has lots of pretty "hard" particularities... even I as a beginner using just a little bit this library I found many problems (you say most of them are not bug, to me most of them are bug per the bug wiki definition). The documentation does not say anything (not even a warning) about most of the things I pointed (take for example the reset issue that I told you earlier and the double quote I told you just now).

I know this is an open community and nobody has to do homework of nobody! I just think if this library wants to be solid and grab traction it should be more intuitive, the behaviour should be more expected instead of tweaks here and there.

Anyway, you dont need to reply this long thread again, I know you already have lots of things on your plate but just think about what I just said...
