### ISSUE TITLE
Is there something like Bootstrap 4 "Spacing utilities"?

### ISSUE THREAD

**Issue by johnunclesam** [Semantic-Org/Semantic-UI#5863]
https://getbootstrap.com/docs/4.0/utilities/spacing/

Is there a way to obtain this in Semantic-UI.

I don't know really well LESS.

These classes are really useful!

**Comment by Banandrew** [comment]
Hi @johnunclesam,

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
* [Official forums](http://forums.semantic-ui.com)

**Comment by johnunclesam** [comment]
This one is a feature request, not an "How to" question, @Banandrew.

Thanks for your work anyway.

**Comment by YamiOdymel** [comment]
I guess this won't be added in Semantic UI since it against with the spirit of Semantic UI. There should be no _global-classes_ in Semantic UI.

**Comment by johnunclesam** [comment]
@YamiOdymel, don't you see the utility of these classes?

**Comment by YamiOdymel** [comment]
Of course I do, I love them when I was using Bootstrap, but we shouldn't bring everything from the other frameworks to Semantic UI (I remember that's why Semantic UI has no hamburger menu).

They are useful for quick layout designing, but it'll be verbose in the mid-late development. It also makes you harder to maintain the styles. You'll have to looking into each of the pages to change the styles instead of just open a single `style.css` to change it.
