### ISSUE TITLE
[Progress] Initializing works only after timeout

### ISSUE THREAD

**Issue by NicoAiko** [Semantic-Org/Semantic-UI#5888]
I don't know, if this is a problem for someone else as well, but I have the following situation.

I use Semantic with VueJS.

When my component is mounted, I call `$('.ui.progress').progress();` like this:

```javascript
mounted() {
  $('.ui.progress').progress();
}
```

I tried several approaches, but what worked was using a `window.setTimeout`, but I find that a dirty hack that's not to be used and better be replaced with some more clean code.

Unfortunately, my snippet seems to work on JSFiddle, so I suppose VueJS to be the one messing up, but I'm not entirely sure...

https://jsfiddle.net/ca0rovs3/97/ is the code I use.

This is how it looks on my page though. 
![image](https://user-images.githubusercontent.com/22343587/31891467-cdbacf78-b806-11e7-8d24-54594b3e2188.png)

**Comment by Banandrew** [comment]
Hi @NicoAiko, I’ve just tried it on my local machine with Vue 2, and it works fine without `setTimeout`. Perhaps, it’s because of nested Vue components? In any case, it’s definitely not a SUI problem, so I’ll be closing the thread as a usage question; I think it’d be best to ask around Vue communities.
