### ISSUE TITLE
[Search] Search popup should be correctly positioned in stackable grid

### ISSUE THREAD

**Issue by bbernhard** [Semantic-Org/Semantic-UI#5920]
**JSFiddle:**
https://jsfiddle.net/r0eydLve/

**Steps to reproduce:**
* Enter something (e.q `Hallo`) in the search bar and wait until the search popup opens. 

As you can see in the JSFiddle (and in the attached screenshot), the popup doesn't get correctly positioned. If you replace the `stackable grid` with `grid`, everything looks fine. 

![semantic-ui-search-bug](https://user-images.githubusercontent.com/5710631/32419520-7bdc7bbe-c27b-11e7-8e21-92b358bf32c2.png)

On a side note: Is it somehow possible to change the shape of the input field? When specifing the class `prompt` for the `input` it's shape automatically changes. However, I would like to keep it rectangular. Is that possible?

Thanks,
Bernhard

**Comment by Banandrew** [comment]
Hi @bbernhard, that’s because of the `.center.aligned.column` that sets `text-align: center;`. I feel like it’s a general CSS issue, but we’ll investigate.

>On a side note: Is it somehow possible to change the shape of the input field? When specifing the class prompt for the input it's shape automatically changes. However, I would like to keep it rectangular. Is that possible?

You’ll have to override the source. Open `installation_folder/src/site/modules/search.variables`, add the following, then rebuild the framework:
```CSS
@promptBorderRadius: @defaultBorderRadius;
```
