### ISSUE TITLE
seamantic ui search for type category is not working

### ISSUE THREAD

**Issue by rushikeshbhadre** [Semantic-Org/Semantic-UI#5939]
Hi all,
I am trying Semantic UI "search" type "category" example by using Local content,
but it is not working, I think local JSON content format is wrong.
can anybody tell whats wrong with code or JSON format?

```html
<div class="ui category search">
  <div class="ui icon input">
    <input class="prompt" type="text" placeholder="Search animals...">
    <i class="search icon"></i>
  </div>
  <div class="results"></div>
</div>
```
```js
  var content = {
    "category1": {
      "name": "Category 1",
      "results": [
        {
          "title": "Result1 Title",
          "description": "Option1 Description"
        },
        {
          "title": "Result2 Title",
          "description": "Option2 Description"
        }
      ]
    },
    "category2": {
      "name": "Category 2",
      "results": [
        {
          "title": "Result3",
          "description": "Option3 Description"
        }
      ]
    }
  };

$('.ui.search').search({
                    source : content,
                    type : 'category'
                });
```

**Comment by vinayakkulkarni** [comment]
Hi @rushikeshbhadre,

As per our guidelines, You can make a test case by forking this [JSFiddle](https://jsfiddle.net/ca0rovs3/)

Also, since this is a usage questions, i urge you to join the [discord chat](https://discord.gg/7vqmGxa) or join us on [gitter](https://gitter.im/Semantic-Org/Semantic-UI) channel to get this resolved ASAP.

Closing this as it's a usage related question.
