### ISSUE TITLE
[Dropdown] - "Element is no longer attached to DOM. Unable to animate. slide down out" using Angular 4

### ISSUE THREAD

**Issue by msalafia** [Semantic-Org/Semantic-UI#5941]
I have implemented a Menu using the Dropdown in an Angular Component. **Sign out** dropdown item is a router link, so clicking on it cause a redirection on another component. When i do this it returns the following error:

> Transition: Element is no longer attached to DOM. Unable to animate.  Use silent setting to surpress this warning in production. slide down out

 This is as it appear:
![image](https://user-images.githubusercontent.com/11465611/32674607-3ad58a16-c654-11e7-9498-1f0c37062b29.png)

and this is the code

```html
<div class="ui right icon dropdown item">
    <img class="ui avatar image" src="../assets/avatar/man-1.svg">
    {{ user.displayName | truncate:18 }}
    <i class="dropdown icon"></i>
    <div class="menu">
        <a class="item"><i class="edit icon"></i> Edit Profile</a>
        <div class="divider"></div>
        <a class="item" [routerLink]="['/auth/signin']"><i class="sign out icon"></i> Sign out</a>
    </div>
</div>
```

After the redirection, every click on the page cause this error. 
I have noticed that causing the **slide down out** animation on the drop down at least one time (e.g clicking on Edit Profile) fix this issue, and the error disappears.

**Comment by Banandrew** [comment]
Hi @msalafia, I know nothing about Angular, but I’m assuming this is an issue with Angular lifecycle, and it would probably be best to ask around Angular communities first. In any case, although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests to keep the board more manageable for maintainers, so I’ll closing the thread because of that.
