### ISSUE TITLE
Icons are not displaying like was expected

### ISSUE THREAD

**Issue by vandolphreyes** [Semantic-Org/Semantic-UI#5942]
I want to use 'alarm mute icon' but it's showing the mic mute icon instead of bell muted icon. Other icons like mute are not behaving properly also.

Im using version 2.1.8. 

Thanks

**Comment by Banandrew** [comment]
Hi @vandolphreyes, it was fixed in `2.2`. If updating to `2.2` is not an option, you’ll have to patch it in `installation_folder/src/site/elements/icon.overrides`. Here’re the latest icon definitions for the reference in case you need them:

https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/themes/default/elements/icon.overrides#L1-L4
