### ISSUE TITLE
icon with name list clashes with list element in message element

### ISSUE THREAD

**Issue by chrispaynter** [Semantic-Org/Semantic-UI#5999]
If you use an icon name list in the message element, the CSS for the actual[ list element ](https://semantic-ui.com/elements/list.html)clashes and causes margin issues.

Here is a screen shot:

<img width="516" alt="screen shot 2017-12-05 at 10 14 40 pm" src="https://user-images.githubusercontent.com/1684083/33633732-bcb6211c-da09-11e7-944b-25f78b6cb491.png">

Here is the react code:

```
<Message
          icon="list"
          header="You haven't shortlisted any applications yet."
          content="Applications you shortlist because you like them, will end up here."
        />

```
And here is the overriding CSS as observed in Chrome browser:

```
.ui.message .list:not(.ui) {
    text-align: left;
    padding: 0;
    opacity: .85;
    list-style-position: inside;
    margin: .5em 0 0;
}
```

Apologies, I would like to try and fix this myself and submit a PR but I am on deadline and will just change icon for now.

**Comment by vinayakkulkarni** [comment]
Dear @chrispaynter,

I'd recommend you fork this[ jsFiddle](https://jsfiddle.net/ca0rovs3/) and present a test-case for further analysis of the issue.

Since this is a usage question, I urge you to ask it in our [Gitter channel](https://gitter.im/Semantic-Org/Semantic-UI) or [Discord Server](https://discord.gg/7vqmGxa)

Closing till there's a test case.
