### ISSUE TITLE
chrome bug - modal

### ISSUE THREAD

**Issue by alexandrestein** [Semantic-Org/Semantic-UI#615]
Hello,

The first time the modal open I cannot scroll down to it's end:
![capture d cran de 2014-02-10 23 04 49](https://f.cloud.github.com/assets/5431025/2131357/6b9cd39e-929f-11e3-94dd-ab139134d138.png)

After it works but it's white at the end of the body:
![capture d cran de 2014-02-10 23 07 17](https://f.cloud.github.com/assets/5431025/2131382/ba1c3e74-929f-11e3-8e89-a646a192951a.png)

The second issue appears on Firefox to. I'm on Ubuntu.

**Comment by xiechao06** [comment]
I've met the same problem, but after debugging, I found the reason is: I put some images into the ".content" tag, and the modal is shown before the image loaded.  something like:
```javascript
var $modal = $('.ui.modal').modal({ options... });
$modal.find('.content').html("<img src=\"real large image\">");
$modal.modal('show');
```
you could refer to http://plnkr.co/edit/uNo0RGX8YLfPjjUtJXUo?p=preview
I resolved this problem by setting the 'height' of '.content img' tag.  
I guess maybe you've done the similar things.

I think this is really a frustrating problem, I hope @jlukic could add warnings (that display images in modal may incur some problems) in documents.
