### ISSUE TITLE
Errors disappear after a few seconds - form validation

### ISSUE THREAD

**Issue by dalearn** [Semantic-Org/Semantic-UI#6383]
I am rather new to Semantic so excuse me if I have done something wrong but as is demonstrated in the fiddle below, when I click on the submit button I see errors appear and after a short while the errors disappear and all that remains is the red ring around the input boxes.  Is this a bug or have I set up something the wrong way?  I would like for the errors to stay there until the input is valid.  (I believe the `on: 'blur'` event)

Fiddle:  https://jsfiddle.net/bz16toec/

**Comment by dk1m** [comment]
I haven't really used the form validation feature much yet, but I can see one odd thing about your example. Each time the Log In button is clicked, you initialize the form (`$('.ui.form.mainForm').form()`). So I tried re-organizing the code to initialize the form just once, and turned the form into a real form using form submission, and the problem seems to go away. I'm not sure exactly why this particular behavior happens though.

https://jsfiddle.net/g8mybLtc/1/

Is this the behavior you were expecting?

**Comment by dalearn** [comment]
Excellent!  That's exactly what I was looking for.  Apparently the javascript doesn't work when put above the html which is why I was doing it the way I was but you have fixed it.
