### ISSUE TITLE
[Progress] Should be empty at 0%

### ISSUE THREAD

**Issue by Kxze** [Semantic-Org/Semantic-UI#6445]
### Steps
1. Create a Progress element at 0%

### Expected Result
Bar should be empty

### Actual Result
Bar is at 2%

### Version
LTS

Is there a particular reason why it behaves like this? If so, is it possible to make it so 0% and 1% represent their actual values instead of 2%?

**Comment by ColinFrick** [comment]
Probably to ensure that the "0%" text is always visible. To really display it as empty, you could set the `@barMinWidth` variable to 0

**Comment by Kxze** [comment]
Makes sense. Thanks!

**Comment by lubber-de** [comment]
We supported both now:  Not showing any progressbar but still having "0%" being displayed :blush: 
See https://github.com/fomantic/Fomantic-UI/pull/412
Supposed to be inlcuded in the upcoming Fomantic-UI 2.7.2 Release

**Comment by KevinKra** [comment]
A little late to the party, but I wasnt entirely sure how to implement it with the above examples 🤷‍♂️ 

That said, reading into @lubber-de 's notes posted above it says that the `min-width` isnt set to 0, so ... if you set the `min-width` to 0 it will go all the way to 0 instead of 2em.

```
const VerticalBar = styled(Progress)`
  grid-column: 1 / 2;
  background-color: ${colors.grey[200]};

  &&& {
    z-index: -1;
    width: 6rem;
    height: 4px;
    border-radius: 0;
    margin: auto;
    transform: rotate(90deg);
    background-color: ${colors.grey[800]};
    .bar {
      border-radius: 0;
      height: 4px;
      min-width: 0;
    }
  }
`;
```
^ Here is my full working example using styled components, `&&&` overrides through specificity and `.bar` targets the bar in the provided semantic-ui element.

(i also made the bar vertical as opposed to horizontal 😏)
