### ISSUE TITLE
ui grid css flex-direction as row confusing.

### ISSUE THREAD

**Issue by sayeko** [Semantic-Org/Semantic-UI#6692]
I'm trying semantic ui grid for layout purpose.
I notice that semantic define the .ui.grid as flex and use flex-direction row
now I don't understand why because grid in generally should be row > columns so the grid should be flex-direction column.
with that I can control on row level height with flex ratio

}

old
.ui.grid {
display: flex;
flex-direction: row;
-ms-flex-wrap: wrap;
flex-wrap: wrap;
align-items: stretch;
padding: 0;

new
.ui.grid {
display: flex;
flex-direction: column;
-ms-flex-wrap: wrap;
flex-wrap: wrap;
align-items: stretch;
padding: 0;

Proposed solution
make the flex-direction in ui.grid as column by default.

version 2.4.0

**Comment by Atulin** [comment]
That's because the most common use for a grid is using it without rows altogether, just as a horizontal flex. Therefore the most-used scenario is made the most available one.

Also, changing it now would break layouts on a lot of websites. And I mean **a lot**. Too breaking of a change for basicaly zero gain besides adhering to some "row->columns" standard.

**Comment by hammy2899** [comment]
@sayeko In SUI you can create a row like flow with girds without defining any rows like this example https://jsfiddle.net/au43hynL/

**Comment by sayeko** [comment]
@hammy2899 yes this was clear from Atulin's answer.
but if I want to control the height ratio between rows you cannot do it.
for example row 1 have flex-grow: 1 and the other row will take double space flex-grow: 2

anyway thanks I will override it and customize for my need.
