### ISSUE TITLE
Make it non-responsive

### ISSUE THREAD

**Issue by hambern** [Semantic-Org/Semantic-UI#732]
I really like Semantic-UI and use it gladly. BUT... I have responsive web-development and I think it's a gimmick and will disappear in a few years. But still.. I like the look and feel of Semantic-UI. So, how do i kill the responsiveness?

**Comment by Narven** [comment]
This was closed, but I have the same issue. I can specify an example. I'm building a desktop app with electron (electron.atom.io). My App is small in size, and that size will never change. If I try to add some code like this:

```
<div class="ui divided items">
  <div class="item">
    <div class="image">
      <img src="images/electron.ico" width="80px">
    </div>
  </div>
  <div class="item">
    <div class="image">
      <img src="images/electron.ico" width="80px">
    </div>
  </div>
  <div class="item">
    <div class="image">
      <img src="images/electron.ico" width="80px">
    </div>
  </div>
</div>
```

It automaticly stacks up all images, because it thinks it is in "mobile" mode. But I want to display the items in that list as normal.

Is there any way without messing around with semantic.css to handle this? thanks

**Comment by jlukic** [comment]
Responsive first items should all include `unstackable` variations which allow you to adjust default behavior. I've opened as a new issue #2901

**Comment by rorysoft** [comment]
Where is this Hambern guy now?

**Comment by Hambern** [comment]
I've changed my mind :)
