### ISSUE TITLE
[Grid] Add Grid Offsets

### ISSUE THREAD

**Issue by davepwsmith** [Semantic-Org/Semantic-UI#863]
It would be good if there was a way to push and pull grid elements x number of columns left or right, since having empty divs seems inelegant...

e.g.

```
<div class="column three wide push 3">STUFF</div>
```
rather than:
```
<div class="column three wide"></div>
<div class="column three wide">STUFF</div>
```

I understand that having both written numbers (`three`) and numerals (`3`) is also not ideal, but I couldn't really see a way around this.

**Comment by jlukic** [comment]
This was decided against.

**Comment by kawazoe** [comment]
@jlukic Do you have any solution to recommend to replace this feature? I would really like to avoid using javascript to handle this in my semantic-ui project. Specifically, since I am already building some of those grids using angular, I would like to avoid conflicting with angular ng-repeat directive.
