### ISSUE TITLE
Full screen modal

### ISSUE THREAD

**Issue by kguner** [Semantic-Org/Semantic-UI#897]
Is there any way to make a modal full screen.

It is useful for modals where you edit a text area or other editor.

Here is an example from shopify: 

![modal](https://cloud.githubusercontent.com/assets/1753047/3334967/1b3be6a4-f809-11e3-9d4b-4bd71d313cfc.png)
![modal-fullscreen](https://cloud.githubusercontent.com/assets/1753047/3334968/1db7deba-f809-11e3-8481-60e5be303e2f.png)

**Comment by nilsi** [comment]
Is there a way to make the modal totally fullscreen and hide modal? 

Best I tried so far is this:

```
$('.login-modal')
            .modal('setting', {
                onShow : function () {
                    $(this).css({
                        'top' : '0',
                        'bottom' : '0',
                        'left' : '0',
                        'right' : '0',
                        'width' : '100%',
                        'height' : '100%',
                        'background-color' : 'rgba(255, 255, 255, 0.90)',
                        'margin' : '0 !important'
                    });
                }
            })
            .modal('hide dimmer')
            .modal('show', 'closable');
```

Second time I open it it looks almost perfect but there is still some margin at the top and bottom and the dimmer is still showing. (Margin gets overridden and need to hide dimmer since my modal is slightly transparent).  If I change the order of  `.modal('hide dimmer')` and `.modal('show', 'closable');` the modal is just flashing and then gone again.

Anyway to do this or I shall implement my own modal? Thanks.

**Comment by cpury** [comment]
I managed to solve this with two steps:

1. Add this to your css (`#fullscreenModal` being the id of your modal):
```css
#fullscreenModal {
	top: 0px;
	position: fixed;
	bottom: 0px;
	left: 0px ;
	right: 0px;
	width: 100% !important;
	height: 100% !important;
	margin: 0 !important;
}
```

2. Open it like this in js:
```js
$('#fullscreenModal').modal('setting', {
  onShow: function () {
    $(this).css({
      display: 'block',
    });
  }
}).modal('show');
