### ISSUE TITLE
Feature Request: "data-*" Attributes Instead of JavaScript

### ISSUE THREAD

**Issue by luxlogica** [Semantic-Org/Semantic-UI#931]
Web **designers** are very different to web **developers**: they use different tools, have different concerns, and specialise on different areas of knowledge. A good web designer will know (some) html and css, but will usually stay away from JavaScript (because "that's programming"). 

Semantic is specially attractive to designers, because of it easy and logical syntax, because many of its basic elements already follow many good design principles, and because it seems less opinionated and easier to customise than most other frameworks. 

Unfortunately, there is some very neat functionality in Semantic, which requires the user to be familiar with JavaScript. Some of it may be simple - a matter of adding one or two lines in a 'script' element in our page - but others require lengthy incursions into the language (like Form Validation) which can be scary. Others - like Transitions - provide no explanation at all outside of the scope of JavaScript usage, and designers will be unlikely to make any use of it at all.

Other frameworks have managed to successfully abstract the JavaScript layer completely by using "data-*" attributes in the required elements. Any information that would normally be passed on to a JavaScript script, can be set in a 'data-' attribute to an arbitrary element. For instance, a "data-check-empty" attribute could be used to flag that a form-validation check is needed as to whether the element is empty or not, and a "data-check-empty-msg" could be used to set a custom message if the validation fails. Similarly, "data-check-min-length", "data-check-max-length", and even a "data-check-regex" could be used to set multiple checks in a single element.

The idea would be, therefore, that anywhere in the current framework where there is a requirement that the user should use JavaScript in order to turn on, configure or access certain features, those features would be available instead via "data-*" attributes.

This means that a designer could continue to deal only with the html elements that they are familiar with, while getting all the benefits of the JavaScript scripts in the background. This type of approach means that the framework would be attractive and accessible to a much wider range of users.

**Comment by jblac** [comment]
new comment on a super old thread, go me!  It's a shame this was declined, as a rails developer, I define my fields like:

~~~ruby
<%= f.input :password, required: true, input_html: { maxlength: 20 } %>
~~~ 
and of course, i can expand or simplify my requirements however i want there.   This outputs the following HTML for the field:

~~~html
<input maxlength="20" class="password required" required="required" aria-required="true" size="20" type="password" name="species[password]" id="species_password"">
~~~

Bootstrap reads the attributes out of the box, if i want to use semantic (which from a UI standpoint I like better) I have to re-define everything I've already defined and I have to do it for all 400 forms in my application?  Seems like unnecessary cost to the semantic users to me.    This is the only reason why I can't take semantic seriously atm.

**Comment by ElEmFurt** [comment]
I was able to achieve **attribute based validation** rather easily using a data attribute and a single function (incase anyone is still in need of this).  My controls have a data-validate attribute with the id in it for the value, so that I can then find all controls with this data-validate attribute and then add them as rules. In my case I just needed an empty validation on it, if other validations are needed, they can also be added as data attributes and then used inside the function below for adding them dynamically.

The advantage of this is that I can call this function after I add dynamic controls as well, and it works just fine.

function SetValidations()
            {
                $('.ui.form').form({
                    inline: true,
                    on: 'submit',
                    transition: 'fade',
                });
                //Add validations dynamically
                $("[data-validate]").each(function () {
                    var validateId = $(this).attr('data-validate');
                    $('.ui.form').form('add rule', validateId, ['empty']);
                });
            }

Also as mentioned above, a developer can create a system of attributes to be used, in a similar manner and the web designer can then easily refer the list of attributes to enable the features needed. I function as both for my applications, so it's rather easy for me to take a decision on what the HTML markup will contain vs. the javascript.

Hope this helps anyone looking for a similar fix.
