### ISSUE TITLE
[Dropdown] Allow initialized dropdowns to attach events to dynamically added menu items

### ISSUE THREAD

**Issue by cowwoc** [Semantic-Org/Semantic-UI#953]
http://stackoverflow.com/a/22214965/14731

We'd like to populate a dropdown menu dynamically. The problem is that we must invoke `dropdown()` each time the menu contents changes (otherwise the items are not clickable) but on the other hand this causes the component's "defaults" to get overwritten. Meaning, "restore defaults" no longer works.

We'd like to be able to notify the module of new menu items without losing the existing state (such as "defaults").

**Comment by aramk** [comment]
@jlukic that's a great addition. I found the issue and was calling `dropdown()` again, but this bind the event handlers twice and causes a `trigger('change')` twice, causing issues in my app the more times I needed to call `dropdown()`. Would it be possible for Semantic-UI to store a variable internally and allow us to call `dropdown()` without the `"refresh"`? That is if the refresh has no effect other than ensuring all events are bound etc. Otherwise the burden lies with the user to store this variable and ensure the correct method is called on both init and an update.

**Comment by jlukic** [comment]
@aramk Since my comment in September, you shouldn't need to use refresh when updating menu content. It automatically calls it internally using DOM Mutations.

**Comment by aramk** [comment]
Cheers @jlukic, I'll try that.

**Comment by ianjonesidau** [comment]
I have a scenario where the options inner HTML changes, but this mutation does not seem to trigger a change in the dropdown()

```html
<option value="2b32ig9bwfvkd">James <span>(33)</span></option>
```

The number updates due to a DOM changes triggered by Meteor.js but the dropdown() does not update. Any way to make this happen?

**Comment by jlukic** [comment]
Is this what you're looking for?
https://github.com/Semantic-Org/Semantic-UI/issues/1789#issuecomment-74102863

**Comment by ianjonesidau** [comment]
@jlukic Meteor.js mutates the DOM, so it handles the AJAX. Your second suggest works for me thanks! 'refresh' then 'setup select'. Is there a 'setup selected' or equivalent?
